using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliant(true)]
[assembly: AssemblyProduct("RISKMASTER X r6")]
[assembly: AssemblyCompany("CSC")]

[assembly: AssemblyCopyright("Copyright (c) 2010, CSC")]
[assembly: AssemblyTrademark("CSC")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyVersion("3.1.467.0")]
[assembly: AssemblyFileVersion("3.1.467.0")]
[assembly: AssemblyInformationalVersion("3.1.467.0")]
