USE [DA_RMX_STAGING]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[ADJUST_DATED_TEXT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[ADJUST_DATED_TEXT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[TEXT_TYPE_CODE] [int] NULL,
	[ADJ_DTTEXT_ROW_ID] [int] NULL,
	[ADJ_ROW_ID] [int] NULL,
	[DATE_ENTERED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENTERED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_ENTERED] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATED_TEXT] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATED_TEXT_HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_ADJUST_DATED_TEXT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CLAIM]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CLAIM](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[EVENT_ID] [int] NULL,
	[EVENT_NUMBER] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLAIM_NUMBER] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLAIM_STATUS_CODE] [int] NULL,
	[LINE_OF_BUS_CODE] [int] NULL,
	[OPEN_FLAG] [smallint] NULL,
	[CLAIM_TYPE_CODE] [int] NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_CLOSED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_OF_CLAIM] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_OF_CLAIM] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FILE_NUMBER] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[METHOD_CLOSED_CODE] [int] NULL,
	[PAYMNT_FROZEN_FLAG] [smallint] NULL,
	[PRIMARY_POLICY_ID] [int] NULL,
	[SERVICE_CODE] [int] NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACCIDENT_DESC_CODE] [int] NULL,
	[ACCIDENT_TYPE_CODE] [int] NULL,
	[DATE_FDDOT_RPT] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_STDOT_RPT] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IN_TRAFFIC_FLAG] [smallint] NULL,
	[POLICE_AGENCY_EID] [int] NULL,
	[PREVENTABLE_FLAG] [smallint] NULL,
	[REPORTABLE_FLAG] [smallint] NULL,
	[ST_DOT_RPT_ID] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EST_COLLECTION] [float] NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_RPTD_TO_RM] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DURATION] [int] NULL,
	[FILING_STATE_ID] [int] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[MCO_EID] [int] NULL,
	[RATE_TABLE_ID] [int] NULL,
	[PLAN_ID] [int] NULL,
	[CLASS_ROW_ID] [int] NULL,
	[TAX_FLAGS] [int] NULL,
	[BEN_CALC_PAY_START] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BEN_CALC_PAY_TO] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIS_TYPE_CODE] [int] NULL,
	[BENEFITS_START] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BENEFITS_THROUGH] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISABIL_FROM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISABIL_TO_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EDI_EXTRACTED] [int] NULL,
	[COMP_RATE] [float] NULL,
	[EXPOSURE_ID] [int] NULL,
	[PENSION_AMT] [float] NULL,
	[SS_AMT] [float] NULL,
	[OTHER_AMT] [float] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LSS_CLAIM_IND] [int] NULL,
	[LEAVE_FLAG] [smallint] NULL,
	[OTH_OFF1] [float] NULL,
	[OTH_OFF2] [float] NULL,
	[OTH_OFF3] [float] NULL,
	[POST_TAX_DED1] [float] NULL,
	[POST_TAX_DED2] [float] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CLAIM] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CLAIM_ADJ_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CLAIM_ADJ_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[ADJ_ROW_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CLAIM_ADJ_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CLAIM_ADJUSTER]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CLAIM_ADJUSTER](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[ADJ_ROW_ID] [int] NULL,
	[ADJUSTER_EID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[CURRENT_ADJ_FLAG] [smallint] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CLAIM_ADJUSTER] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CLAIM_PRG_NOTE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CLAIM_PRG_NOTE](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CL_PROG_NOTE_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[EVENT_ID] [int] NULL,
	[ENTERED_BY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_ENTERED] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_CREATED] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_CREATED] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOTE_TYPE_CODE] [int] NULL,
	[USER_TYPE_CODE] [int] NULL,
	[NOTE_MEMO] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOTE_MEMO_CARETECH] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENTERED_BY_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CLAIM_PRG_NOTE] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CLAIM_STATUS_HIST]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CLAIM_STATUS_HIST](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CL_STATUS_ROW_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[DATE_STATUS_CHGD] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATUS_CODE] [int] NULL,
	[STATUS_CHGD_BY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REASON] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[APPROVED_BY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CLAIM_STATUS_HIST] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CLAIM_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CLAIM_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[TYPEOFREPORT_CODE] [int] NULL,
	[EMPL_ENRL_MCO_CODE] [int] NULL,
	[ABLE_RTW_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PERM_LOSS_NUMB] [float] NULL,
	[PERM_LOSS_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVERLOG_CODE] [int] NULL,
	[OTHEMPLOY_CODE] [int] NULL,
	[PREXISTCON_TEXT] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPOUEMP_TEXT] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CLAIM_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CLAIM_X_LITIGATION]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CLAIM_X_LITIGATION](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[LIT_TYPE_CODE] [int] NULL,
	[LITIGATION_ROW_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[DOCKET_NUMBER] [varchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUIT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COURT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JUDGE_EID] [int] NULL,
	[VENUE_STATE_ID] [int] NULL,
	[COUNTY] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CO_ATTORNEY_EID] [int] NULL,
	[DEMAND_ALLEGATIONS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIT_STATUS_CODE] [int] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CLAIM_X_LITIGATION] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CLAIMANT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CLAIMANT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CLAIMANT_ROW_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[CLAIMANT_EID] [int] NULL,
	[CLAIMANT_TYPE_CODE] [int] NULL,
	[ATTORNEY_EID] [int] NULL,
	[PRIMARY_CLMNT_FLAG] [smallint] NULL,
	[INJURY_DESCRIPTION] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DAMAGE_DESCRIPTION] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLAIM_AMOUNT] [float] NULL,
	[INSURER_EID] [int] NULL,
	[CLAIMANT_NUMBER] [int] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CLAIMANT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CLAIMANT_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CLAIMANT_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CLAIMANT_ROW_ID] [int] NULL,
	[CLAIMANT_EID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CLAIMANT_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CODES]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CODES](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[IND_STANDARD_CODE] [int] NULL,
	[LINE_OF_BUS_CODE] [int] NULL,
	[CODE_ID] [int] NULL,
	[TABLE_ID] [int] NULL,
	[SHORT_CODE] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RELATED_CODE_ID] [int] NULL,
	[DELETED_FLAG] [smallint] NULL,
	[TRIGGER_DATE_FIELD] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFF_START_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFF_END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORG_GROUP_EID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CODES] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[CODES_TEXT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[CODES_TEXT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CODE_ID] [int] NULL,
	[LANGUAGE_CODE] [int] NULL,
	[SHORT_CODE] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODE_DESC] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_CODES_TEXT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DIS_CLASS_TD]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[DIS_CLASS_TD](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[TD_ROW_ID] [int] NULL,
	[CLASS_ID] [int] NULL,
	[WAGES_FROM] [float] NULL,
	[WAGES_TO] [float] NULL,
	[WEEKLY_BENEFIT] [float] NULL,
	[SUPP_AMT] [float] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_DIS_CLASS_TD] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DIS_CLASS_WAIT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[DIS_CLASS_WAIT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[WAIT_ROW_ID] [int] NULL,
	[CLASS_ID] [int] NULL,
	[DIS_TYPE_CODE] [int] NULL,
	[DIS_WAIT_PRD] [int] NULL,
	[DIS_CLNDR_WRK_CODE] [int] NULL,
	[DIS_PRD_TYPE] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_DIS_CLASS_WAIT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DIS_PLAN_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[DIS_PLAN_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PLAN_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_DIS_PLAN_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DIS_PLAN_X_INSURED]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[DIS_PLAN_X_INSURED](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PLAN_ID] [int] NULL,
	[INSURED_EID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_DIS_PLAN_X_INSURED] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DISABILITY_CLASS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[DISABILITY_CLASS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CLASS_ROW_ID] [int] NULL,
	[PLAN_ID] [int] NULL,
	[CLASS_NAME] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLASS_DESC] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ELIG_BENE_PRD] [int] NULL,
	[BENE_PRD_TYPE] [int] NULL,
	[BENE_FROM_DT_TYPE] [int] NULL,
	[DIS_WAIT_PRD] [int] NULL,
	[DIS_CLNDR_WRK_CODE] [int] NULL,
	[DIS_PRD_TYPE] [int] NULL,
	[DIS_MAX_PRD] [int] NULL,
	[DIS_MAX_PRD_TYPE] [int] NULL,
	[FROM_DIS_PRD_TYPE] [int] NULL,
	[ALLOW_EXT] [int] NULL,
	[EXTEND_PRD] [int] NULL,
	[EXTEND_PRD_TYPE] [int] NULL,
	[MAX_TOT_DIS_PRD] [int] NULL,
	[MAX_TOT_PRD_TYPE] [int] NULL,
	[ACTUAL_WORK_WEEK] [smallint] NULL,
	[DAY7_WORK_WEEK] [smallint] NULL,
	[DAY5_WORK_WEEK] [smallint] NULL,
	[OTHER_WORK_WEEK] [smallint] NULL,
	[OTHER_DAYS] [int] NULL,
	[BENE_PRCTG_FLAG] [smallint] NULL,
	[BENE_PER_AMT] [float] NULL,
	[BENE_FLAT_AMT_FLAG] [smallint] NULL,
	[BENE_FLAT_AMT] [float] NULL,
	[BENE_TD_FLAG] [smallint] NULL,
	[BENE_BASED_CODE] [int] NULL,
	[WITHHOLD_FED_ITAX] [smallint] NULL,
	[WITHHOLD_FICA] [smallint] NULL,
	[WEEKLY_BENE_CAP] [float] NULL,
	[MAX_BEN_PER_CLAIM] [float] NULL,
	[MAX_BEN_PER_CAL_YR] [float] NULL,
	[WAGE_FOR_DIS_PRD] [float] NULL,
	[WAGE_FOR_CAL_YR] [float] NULL,
	[TAXABLE_PERCENT] [float] NULL,
	[WITHHOLD_MEDICARE] [smallint] NULL,
	[WITHHOLD_STATE] [smallint] NULL,
	[USE_VOUCHERS] [smallint] NULL,
	[DAY30_WORK_MONTH] [smallint] NULL,
	[ACTUAL_MONTH] [smallint] NULL,
	[UPPER_AGE_LIMIT] [int] NULL,
	[LOWER_AGE_LIMIT] [int] NULL,
	[SUPP_PERCENT] [float] NULL,
	[SUPP_FLAT_AMT] [float] NULL,
	[SUPP_BANK_ACC_ID] [int] NULL,
	[SUPP_SUB_ACC_ID] [int] NULL,
	[SUPP_TR_TYPE_CODE] [int] NULL,
	[SUPP_SEP_PAY_FLAG] [smallint] NULL,
	[PENSION_AMT] [float] NULL,
	[SS_AMT] [float] NULL,
	[OTHER_AMT] [float] NULL,
	[PRORATE_OFF_FLAG] [smallint] NULL,
	[FULLPAY_ONLY_FLAG] [smallint] NULL,
	[OTH_OFF1] [float] NULL,
	[OTH_OFF2] [float] NULL,
	[OTH_OFF3] [float] NULL,
	[POST_TAX_DED1] [float] NULL,
	[POST_TAX_DED2] [float] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_DISABILITY_CLASS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DISABILITY_PLAN]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[DISABILITY_PLAN](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PLAN_ID] [int] NULL,
	[PLAN_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLAN_NAME] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLAN_DESCRIPTION] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLAN_STATUS_CODE] [int] NULL,
	[PREMIUM] [float] NULL,
	[BANK_ACC_ID] [int] NULL,
	[EFFECTIVE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPIRATION_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ISSUE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REVIEW_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RENEWAL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CANCEL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PREF_DAY_CODE] [int] NULL,
	[PREF_PAY_SCH_CODE] [int] NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[START_PAY_PERIOD] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRINT_BEFORE_END] [smallint] NULL,
	[SUB_ACC_ROW_ID] [int] NULL,
	[PREF_DAY_OF_M_CODE] [int] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_DISABILITY_PLAN] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EMP_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EMP_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EMPLOYEE_EID] [int] NULL,
	[COPHYSEXAM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EMP_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EMPLOYEE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EMPLOYEE](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[COUNTY_OF_RESIDNC] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVLIC_STATE] [int] NULL,
	[INSURABLE_FLAG] [smallint] NULL,
	[LAST_VERIFIED_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUM_OF_VIOLATIONS] [int] NULL,
	[TERM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_PERMIT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_PERMIT_NUMBER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMPLOYEE_EID] [int] NULL,
	[ACTIVE_FLAG] [smallint] NULL,
	[EMPLOYEE_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MARITAL_STAT_CODE] [int] NULL,
	[DATE_HIRED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POSITION_CODE] [int] NULL,
	[DEPT_ASSIGNED_EID] [int] NULL,
	[SUPERVISOR_EID] [int] NULL,
	[EXEMPT_STATUS_FLAG] [smallint] NULL,
	[NO_OF_EXEMPTIONS] [int] NULL,
	[FULL_TIME_FLAG] [smallint] NULL,
	[HOURLY_RATE] [float] NULL,
	[WEEKLY_HOURS] [float] NULL,
	[WEEKLY_RATE] [float] NULL,
	[WORK_SUN_FLAG] [smallint] NULL,
	[WORK_MON_FLAG] [smallint] NULL,
	[WORK_TUE_FLAG] [smallint] NULL,
	[WORK_WED_FLAG] [smallint] NULL,
	[WORK_THU_FLAG] [smallint] NULL,
	[WORK_FRI_FLAG] [smallint] NULL,
	[WORK_SAT_FLAG] [smallint] NULL,
	[PAY_TYPE_CODE] [int] NULL,
	[PAY_AMOUNT] [float] NULL,
	[DRIVERS_LIC_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVERSLICTYPECODE] [int] NULL,
	[DATE_DRIVERSLICEXP] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVLIC_RSTRCTCODE] [int] NULL,
	[NCCI_CLASS_CODE] [int] NULL,
	[DATE_OF_DEATH] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SEC_DEPT_EID] [int] NULL,
	[JOB_CLASS_CODE] [int] NULL,
	[MONTHLY_RATE] [float] NULL,
	[ELIG_DIS_BEN_FLAG] [smallint] NULL,
	[DIS_OPTION_CODE] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[ENTITY]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[ENTITY](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[BUSINESS_TYPE_CODE] [int] NULL,
	[COUNTY] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NATURE_OF_BUSINESS] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIC_CODE] [int] NULL,
	[SIC_CODE_DESC] [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WC_FILING_NUMBER] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENTITY_ID] [int] NULL,
	[ENTITY_TABLE_ID] [int] NULL,
	[LAST_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAST_NAME_SOUNDEX] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIRST_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ALSO_KNOWN_AS] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABBREVIATION] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COST_CENTER_CODE] [int] NULL,
	[ADDR1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDR2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CITY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COUNTRY_CODE] [int] NULL,
	[STATE_ID] [int] NULL,
	[ZIP_CODE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARENT_EID] [int] NULL,
	[TAX_ID] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTACT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMAIL_TYPE_CODE] [int] NULL,
	[EMAIL_ADDRESS] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SEX_CODE] [int] NULL,
	[BIRTH_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PHONE1] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PHONE2] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FAX_NUMBER] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DELETED_FLAG] [smallint] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[TRIGGER_DATE_FIELD] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFF_START_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFF_END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARENT_1099_EID] [int] NULL,
	[REPORT_1099_FLAG] [smallint] NULL,
	[MIDDLE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TITLE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAICS_CODE] [int] NULL,
	[RM_USER_ID] [int] NULL,
	[FREEZE_PAYMENTS] [int] NULL,
	[ORGANIZATION_TYPE] [int] NULL,
	[NPI_NUMBER] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MMSEA_TIN_EDT_FLAG] [smallint] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_ENTITY] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[ENTITY_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[ENTITY_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[ENTITY_ID] [int] NULL,
	[INDEX_BUREAU_NUMB] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STE_AGNT_BRU_IDNT] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_ENTITY_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EV_CONCOM_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EV_CONCOM_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EV_CONCOM_ROW_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EV_CONCOM_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EV_X_CONCOM_PROD]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EV_X_CONCOM_PROD](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EV_CONCOM_ROW_ID] [int] NULL,
	[EVENT_ID] [int] NULL,
	[CONCOM_PRODUCT_ID] [int] NULL,
	[FROM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TO_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONCOM_PRODUCT] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EV_X_CONCOM_PROD] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EVENT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EVENT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[COUNTY_OF_INJURY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EVENT_ID] [int] NULL,
	[EVENT_NUMBER] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EVENT_TYPE_CODE] [int] NULL,
	[EVENT_STATUS_CODE] [int] NULL,
	[EVENT_IND_CODE] [int] NULL,
	[EVENT_DESCRIPTION] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BRIEF_DESC] [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEPT_EID] [int] NULL,
	[DEPT_INVOLVED_EID] [int] NULL,
	[ADDR1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDR2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CITY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_ID] [int] NULL,
	[ZIP_CODE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COUNTRY_CODE] [int] NULL,
	[LOCATION_AREA_DESC] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIMARY_LOC_CODE] [int] NULL,
	[LOCATION_TYPE_CODE] [int] NULL,
	[ON_PREMISE_FLAG] [smallint] NULL,
	[NO_OF_INJURIES] [int] NULL,
	[NO_OF_FATALITIES] [int] NULL,
	[CAUSE_CODE] [int] NULL,
	[DATE_OF_EVENT] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_OF_EVENT] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_REPORTED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_REPORTED] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTD_BY_EID] [int] NULL,
	[DATE_RPTD_TO_RM] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_TO_FOLLOW_UP] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACCOUNT_ID] [int] NULL,
	[DATE_PHYS_ADVISED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_PHYS_ADVISED] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TREATMENT_GIVEN] [smallint] NULL,
	[RELEASE_SIGNED] [smallint] NULL,
	[DEPT_HEAD_ADVISED] [smallint] NULL,
	[PHYS_NOTES] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_CARRIER_NOTIF] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SEC_DEPT_EID] [int] NULL,
	[INJURY_FROM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INJURY_TO_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EVENT_DESCRIPTION_HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INT_REQ_FLAG] [smallint] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EVENT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EVENT_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EVENT_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EVENT_ID] [int] NULL,
	[RESOLUVALU_AMT] [float] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EVENT_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EVENT_X_ACTION]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EVENT_X_ACTION](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EVENT_ID] [int] NULL,
	[ACTION_CODE] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EVENT_X_ACTION] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EVENT_X_MEDW_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EVENT_X_MEDW_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EVENT_ID] [int] NULL,
	[PATINT_CODE_A_TEXT] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATINT_CODE_B_TEXT] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATINT_CODE_C_TEXT] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEVICE_CODE_A_TEXT] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEVICE_CODE_B_TEXT] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEVICE_CODE_C_TEXT] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTH_OUTCOME_CODE] [int] NULL,
	[SING_USE_CODE] [int] NULL,
	[REPRO_NAME_ADDR_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EVENT_X_MEDW_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EVENT_X_MEDW_TEST]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EVENT_X_MEDW_TEST](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EV_MW_TEST_ROW_ID] [int] NULL,
	[EVENT_ID] [int] NULL,
	[LAB_TEST] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RESULT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEST_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EVENT_X_MEDW_TEST] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EVENT_X_MEDWATCH]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EVENT_X_MEDWATCH](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EVENT_ID] [int] NULL,
	[UNIT_CODE] [int] NULL,
	[DATE_RPTD_TO_FDA] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_RPTD_TO_MFG] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTD_BY_EID] [int] NULL,
	[RPTD_BY_PRO_FLAG] [smallint] NULL,
	[RPTD_BY_POS_CODE] [int] NULL,
	[RELEVANT_HISTORY] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAST_REPORT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REPORT_YEAR] [int] NULL,
	[REPORT_SERIAL_NO] [int] NULL,
	[ADVERSE_EVENT_FLAG] [smallint] NULL,
	[PRODUCT_PROB_FLAG] [smallint] NULL,
	[LIFE_THREAT_FLAG] [smallint] NULL,
	[HOSPITALIZ_FLAG] [smallint] NULL,
	[DISABILITY_FLAG] [smallint] NULL,
	[CONGENITAL_FLAG] [smallint] NULL,
	[REQD_INTERV_FLAG] [smallint] NULL,
	[FOLLOW_UP_COUNT] [int] NULL,
	[RPT_MANDATORY] [smallint] NULL,
	[MED_TYPE] [int] NULL,
	[MED_NAME] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOSE] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FREQUENCY] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROUTE] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[THERAPY_FROM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[THERAPY_TO_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DURATION] [int] NULL,
	[LOT_NUMBER] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NDC_NUMBER] [int] NULL,
	[EXPIRATION_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MW_EVENT_ABATED] [smallint] NULL,
	[MW_EVNT_REAPPEARED] [smallint] NULL,
	[DIAGNOSIS_TEST] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BRAND_NAME] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EQUIP_TYPE_CODE] [int] NULL,
	[MANUFACTURER_EID] [int] NULL,
	[MODEL_NUMBER] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CATALOG_NUMBER] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERIAL_NUMBER] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHER_NUMBER] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEVICE_OPER_CODE] [int] NULL,
	[IMPLANT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPLANT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AGE_OF_DEVICE] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEV_AVAIL_FOR_EVAL] [smallint] NULL,
	[DEVICE_RETURN_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EQ_LOT_NUMBER] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EQ_EXPIRATION_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHERS_FLAG] [smallint] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EVENT_X_MEDWATCH] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EVENT_X_OSHA]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EVENT_X_OSHA](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[ACTIVITY_WHEN_INJ] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EVENT_ID] [int] NULL,
	[HOW_ACC_OCCURRED] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NO_RULES_FLAG] [smallint] NULL,
	[OBJ_SUBST_THAT_INJ] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RECORDABLE_FLAG] [smallint] NULL,
	[SAFEG_NOTUSED_FLAG] [smallint] NULL,
	[SAFEGUARD_FLAG] [smallint] NULL,
	[PRIVACY_CASE_FLAG] [int] NULL,
	[SHARPS_OBJECT] [int] NULL,
	[SHARPS_BRAND_MAKE] [int] NULL,
	[SAFEG_NOTUSED] [int] NULL,
	[SAFEG_PROVIDED] [int] NULL,
	[RULES_NOT_FOLLOWED] [int] NULL,
	[OSHA_ESTAB_EID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EVENT_X_OSHA] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EVENT_X_OSHA_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EVENT_X_OSHA_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EVENT_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EVENT_X_OSHA_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EVENT_X_OUTCOME]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[EVENT_X_OUTCOME](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EVENT_ID] [int] NULL,
	[OUTCOME_CODE] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EVENT_X_OUTCOME] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[FALL_IND_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[FALL_IND_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EVENT_ID] [int] NULL,
	[HIST_FALL_CODE] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_FALL_IND_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[FALL_INDICATOR]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[FALL_INDICATOR](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EVENT_ID] [int] NULL,
	[COND_PRIOR_CODE] [int] NULL,
	[RAIL_POSITION_CODE] [int] NULL,
	[RESTRAINT_CODE] [int] NULL,
	[BED_POSITION_CODE] [int] NULL,
	[CALL_LIGHT_FLAG] [smallint] NULL,
	[CALL_LIGHT_CODE] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_FALL_INDICATOR] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[FUNDS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[FUNDS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[AUTO_CHECK_DETAIL] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROLLUP_ID] [int] NULL,
	[VOID_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDR1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDR2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTO_CHECK_FLAG] [smallint] NULL,
	[CITY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLAIMANT_EID] [int] NULL,
	[COUNTRY_CODE] [int] NULL,
	[FIRST_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAST_NAME] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRECHECK_FLAG] [smallint] NULL,
	[STATE_ID] [int] NULL,
	[UNIT_ID] [int] NULL,
	[ZIP_CODE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRANS_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[CLAIM_NUMBER] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CTL_NUMBER] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VOID_FLAG] [smallint] NULL,
	[DATE_OF_CHECK] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHECK_MEMO] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRANS_NUMBER] [bigint] NULL,
	[TRANS_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PAYEE_EID] [int] NULL,
	[PAYEE_TYPE_CODE] [int] NULL,
	[ACCOUNT_ID] [int] NULL,
	[AMOUNT] [float] NULL,
	[STATUS_CODE] [int] NULL,
	[FILED_1099_FLAG] [smallint] NULL,
	[CLEARED_FLAG] [smallint] NULL,
	[PAYMENT_FLAG] [smallint] NULL,
	[COLLECTION_FLAG] [smallint] NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOTES] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CRC] [int] NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BATCH_NUMBER] [int] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[ENCLOSURE_FLAG] [smallint] NULL,
	[APPROVE_USER] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_APPROVAL] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUB_ACCOUNT_ID] [int] NULL,
	[SETTLEMENT_FLAG] [smallint] NULL,
	[APPROVER_ID] [int] NULL,
	[VOUCHER_FLAG] [smallint] NULL,
	[WEEKS_PAID_CODE] [int] NULL,
	[NUM_OF_PAID_DAYS] [int] NULL,
	[TAX_PAYMENT_FLAG] [smallint] NULL,
	[RESUBMIT_EDI] [smallint] NULL,
	[SUPP_PAYMENT_FLAG] [smallint] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REISSUE_FLAG] [smallint] NULL,
	[REISSUE_BY] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REISSUE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REISSUE_PARENT_ID] [int] NULL,
	[NOTES_HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REISSUE_REASON_CODE] [int] NULL DEFAULT ((0)),
	[MIDDLE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_FUNDS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[FUNDS_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[FUNDS_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[TRANS_ID] [int] NULL,
	[INT_CLAIM_TEXT] [varchar](21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_FUNDS_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[FUNDS_TRANS_SPLIT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[FUNDS_TRANS_SPLIT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[SUM_AMOUNT] [float] NULL,
	[SPLIT_ROW_ID] [int] NULL,
	[TRANS_ID] [int] NULL,
	[TRANS_TYPE_CODE] [int] NULL,
	[RESERVE_TYPE_CODE] [int] NULL,
	[AMOUNT] [float] NULL,
	[GL_ACCOUNT_CODE] [int] NULL,
	[FROM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TO_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVOICED_BY] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVOICE_AMOUNT] [float] NULL,
	[INVOICE_NUMBER] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PO_NUMBER] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CRC] [int] NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVOICE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BILL_RCVD_BY_CARRIER_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUPP_PAYMENT_FLAG] [smallint] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_FUNDS_TRANS_SPLIT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[FUNDS_TRANS_SPLIT_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[FUNDS_TRANS_SPLIT_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[SPLIT_ROW_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_FUNDS_TRANS_SPLIT_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[PERSON_INVOLVED]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[PERSON_INVOLVED](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[COUNTY_OF_RESIDNC] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVLIC_STATE] [int] NULL,
	[EST_LEN_DISABILITY] [int] NULL,
	[HIRED_IN_STE_FLAG] [smallint] NULL,
	[INSURABLE_FLAG] [smallint] NULL,
	[LAST_VERIFIED_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUM_OF_VIOLATIONS] [int] NULL,
	[OSHA_ACC_DESC] [varchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OSHA_REC_FLAG] [int] NULL,
	[REGULAR_JOB_FLAG] [smallint] NULL,
	[TERM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_PERMIT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_PERMIT_NUMBER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORKDAY_START_TIME] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PI_ROW_ID] [int] NULL,
	[EVENT_ID] [int] NULL,
	[PI_EID] [int] NULL,
	[PI_TYPE_CODE] [int] NULL,
	[INJURY_ILLNESS_FLG] [int] NULL,
	[DATE_OF_DEATH] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REHAB_TEXT] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESC_BY_WITNESS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATIENT_ACCT_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEDICAL_RCD_NO] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INS_PLAN_GROUP_NO] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_OF_ADMISSION] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_OF_DISCHARGE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADM_TYPE_CODE] [int] NULL,
	[ADM_SOURCE_CODE] [int] NULL,
	[ADMISSION_REASON] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACUITY_LEVEL_CODE] [int] NULL,
	[PATIENT_STAT_CODE] [int] NULL,
	[PATIENT_COND_CODE] [int] NULL,
	[DISCHARGE_DSP_CODE] [int] NULL,
	[EXP_LENGTH_OF_STAY] [int] NULL,
	[EXPECTED_COST] [float] NULL,
	[QI_SIGNIF_CODE] [int] NULL,
	[EPISODE_OF_CARE_ID] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATIENT_TYPE_CODE] [int] NULL,
	[MARITAL_STAT_CODE] [int] NULL,
	[RACE_ENTH_CODE] [int] NULL,
	[WEIGHT] [int] NULL,
	[PRIMARY_PAY_CODE] [int] NULL,
	[EMERGENCY_CONTACT] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMERGENCY_CONT_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATIENT_ROOM_NO] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FACILITY_UNIT_CODE] [int] NULL,
	[FACILITY_DEPT_EID] [int] NULL,
	[HCO_ID_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCO_SITE_ID_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WHY_AT_FACILITY] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLAIM_AMOUNT] [float] NULL,
	[LOST_WORK_FLAG] [smallint] NULL,
	[LEN_OF_SVC_DAYS] [int] NULL,
	[POSITION_CODE] [int] NULL,
	[DEPT_ASSIGNED_EID] [int] NULL,
	[SUPERVISOR_EID] [int] NULL,
	[EXEMPT_STATUS_FLAG] [smallint] NULL,
	[NO_OF_EXEMPTIONS] [int] NULL,
	[FULL_TIME_FLAG] [smallint] NULL,
	[HOURLY_RATE] [float] NULL,
	[WEEKLY_HOURS] [float] NULL,
	[WEEKLY_RATE] [float] NULL,
	[WORK_SUN_FLAG] [smallint] NULL,
	[WORK_MON_FLAG] [smallint] NULL,
	[WORK_TUE_FLAG] [smallint] NULL,
	[WORK_WED_FLAG] [smallint] NULL,
	[WORK_THU_FLAG] [smallint] NULL,
	[WORK_FRI_FLAG] [smallint] NULL,
	[WORK_SAT_FLAG] [smallint] NULL,
	[DRIVERS_LIC_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVERSLICTYPECODE] [int] NULL,
	[DATE_DRIVERSLICEXP] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVLIC_RSTRCTCODE] [int] NULL,
	[NCCI_CLASS_CODE] [int] NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INJURY_CAT_CODE] [int] NULL,
	[PAY_AMOUNT] [float] NULL,
	[ACTIVE_FLAG] [smallint] NULL,
	[EMPLOYEE_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_HIRED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISABILITY_CODE] [int] NULL,
	[ILLNESS_CODE] [int] NULL,
	[PAY_TYPE_CODE] [int] NULL,
	[LOST_CONSC_FLAG] [smallint] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[PATIENT_ID] [int] NULL,
	[EST_RTW_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OSHA_ESTAB_EID] [int] NULL,
	[MAJOR_HAND_CODE] [int] NULL,
	[HRANGE_START_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HRANGE_END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JOB_CLASS_CODE] [int] NULL,
	[OTHER_TREATMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHER_MEDCOND] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STD_DISABIL_TYPE] [int] NULL,
	[CUSTOM_FED_TAX_PER] [float] NULL,
	[CUSTOM_SS_TAX_PER] [float] NULL,
	[CUSTOM_MED_TAX_PER] [float] NULL,
	[CUSTOM_ST_TAX_PER] [float] NULL,
	[MONTHLY_RATE] [float] NULL,
	[ELIG_DIS_BEN_FLAG] [smallint] NULL,
	[DIS_OPTION_CODE] [int] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_PERSON_INVOLVED] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[PI_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[PI_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PI_ROW_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_PI_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[PI_X_BODY_PART]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[PI_X_BODY_PART](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PI_ROW_ID] [int] NULL,
	[BODY_PART_CODE] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_PI_X_BODY_PART] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[PI_X_DIAGNOSIS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[PI_X_DIAGNOSIS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PI_ROW_ID] [int] NULL,
	[DIAGNOSIS_CODE] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_PI_X_DIAGNOSIS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[PI_X_INJURY]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[PI_X_INJURY](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PI_ROW_ID] [int] NULL,
	[INJURY_CODE] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_PI_X_INJURY] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[PI_X_TREATMENT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[PI_X_TREATMENT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PI_ROW_ID] [int] NULL,
	[TREATMENT_CODE] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_PI_X_TREATMENT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[PI_X_WORK_LOSS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[PI_X_WORK_LOSS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PI_WL_ROW_ID] [int] NULL,
	[PI_ROW_ID] [int] NULL,
	[DATE_LAST_WORKED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_RETURNED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DURATION] [int] NULL,
	[STATE_DURATION] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_PI_X_WORK_LOSS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[PI_X_WRKLOSS_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[PI_X_WRKLOSS_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PI_WL_ROW_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_PI_X_WRKLOSS_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[POLICY]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[POLICY](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POLICY_ID] [int] NULL,
	[POLICY_NAME] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POLICY_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POLICY_STATUS_CODE] [int] NULL,
	[INSURER_EID] [int] NULL,
	[ISSUE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REVIEW_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RENEWAL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFFECTIVE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPIRATION_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CANCEL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PREMIUM] [float] NULL,
	[TRIGGER_CLAIM_FLAG] [smallint] NULL,
	[PRIMARY_POLICY_FLG] [smallint] NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BROKER_EID] [int] NULL,
	[BANK_ACC_ID] [int] NULL,
	[SUB_ACC_ROW_ID] [int] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_POLICY] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[POLICY_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[POLICY_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[POLICY_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_POLICY_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[RESERVE_CURRENT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[RESERVE_CURRENT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[BALANCE_AMOUNT] [float] NULL,
	[RC_ROW_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[UNIT_ID] [int] NULL,
	[CLAIMANT_EID] [int] NULL,
	[RESERVE_TYPE_CODE] [int] NULL,
	[RESERVE_AMOUNT] [float] NULL,
	[INCURRED_AMOUNT] [float] NULL,
	[COLLECTION_TOTAL] [float] NULL,
	[PAID_TOTAL] [float] NULL,
	[DATE_ENTERED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENTERED_BY_USER] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REASON] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CRC] [int] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[RES_STATUS_CODE] [int] NULL,
	[ALLOCATED_AMOUNT] [float] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_RESERVE_CURRENT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[RESERVE_HISTORY]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[RESERVE_HISTORY](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[BALANCE_AMOUNT] [float] NULL,
	[CHANGE_AMOUNT] [float] NULL,
	[RSV_ROW_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[CLAIMANT_EID] [int] NULL,
	[UNIT_ID] [int] NULL,
	[RESERVE_TYPE_CODE] [int] NULL,
	[RESERVE_AMOUNT] [float] NULL,
	[COLLECTION_TOTAL] [float] NULL,
	[INCURRED_AMOUNT] [float] NULL,
	[PAID_TOTAL] [float] NULL,
	[DATE_ENTERED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENTERED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REASON] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CRC] [int] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[RES_STATUS_CODE] [int] NULL,
	[CLOSED_FLAG] [int] NULL,
	[AUTO_ADJ_FLAG] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_RESERVE_HISTORY] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[UNIT_X_CLAIM]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[UNIT_X_CLAIM](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[UNIT_ROW_ID] [int] NULL,
	[UNIT_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[VEHICLE_MAKE] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_YEAR] [int] NULL,
	[HOME_DEPT_EID] [int] NULL,
	[LICENSE_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_ROW_ID] [int] NULL,
	[DAMAGE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNIT_TYPE_CODE] [int] NULL,
	[VIN] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_UNIT_X_CLAIM] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[UNIT_X_CLAIM_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[UNIT_X_CLAIM_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[UNIT_ROW_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_UNIT_X_CLAIM_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[VEHICLE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[VEHICLE](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[DISPOSAL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LEASE_AMOUNT] [float] NULL,
	[LEASE_EXPIRE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LEASE_FLAG] [smallint] NULL,
	[LEASE_NUMBER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LEASE_TERM] [int] NULL,
	[LEASING_CO_EID] [int] NULL,
	[LICENSE_RNWL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_MODEL] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNIT_ID] [int] NULL,
	[VEHICLE_MAKE] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_YEAR] [int] NULL,
	[UNIT_TYPE_CODE] [int] NULL,
	[HOME_DEPT_EID] [int] NULL,
	[LICENSE_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_ROW_ID] [int] NULL,
	[GROSS_WEIGHT] [int] NULL,
	[VIN] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORIGINAL_COST] [float] NULL,
	[PURCHASE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEDUCTIBLE] [float] NULL,
	[LAST_SERVICE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE_OF_SERVICE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSURANCE_COVERAGE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DELETED_FLAG] [smallint] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_VEHICLE] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[VEHICLE_SUPP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[VEHICLE_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[UNIT_ID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_VEHICLE_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[ERROR_LOG]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[ERROR_LOG] (
	[ERR_LOG_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[MODULE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_FLOW_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATA_FLOW_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERROR_TIME] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERROR_TITLE] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERROR_DESC] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IS_VALIDATION] [int] NULL,
	[ERROR_TABLE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABLE_ROW_ID] [int] NULL,
	[ERROR_COLUMNS] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_ERROR_LOG] PRIMARY KEY CLUSTERED
(
	[ERR_LOG_ROW_ID] ASC,
	[JOBID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DA_STATISTICS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[DA_STATISTICS] (
	[JOBID] [int] NOT NULL,
	[PASS_COUNT] [int] NOT NULL,
	[IS_VALIDATION] [int] NULL,
	[IMPORT_MODULE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABLE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_COUNT] [int] NULL,
	[START_VALID_ROW_COUNT] [int] NULL,
	[START_INVALID_ROW_COUNT] [int] NULL,
	[END_VALID_ROW_COUNT] [int] NULL,
	[END_INVALID_ROW_COUNT] [int] NULL,
	[TOTAL_ROWS] [int] NULL,
	[TOTAL_FAILED_VALIDATIONS] [int] NULL,
	[START_TIME] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[END_TIME] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_DA_STATISTICS] PRIMARY KEY CLUSTERED
(
	[JOBID] ASC,
	[PASS_COUNT] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[DDS_OPTIONSET]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[DDS_OPTIONSET] (
	[JOBID] [int] NOT NULL,
	[ALLOW_NEW_CLAIMS] [int] NULL,
	[ALLOW_NEW_CODES] [int] NULL,
	[ALLOW_NEW_EMPLOYEES] [int] NULL,
	[ALLOW_NEW_DEPARTMENT] [int] NULL,
	[PAYMENTS_AVAILABLE] [int] NULL,
	[ADJUSTER_NOTES_AVAILABLE] [int] NULL,
	[EVENTS_AVAILABLE] [int] NULL,
	[CLAIMS_AVAILABLE] [int] NULL,
	[SHORT_TERM_DISABILITY_AVAILABLE] [int] NULL,
	[MED_WATCH_AVAILABLE] [int] NULL,
	[ENHANCED_NOTES_AVAILABLE] [int] NULL,
	[SET_ADJUSTER_AS_CURRENT] [int] NULL,
	[DONT_CHECK_DUPLICATE_PAYMENTS] [int] NULL,
	[ATTACH_TRANS_ID_TO_CHECK_NO] [int] NULL,
	[CREATE_ENTITY_IF_TAX_ID_EMPTY_GCVA] [int] NULL,
	[ID_CLAIMANT_BY_NAME_GCVA] [int] NULL,
	[ID_CLAIMANT_BY_SUFFIX_GCVA] [int] NULL,
	[UPDATE_CLAIMANT_NAME_GCVA] [int] NULL,
	[UPDATE_CLAIMANT_NAME_WC] [int] NULL,
	[USE_TAX_ID_IN_ENTITY_MATCHES] [int] NULL,
	[PAYMENT_BANK_ACCOUNT] [int] NULL,
	[PAYMENT_SUB_ACCOUNT] [int] NULL,
	[EMPLOYEE_MATCH_BY_NAME] [int] NULL,
	[EMPLOYEE_MATCH_BY_TAX_ID] [int] NULL,
	[EMPLOYEE_MATCH_BY_EMP_NUM] [int] NULL,
	[NON_EMP_MATCH_BY_NAME] [int] NULL,
	[NON_EMP_MATCH_BY_TAX_ID] [int] NULL,
	[MAX_ERRORS] [int] NULL,
	[RECALCULATE_RESERVES] [int] NULL,
	[UPDATE_CLAIMANT_DETAILS] [int] NULL,
	[VALID_START_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VALID_END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[USE_TRANSACTIONS] [int] NULL,
	[PERFORM_VERIFICATION] [int] NULL,
	[VALIDATE_SUPPLEMENTALS] [int] NULL,
	[DIARY_TO_USERS] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EVENT_IMPORTFILE_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEDWATCH_IMPORTFILE_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLAIM_IMPORTFILE_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STD_PLAN_IMPORTFILE_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STD_CLASS_IMPORTFILE_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADJUSTER_IMPORTFILE_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PAYMENT_IMPORTFILE_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENHANCE_NOTES_IMPORTFILE_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
 CONSTRAINT [PK_DDS_OPTIONSET] PRIMARY KEY CLUSTERED
(
	[JOBID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
