;Sdalvi3 EDI Medical Bills 
;DN0502 Billing Type Code
;[ASSIGN %%1=ADD_CODE(CH,1033,CH - Chiropractic (Medical 2.0),BILLTYPE,0)]
;[ASSIGN %%1=ADD_CODE(PD,1033,PD - Podiatry(Medical 2.0),BILLTYPE,0)]
[ASSIGN %%1=ADD_CODE(DD,1033,DD - Dentist or Dental(Medical 2.0),BILLTYPE,0)]
[ASSIGN %%1=ADD_CODE(HS,1033,HS - Hospital(Medical 2.0),BILLTYPE,0)]
[ASSIGN %%1=ADD_CODE(MD,1033,MD - Physician or Medical(Medical 2.0),BILLTYPE,0)]
[ASSIGN %%1=ADD_CODE(O,1033,O - Other(Medical 2.0),BILLTYPE,0)]

;DN0503 Billing Format Code
[ASSIGN %%1=ADD_GLOSSARY(BILLING_FORMAT_CODE,Billing Format Code,10,1033)]
[ASSIGN %%1=ADD_CODE(A,1033,A - Uniform Billing Claim Form Bill Type,BILLING_FORMAT_CODE,0)]
[ASSIGN %%1=ADD_CODE(B,1033,B - Place of Service Code,BILLING_FORMAT_CODE,0)]

;DN0507 Provider Agreement Code
[ASSIGN %%1=ADD_GLOSSARY(PROV_AGRMNT_CODE,Provider Agreement Code,10,1033)]
[ASSIGN %%1=ADD_CODE(H,1033,H - Health Maintenance Organization (HMO) Agreement,PROV_AGRMNT_CODE,0)]
[ASSIGN %%1=ADD_CODE(N,1033,N - No Agreement,PROV_AGRMNT_CODE,0)]
[ASSIGN %%1=ADD_CODE(P,1033,P - Participation Agreement,PROV_AGRMNT_CODE,0)]
[ASSIGN %%1=ADD_CODE(Y,1033,Y - Preferred Provider Organization (PPO) Agreement,PROV_AGRMNT_CODE,0)]

;DN0508 Bill Submission Reason Code
[ASSIGN %%1=ADD_GLOSSARY(BILL_SUB_RSN_CODE,Bill Submission Reason Code,10,1033)]
[ASSIGN %%1=ADD_CODE(00,1033,00 - Original,BILL_SUB_RSN_CODE,0)]
[ASSIGN %%1=ADD_CODE(01,1033,01 - Cancellation,BILL_SUB_RSN_CODE,0)]
[ASSIGN %%1=ADD_CODE(02,1033,02 - Corrected and Verified Original Claim,BILL_SUB_RSN_CODE,0)]
[ASSIGN %%1=ADD_CODE(05,1033,05 - Replace,BILL_SUB_RSN_CODE,0)]
[ASSIGN %%1=ADD_CODE(09,1033,09 - Encounter,BILL_SUB_RSN_CODE,0)]

;DN0515 Contract Type Code
[ASSIGN %%1=ADD_GLOSSARY(CONTRACT_TYPE_CODE,Contract Type Code,10,1033)]
[ASSIGN %%1=ADD_CODE(01,1033,01 - Diagnosis Related Group (DRG),CONTRACT_TYPE_CODE,0)]
[ASSIGN %%1=ADD_CODE(02,1033,02 - Per Diem,CONTRACT_TYPE_CODE,0)]
[ASSIGN %%1=ADD_CODE(03,1033,03 - Variable Per Diem,CONTRACT_TYPE_CODE,0)]
[ASSIGN %%1=ADD_CODE(04,1033,04 - Flat,CONTRACT_TYPE_CODE,0)]
[ASSIGN %%1=ADD_CODE(05,1033,05 - Capitated,CONTRACT_TYPE_CODE,0)]
[ASSIGN %%1=ADD_CODE(06,1033,06 - Percent,CONTRACT_TYPE_CODE,0)]
[ASSIGN %%1=ADD_CODE(09,1033,09 - Other,CONTRACT_TYPE_CODE,0)]

;DN0533 Present on Admission Indicator
[ASSIGN %%1=ADD_GLOSSARY(PRESENT_ON_ADMSN_IND,Present on Admission Indicator,10,1033)]
[ASSIGN %%1=ADD_CODE(N,1033,N - No,PRESENT_ON_ADMSN_IND,0)]
[ASSIGN %%1=ADD_CODE(U,1033,U - Unknown,PRESENT_ON_ADMSN_IND,0)]
[ASSIGN %%1=ADD_CODE(W,1033,W - Not Applicable,PRESENT_ON_ADMSN_IND,0)]
[ASSIGN %%1=ADD_CODE(Y,1033,Y - Yes,PRESENT_ON_ADMSN_IND,0)]

;DN0543 Bill Adjustment Group Code
[ASSIGN %%1=ADD_GLOSSARY(BILL_ADJ_GRP_CODE,Bill Adjustment Group Code,10,1033)]
[ASSIGN %%1=ADD_CODE(CO,1033,CO - Contractual Obligations,BILL_ADJ_GRP_CODE,0)]
[ASSIGN %%1=ADD_CODE(OA,1033,OA - Other Adjustments,BILL_ADJ_GRP_CODE,0)]
[ASSIGN %%1=ADD_CODE(PI,1033,PI - Payer Initiated Reductions,BILL_ADJ_GRP_CODE,0)]
[ASSIGN %%1=ADD_CODE(PR,1033,PR - Patient Responsibility,BILL_ADJ_GRP_CODE,0)]
[ASSIGN %%1=ADD_CODE(RR,1033,RR - Regulatory Requirement,BILL_ADJ_GRP_CODE,0)]

;DN0553 Day(s)/Unit(s) Code
[ASSIGN %%1=ADD_GLOSSARY(DAYS_UNITS_CODE,Day(s)/Unit(s) Code,10,1033)]
[ASSIGN %%1=ADD_CODE(DA,1033,DA - Days,DAYS_UNITS_CODE,0)]
[ASSIGN %%1=ADD_CODE(MJ,1033,MJ - Minutes,DAYS_UNITS_CODE,0)]
[ASSIGN %%1=ADD_CODE(UN,1033,UN - Unit,DAYS_UNITS_CODE,0)]

;DN0562 Dispense as Written Code
[ASSIGN %%1=ADD_GLOSSARY(DISPENSE_WRITTEN_CODE,Dispense as Written Code,10,1033)]
[ASSIGN %%1=ADD_CODE(0,1033,0 - Not Dispense as Written (DAW),DISPENSE_WRITTEN_CODE,0)]
[ASSIGN %%1=ADD_CODE(1,1033,1 - Physician Dispense as Written (DAW),DISPENSE_WRITTEN_CODE,0)]
[ASSIGN %%1=ADD_CODE(2,1033,2 - Patient Dispense as Written (DAW),DISPENSE_WRITTEN_CODE,0)]
[ASSIGN %%1=ADD_CODE(3,1033,3 - Pharmacy Dispense as Written (DAW),DISPENSE_WRITTEN_CODE,0)]
[ASSIGN %%1=ADD_CODE(4,1033,4 - No generic available,DISPENSE_WRITTEN_CODE,0)]
[ASSIGN %%1=ADD_CODE(5,1033,5 - Brand Dispensed as Generic Override,DISPENSE_WRITTEN_CODE,0)]
[ASSIGN %%1=ADD_CODE(6,1033,6 - Override,DISPENSE_WRITTEN_CODE,0)]
[ASSIGN %%1=ADD_CODE(7,1033,7 - Substitution not allowed – Brand Drug mandated by law,DISPENSE_WRITTEN_CODE,0)]
[ASSIGN %%1=ADD_CODE(8,1033,8 - Substitution allowed - Generic Drug not available,DISPENSE_WRITTEN_CODE,0)]
[ASSIGN %%1=ADD_CODE(9,1033,9 - Other,DISPENSE_WRITTEN_CODE,0)]


; DN0291 lump sum payment/settlement type code table and values
[ASSIGN %%1=ADD_GLOSSARY(LUMP_SUM_PMT,Lump Sum Payment,3,1033)]
[ASSIGN %%1=ADD_CODE(AD,1033,Advance,LUMP_SUM_PMT,0)]
[ASSIGN %%1=ADD_CODE(AS,1033,Agreement Stipulated,LUMP_SUM_PMT,0)]
[ASSIGN %%1=ADD_CODE(AW,1033,Award,LUMP_SUM_PMT,0)]
[ASSIGN %%1=ADD_CODE(SF,1033,Settlement Full,LUMP_SUM_PMT,0)]
[ASSIGN %%1=ADD_CODE(SP,1033,Settlement Partial,LUMP_SUM_PMT,0)]


;Medical EDI DN Name Codes
[ASSIGN %%1=ADD_GLOSSARY(EDI_MED_DN_CODES,Medical EDI DN Codes,3,1033)]
[ASSIGN %%1=ADD_CODE(0005,1033,JURISDICTION CLAIM NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0006,1033,INSURER FEIN,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0007,1033,INSURER NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0014,1033,CLAIM ADMINISTRATOR MAILING POSTAL CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0015,1033,CLAIM ADMINISTRATOR CLAIM NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0016,1033,EMPLOYER NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0018,1033,EMPLOYER FEIN,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0019,1033,EMPLOYER PHYSICAL PRIMARYADDRESS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0020,1033,EMPLOYER PHYSICAL SECONDARY ADDRESS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0021,1033,EMPLOYER PHYSICAL CITY,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0022,1033,EMPLOYER PHYSICAL STATE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0023,1033,EMPLOYER PHYSICAL POSTAL CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0031,1033,DATE OF INJURY,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0042,1033,EMPLOYEE SSN,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0043,1033,EMPLOYEE LAST NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0044,1033,EMPLOYEE FIRST NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0045,1033,EMPLOYEE MIDDLE NAME/INITIAL,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0046,1033,EMPLOYEE MAILING PRIMARY ADDRESS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0047,1033,EMPLOYEE MAILING SECONDARY ADDRESS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0048,1033,EMPLOYEE MAILING CITY,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0049,1033,EMPLOYEE MAILING STATE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0050,1033,EMPLOYEE MAILING POSTAL CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0051,1033,EMPLOYEE PHONE NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0052,1033,EMPLOYEE DATE OF BIRTH,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0053,1033,EMPLOYEE GENDER CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0098,1033,SENDER ID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0099,1033,RECEIVER ID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0100,1033,DATE TRANSMISSION SENT,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0101,1033,TIME TRANSMISSION SENT,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0102,1033,ORIGINAL TRANSMISSION DATE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0103,1033,ORIGINAL TRANSMISSION TIME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0108,1033,DATE PROCESSED,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0109,1033,TIME PROCESSED,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0110,1033,ACKNOWLEDGMENT TRANSACTION SET ID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0111,1033,APPLICATION ACKNOWLEDGMENT CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0115,1033,ELEMENT NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0116,1033,ELEMENT ERROR NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0152,1033,EMPLOYEE EMPLOYMENT VISA,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0153,1033,EMPLOYEE GREEN CARD,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0154,1033,EMPLOYEE ID ASSIGNED BY JURISDICTION,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0155,1033,EMPLOYEE MAILING COUNTRY CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0156,1033,EMPLOYEE PASSPORT NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0164,1033,EMPLOYER PHYSICAL COUNTRY CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0187,1033,CLAIM ADMINISTRATOR FEIN,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0188,1033,CLAIM ADMINISTRATOR NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0208,1033,MANAGED CARE ORGANIZATION IDENTIFICATION NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0209,1033,MANAGED CARE ORGANIZATION NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0255,1033,EMPLOYEE LAST NAME SUFFIX,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0266,1033,TRANSACTION TRACKING NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0293,1033,LUMP SUM PAYMENT/SETTLEMENT CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0500,1033,UNIQUE BILL ID NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0501,1033,TOTAL CHARGE PER BILL,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0502,1033,BILLING TYPE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0503,1033,BILLING FORMAT CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0504,1033,FACILITY CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0505,1033,BILL FREQUENCY TYPE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0507,1033,PROVIDER AGREEMENT CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0508,1033,BILL SUBMISSION REASON CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0509,1033,SERVICE BILL DATE(S) RANGE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0510,1033,DATE OF BILL,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0511,1033,DATE INSURER RECEIVED BILL,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0512,1033,DATE INSURER PAID BILL,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0513,1033,ADMISSION DATE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0514,1033,DISCHARGE DATE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0515,1033,CONTRACT TYPE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0516,1033,TOTAL AMOUNT PAID PER BILL,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0520,1033,OUTPATIENT REASON FOR VISIT CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0521,1033,PRINCIPAL DIAGNOSIS CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0522,1033,DIAGNOSIS CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0523,1033,BILLING PROVIDER UNIQUE BILL IDENTIFICATION NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0524,1033,PROCEDURE DATE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0525,1033,PRINCIPAL PROCEDURE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0527,1033,PRESCRIPTION DATE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0528,1033,BILLING PROVIDER LAST/GROUP NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0529,1033,BILLING PROVIDER FIRST NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0530,1033,BILLING PROVIDER MIDDLE/NAME INITIA,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0531,1033,BILLING PROVIDER LAST NAME SUFFIX,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0532,1033,ORIGINATOR TRANSACTION IDENTIFICATION NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0533,1033,PRESENT ON ADMISSION INDICATOR,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0535,1033,ADMITTING DIAGNOSIS CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0537,1033,BILLING PROVIDER PRIMARY SPECIALTY CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0538,1033,BILLING PROVIDER PRIMARY ADDRESS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0539,1033,BILLING PROVIDER SECONDARY ADDRESS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0540,1033,BILLING PROVIDER CITY,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0541,1033,BILLING PROVIDER STATE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0542,1033,BILLING PROVIDER POSTAL CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0543,1033,BILL ADJUSTMENT GROUP CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0544,1033,BILL ADJUSTMENT REASON CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0545,1033,BILL ADJUSTMENT AMOUNT,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0546,1033,BILL ADJUSTMENT UNITS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0547,1033,LINE NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0548,1033,BILLED DRG CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0549,1033,PAID DRG CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0550,1033,PRINCIPAL PROCEDURE DATE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0551,1033,PROCEDURE DESCRIPTION,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0552,1033,TOTAL CHARGE PER LINE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0553,1033,DAY(S)/UNIT(S) CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0554,1033,DAY(S) /UNIT(S) BILLED,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0555,1033,PLACE OF SERVICE BILL CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0556,1033,CONDITION CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0557,1033,DIAGNOSIS POINTER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0559,1033,REVENUE BILLED CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0561,1033,PRESCRIPTION LINE NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0562,1033,DISPENSE AS WRITTEN CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0563,1033,DRUG NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0569,1033,BILLING PROVIDER COUNTRY CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0570,1033,DRUGS/SUPPLIES QUANTITY DISPENSED,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0571,1033,DRUGS/SUPPLIES NUMBER OF DAYS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0572,1033,DRUGS/SUPPLIES BILLED AMOUNT,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0574,1033,TOTAL AMOUNT PAID PER LINE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0576,1033,REVENUE PAID CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0577,1033,ADMISSION TYPE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0579,1033,DRUGS/SUPPLIES DISPENSING FEE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0580,1033,DAY(S)/UNIT(S) PAID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0581,1033,TREATMENT AUTHORIZATION NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0586,1033,RENDERING LINE PROVIDER FEIN,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0587,1033,RENDERING LINE PROVIDER FIRST NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0588,1033,RENDERING LINE PROVIDER LAST NAME SUFFIX,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0589,1033,RENDERING LINE PROVIDER LAST/GROUP NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0591,1033,RENDERING LINE PROVIDER MIDDLE NAME/INITIAL,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0592,1033,RENDERING LINE PROVIDER NATIONAL PROVIDER ID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0595,1033,RENDERING LINE PROVIDER PRIMARY SPECIALTY CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0599,1033,RENDERING LINE PROVIDER STATE LICENSE NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0600,1033,PLACE OF SERVICE LINE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0605,1033,PRESCRIPTION LINE DATE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0605,1033,SERVICE LINE DATE(S) RANGE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0615,1033,REPORTING PERIOD,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0616,1033,INSURER POSTAL CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0622,1033,ADMISSION HOUR,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0623,1033,DISCHARGE HOUR,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0625,1033,HIPPS RATE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0627,1033,LINE ITEM TAX CHARGE AMOUNT,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0628,1033,LINE ITEM TAX PAID AMOUNT,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0629,1033,BILLING PROVIDER FEIN,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0630,1033,BILLING PROVIDER STATE LICENSE NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0634,1033,BILLING PROVIDER NATIONAL PROVIDER ID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0638,1033,RENDERING BILL PROVIDER LAST/GROUP NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0639,1033,RENDERING BILL PROVIDER FIRST NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0640,1033,RENDERING BILL PROVIDER MIDDLE NAME/INITIAL,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0641,1033,RENDERING BILL PROVIDER LAST NAME SUFFIX,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0643,1033,RENDERING BILL PROVIDER STATE LICENSE NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0647,1033,RENDERING BILL PROVIDER NATIONAL PROVIDER ID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0651,1033,RENDERING BILL PROVIDER PRIMARY SPECIALTY CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0658,1033,SUPERVISING PROVIDER LAST/GROUP NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0659,1033,SUPERVISING PROVIDER FIRST NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0660,1033,SUPERVISING PROVIDER MIDDLE NAME/INITIAL,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0661,1033,SUPERVISING PROVIDER LAST NAME SUFFIX,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0663,1033,SUPERVISING PROVIDER STATE LICENSE NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0667,1033,SUPERVISING PROVIDER NATIONAL PROVIDER ID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0671,1033,SUPERVISING PROVIDER PRIMARY SPECIALTY CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0678,1033,FACILITY NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0680,1033,FACILITY STATE LICENSE NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0682,1033,FACILITY NATIONAL PROVIDER ID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0683,1033,FACILITY SERVICE LOCATION ID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0684,1033,FACILITY PRIMARY ADDRESS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0685,1033,FACILITY SECONDARY ADDRESS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0686,1033,FACILITY CITY,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0687,1033,FACILITY STATE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0688,1033,FACILITY POSTAL CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0689,1033,FACILITY COUNTRY CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0690,1033,REFERRING PROVIDER LAST/GROUP NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0691,1033,REFERRING PROVIDER FIRST NAME,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0692,1033,REFERRING PROVIDER MIDDLE NAME/INITIAL,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0693,1033,REFERRING PROVIDER LAST NAME SUFFIX,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0695,1033,REFERRING PROVIDER STATE LICENSE NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0699,1033,REFERRING PROVIDER NATIONAL PROVIDER ID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0704,1033,MANAGED CARE ORGANIZATION FEIN,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0714,1033,HCPCS LINE PROCEDURE BILLED CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0715,1033,JURISDICTION PROCEDURE BILLED CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0717,1033,HCPCS MODIFIER BILLED CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0718,1033,JURISDICTION MODIFIER BILLED CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0719,1033,ADA PROCEDURE BILLED CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0721,1033,NDC BILLED CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0722,1033,ADA PROCEDURE PAID CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0726,1033,HCPCS LINE PROCEDURE PAID CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0727,1033,HCPCS MODIFIER PAID CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0728,1033,NDC PAID CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0729,1033,JURISDICTION PROCEDURE PAID CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0730,1033,JURISDICTION MODIFIER PAID CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0731,1033,SERVICE ADJUSTMENT GROUP CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0732,1033,SERVICE ADJUSTMENT REASON CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0733,1033,SERVICE ADJUSTMENT AMOUNT,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0734,1033,SERVICE ADJUSTMENT UNITS,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0736,1033,OTHER PROCEDURE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0738,1033,TREATMENT LINE AUTHORIZATION NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0741,1033,CONTRACT LINE TYPE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0742,1033,PROVIDER AGREEMENT LINE CODE,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0743,1033,JURISDICTION TRACKING NUMBER,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0760,1033,PRIOR ACTUAL AMOUNT PAID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0761,1033,LINE ITEM PRIOR ACTUAL AMOUNT PAID,EDI_MED_DN_CODES,0)]
[ASSIGN %%1=ADD_CODE(0762,1033,COMPOUND DRUG INDICATOR,EDI_MED_DN_CODES,0)]

;Medical EDI Acknowledgement Codes
[ASSIGN %%1=ADD_GLOSSARY(APP_ACK_CODE,Medical EDI ACK Codes,3,1033)]
[ASSIGN %%1=ADD_CODE(IA,1033,Item Accept,APP_ACK_CODE,0)]
[ASSIGN %%1=ADD_CODE(IE,1033,Item Accept with Error,APP_ACK_CODE,0)]
[ASSIGN %%1=ADD_CODE(IR,1033,Item Reject,APP_ACK_CODE,0)]
[ASSIGN %%1=ADD_CODE(TA,1033,Transaction Set Accept,APP_ACK_CODE,0)]
[ASSIGN %%1=ADD_CODE(TR,1033,Transaction Set Reject,APP_ACK_CODE,0)]

;Medical EDI reference Codes
[ASSIGN %%1=ADD_GLOSSARY(OTI_REF_QUAL,Medical EDI Reference Codes,3,1033)]
[ASSIGN %%1=ADD_CODE(IX,1033,Item Number,OTI_REF_QUAL,0)]
[ASSIGN %%1=ADD_CODE(TN,1033,Transaction Reference Number,OTI_REF_QUAL,0)]

;Medical EDI Action Codes
[ASSIGN %%1=ADD_GLOSSARY(ACTION_CODE_BGN,Medical EDI Action Codes,3,1033)]
[ASSIGN %%1=ADD_CODE(RU,1033,Return. Required when a portion of the transaction set is being accepted,ACTION_CODE_BGN,0)]
[ASSIGN %%1=ADD_CODE(U,1033,Reject. Required when an entire transaction set is being rejected,ACTION_CODE_BGN,0)]
[ASSIGN %%1=ADD_CODE(WQ,1033,Accept. Required when an entire transaction set is being accepted,ACTION_CODE_BGN,0)]

;Medical NDC Paid Codes
[ASSIGN %%1=ADD_GLOSSARY(NDC_PAID_CODE,Medical EDI NDC PAid Codes,3,1033)]


;******************************************************************************************************************
; Add trading partner table to RISKMASTER glossary
;
[ASSIGN %%1=ADD_GLOSSARY(TRADING_PARTNER, Trading Partner Info, 1, 1033)]
[SQL Server] [FORGIVE] CREATE TABLE TRADING_PARTNER(TP_ROW_ID INTEGER NOT NULL,CLAIM_TYPE_IND VARCHAR(1) NULL,DELETED_FLAG INTEGER NOT NULL,JURISDICTION INTEGER NOT NULL,SENDER_ID VARCHAR(9) NULL, SENDER_ZIP VARCHAR(9) NULL, TRADING_PRTNR_ID VARCHAR(9) NULL, TRADING_PRTNR_NAME VARCHAR(50) NULL,TRADING_PRTNR_ZIP VARCHAR(9) NULL,TEST_PROD_IND VARCHAR(1) NULL,DTTM_RCD_ADDED VARCHAR(14) NOT NULL,DTTM_RCD_LAST_UPD VARCHAR(14) NOT NULL,ADDED_BY_USER VARCHAR(8) NOT NULL, UPDATED_BY_USER VARCHAR(8) NOT NULL)
[SQL Server] [FORGIVE_ALTER] ALTER TABLE TRADING_PARTNER ADD CONSTRAINT PK_TRADING_PARTNER PRIMARY KEY(TP_ROW_ID)
[SQL Server] [FORGIVE_ALTER] ALTER TABLE TRADING_PARTNER ADD RECEIVER_ID varchar(9)
[Oracle]     [FORGIVE] CREATE TABLE TRADING_PARTNER(TP_ROW_ID NUMBER(10) NOT NULL,CLAIM_TYPE_IND VARCHAR(1) NULL,DELETED_FLAG NUMBER(10) NOT NULL,JURISDICTION NUMBER(10) NOT NULL,SENDER_ID VARCHAR(9) NULL, SENDER_ZIP VARCHAR(9) NULL, TRADING_PRTNR_ID VARCHAR(9) NULL, TRADING_PRTNR_NAME VARCHAR(50) NULL,TRADING_PRTNR_ZIP VARCHAR(9) NULL,TEST_PROD_IND VARCHAR(1) NULL,DTTM_RCD_ADDED VARCHAR2(14) NOT NULL,DTTM_RCD_LAST_UPD VARCHAR2(14) NOT NULL,ADDED_BY_USER VARCHAR2(8) NOT NULL, UPDATED_BY_USER VARCHAR2(8) NOT NULL)
[Oracle]     [FORGIVE] CREATE UNIQUE INDEX PK_TRADING_PARTNER ON TRADING_PARTNER(TP_ROW_ID)
[Oracle]     [FORGIVE_ALTER] ALTER TABLE TRADING_PARTNER ADD RECEIVER_ID VARCHAR2(9)
;******************************************************************************************************************

; Alter JULIAN_DATE in FL_CTL_NUMBER table
[SQL Server] [FORGIVE] ALTER TABLE FL_CTL_NUMBER ALTER COLUMN JULIAN_DATE VARCHAR(3) NULL
[Oracle] [FORGIVE] ALTER TABLE FL_CTL_NUMBER MODIFY JULIAN_DATE VARCHAR(3)
;******************************************************************************************************************

;System Table Fields
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED Billing Format Code (DN0503),BILLING_FORMAT_CODE,6,0,0,0,0,0,,BILLING_FORMAT_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED Provider Agreement Code (DN0507),PROV_AGRMNT_CODE,6,0,0,0,0,0,,PROV_AGRMNT_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED Bill Submission Reason Code (DN0508),BILL_SUB_RSN_CODE,6,0,0,0,0,0,,BILL_SUB_RSN_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED NDC Paid Code(DN0728),NDC_PAID_CODE,6,0,0,0,0,0,,NDC_PAID_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED Procedure Paid Code(DN0729),JURIS_PROC_PD_CDE,6,0,0,0,0,0,,PROCEDURE_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED PROCEDURE Billed Code(DN0715),JURIS_PROC_BLD_CODE,6,0,0,0,0,0,,PROCEDURE_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED SUPERVISOR (Physician),SUPERVISOR_EID,8,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI Date Insurer Received Bill(DN0511),FL_RCVD_BILL,3,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED Contract Type Code (DN0515),CONTRACT_TYPE_CODE,6,0,0,0,0,0,,CONTRACT_TYPE_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED Admitting Diagnosis Code (DN0535),ADMTNG_DIAG_CODE,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
[ASSIGN %%1=ADD_STATE_FIELD(CLAIM_SUPP,EDI MED Present on Admission Indicator (DN0533),PRESENT_ON_ADMSN_IND,6,0,0,0,0,0,,PRESENT_ON_ADMSN_IND)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED Bill Adjustment Group Code (DN0543),BILL_ADJ_GRP_CODE,6,0,0,0,0,0,,BILL_ADJ_GRP_CODE)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED Day(s)/Unit(s) Code (DN0553),DAYS_UNITS_CODE,6,0,0,0,0,0,,DAYS_UNITS_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED Bill Adjustment Group Code (DN0544),BILL_ADJ_GRP_CODE,6,0,0,0,0,0,,BILL_ADJ_GRP_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI MED Dispense as Written Code (DN0562),DISPENSE_WRITTEN_CODE,6,0,0,0,0,0,,DISPENSE_WRITTEN_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(CLAIM_SUPP,EDI Lump Sum Payment (DN0293),LUMP_SUM_PMT,6,0,0,0,0,0,,LUMP_SUM_PMT)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI Principal ICD Diagnosis Code ,FL_Prin_ICD_DIAG,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI Principal Procedure Code,FL_PRIN_PROC,6,5,0,0,0,0,,PROCEDURE_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,MED EDI PRINCIPAL PROCEDURE DATE(DN0525),PRNCPL_PROC_DATE,3,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,MED EDI ADMISSION TYPE CODE(DN0577),ADMISSION_TYPE_CODE,6,5,0,0,0,0,,ADMISSION_TYPE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,MED EDI OUTPATIENT REASON FOR VISIT CODE(DN0520),OUTPATIENT_VISIT_CODE,6,5,0,0,0,0,,OUTPTNT_RSN_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Emp. Visa (DN0152),EMP_VISA,0,15,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Emp. Green Card (DN0153),GREEN_CARD,0,15,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Emp. Jurisdiction ID (DN0154),JUR_ID,0,15,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Emp. Passport (DN0156),PASSPORT,0,15,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(CLAIM_SUPP,EDI Agency Claim Number (DN0005),AGENCY_CL_NUM,0,25,0,0,0,0,,)]

;*****************************************************************************************
;Creation of EDI_MED_HISTORY Table
[ASSIGN %%1=ADD_GLOSSARY(EDI_MED_HIST, EDI Med History, 1, 1033)]
[ASSIGN %%1=ADD_GLOSSARY(PROCEDURE_CODE, Principal Procedure Code, 3, 1033)]
[ASSIGN %%1=ADD_GLOSSARY(ADMISSION_TYPE, Admission Type Code, 3, 1033)]
[ASSIGN %%1=ADD_GLOSSARY(OUTPTNT_RSN_CODE, Outpatient Reason Code, 3, 1033)]
[ASSIGN %%1=ADD_GLOSSARY(EDI_MEDICAL_HISTORY, EDI Medical History, 1, 1033)]
[SQL Server] [FORGIVE] CREATE TABLE [EDI_MED_HISTORY]( 	[ROW_ID] [int] NOT NULL, 	[SUBMITTER_NAME] [varchar](60) NULL, 	[SUBMITTER_ID] [varchar](80) NULL,	[SUBMITTER_REL_CODE] [varchar](2) NULL,	[SUBMITTER_ID_CODE_NU] [varchar](3) NULL,	[RECEIVER_NAME] [varchar](60) NULL,	[RECEIVER_ID] [varchar](80) NULL,	[RECEIVER_REL_CODE] [varchar](2) NULL,	[RECEIVER_ID_CODE_NU] [varchar](3) NULL,	[APP_ACK_CODE_OTI] [int] NULL,	[REF_ID_QUALIFIER_OTI] [int] NULL,	[REF_IDENTIFICATION_OTI] [varchar](50) NULL,	[APP_SENDER_CODE_OTI] [varchar](15) NULL,	[APP_RECEIVER_CODE_OTI] [varchar](15) NULL,	[DATE_OTI] [varchar](8) NULL,	[TIME_OTI] [varchar](6) NULL,	[GRP_CTL_NUMBER_NU_OTI] [varchar](9) NULL,	[TRANS_SET_CTL_NUM_NU_OTI] [varchar](9) NULL,	[TRANS_SET_ID_CODE_OTI] [varchar](3) NULL,	[VER_RLS_IND_ID_CODE_NU_OTI] [varchar](12) NULL,	[TRANS_PURPOSE_CODE_NU_OTI] [varchar](2) NULL,	[TRANS_TYPE_CODE_NU_OTI] [varchar](2) NULL,	[APP_TYPE_NU_OTI] [varchar](2) NULL,	[ACTION_CODE_NU_OTI] [varchar](2) NULL,	[TRANS_HANDLING_CODE_NU_OTI] [varchar](3) NULL,	[STATUS_RSN_CODE_NU_OTI] [varchar](3) NULL,	[DESCRIPTION_RED] [varchar](80) NULL,	[RLT_DATA_ID_CODE_NU_RED] [varchar](3) NULL,	[AGNCY_QUALIFIER_CODE_RED] [varchar](2) NULL,	[SRC_SUB_QUALIFIER_NU_RED] [varchar](15) NULL,	[CODE_LST_QUALIFIER_CODE_RED] [int] NULL,	[IND_CODE_RED] [int] NULL,	[TRANS_SET_PURPOSE_CODE_BGN] [varchar](2) NULL,	[REF_IDENTIFICATION_BGN] [varchar](50) NULL,	[DATE_BGN] [varchar](8) NULL,	[TIME_BGN] [varchar](6) NULL,	[TIME_CODE_NU_BGN] [varchar](2) NULL,	[REFERENCE_IDENTIFICATION_BGN] [varchar](50) NULL,	[TRANS_TYPE_CODE_NU_BGN] [varchar](2) NULL,	[ACTION_CODE_BGN] [int] NULL,	[SEC_LEVEL_CODE_NU_BGN] [varchar](2) NULL,	[DTTM_QUALIFIER_DTM] [varchar](3) NULL,	[DATE_DTM] [varchar](8) NULL,	[TIME_DTM] [varchar](8) NULL,	[TIME_CODE_NU_DTM] [varchar](2) NULL,	[DTTM_PRD_FORMAT_QUALIFIER_DTM] [varchar](3) NULL,	[DTTM_PRD_DTM] [varchar](35) NULL,	[REF_ID_QUALIFIER_REF] [varchar](3) NULL,	[REF_IDENTIFICATION_REF] [varchar](50) NULL,	[DESCRIPTION_REF] [varchar](80) NULL,	[REF_IDENTIFIER_NU_REF] [varchar](4) NULL,	[NO_OF_INCLUDED_SEGMENTS_SE] [varchar](10) NULL,	[TRANS_SET_CTL_NUM_SE] [varchar](9) NULL,	[AGNCY_QUALIFIER_CODE_LM] [varchar](2) NULL,	[SRC_SUB_QUALIFIER_LM] [varchar](15) NULL,	[TRANS_SET_ID_CODE_ST] [varchar](3) NULL,	[TRANS_SET_CTL_NUM_ST] [varchar](9) NULL,	[IMPLEMENT_CONVENTION_REF_ST] [varchar](35) NULL,	[CODE_LST_QUALIFIER_CODE_LQ] [varchar](3) NULL,	[IND_CODE_LQ] [int] NULL)
[SQL Server] [FORGIVE_ALTER] ALTER TABLE EDI_MED_HISTORY ADD CONSTRAINT PK_EDI_MED_HISTORY PRIMARY KEY(ROW_ID)
[Oracle] [FORGIVE] CREATE TABLE EDI_MED_HISTORY(   ROW_ID NUMBER NOT NULL,   SUBMITTER_NAME VARCHAR2(60),   SUBMITTER_ID VARCHAR2(80),  SUBMITTER_REL_CODE VARCHAR2(2),  SUBMITTER_ID_CODE_NU VARCHAR2(3),  RECEIVER_NAME VARCHAR2(60),  RECEIVER_ID VARCHAR2(80),  RECEIVER_REL_CODE VARCHAR2(2),  RECEIVER_ID_CODE_NU VARCHAR2(3),  APP_ACK_CODE_OTI NUMBER,  REF_ID_QUALIFIER_OTI NUMBER,  REF_IDENTIFICATION_OTI VARCHAR2(50),  APP_SENDER_CODE_OTI VARCHAR2(15),  APP_RECEIVER_CODE_OTI VARCHAR2(15),  DATE_OTI VARCHAR2(8),  TIME_OTI VARCHAR2(6),  GRP_CTL_NUMBER_NU_OTI VARCHAR2(9),  TRANS_SET_CTL_NUM_NU_OTI VARCHAR2(9),  TRANS_SET_ID_CODE_OTI VARCHAR2(3),  VER_RLS_IND_ID_CODE_NU_OTI VARCHAR2(12),  TRANS_PURPOSE_CODE_NU_OTI VARCHAR2(2),  TRANS_TYPE_CODE_NU_OTI VARCHAR2(2),  APP_TYPE_NU_OTI VARCHAR2(2),  ACTION_CODE_NU_OTI VARCHAR2(2),  TRANS_HANDLING_CODE_NU_OTI VARCHAR2(3),  STATUS_RSN_CODE_NU_OTI VARCHAR2(3),  DESCRIPTION_RED VARCHAR2(80),  RLT_DATA_ID_CODE_NU_RED VARCHAR2(3),  AGNCY_QUALIFIER_CODE_RED VARCHAR2(2),  SRC_SUB_QUALIFIER_NU_RED VARCHAR2(15),  CODE_LST_QUALIFIER_CODE_RED NUMBER,  IND_CODE_RED NUMBER,  TRANS_SET_PURPOSE_CODE_BGN VARCHAR2(2),  REF_IDENTIFICATION_BGN VARCHAR2(50),  DATE_BGN VARCHAR2(8),  TIME_BGN VARCHAR2(6),  TIME_CODE_NU_BGN VARCHAR2(2),  REFERENCE_IDENTIFICATION_BGN VARCHAR2(50),  TRANS_TYPE_CODE_NU_BGN VARCHAR2(2),  ACTION_CODE_BGN NUMBER,  SEC_LEVEL_CODE_NU_BGN VARCHAR2(2),  DTTM_QUALIFIER_DTM VARCHAR2(3),  DATE_DTM VARCHAR2(8),  TIME_DTM VARCHAR2(8),  TIME_CODE_NU_DTM VARCHAR2(2),  DTTM_PRD_FORMAT_QUALIFIER_DTM VARCHAR2(3),  DTTM_PRD_DTM VARCHAR2(35),  REF_ID_QUALIFIER_REF VARCHAR2(3),  REF_IDENTIFICATION_REF VARCHAR2(50),  DESCRIPTION_REF VARCHAR2(80),  REF_IDENTIFIER_NU_REF VARCHAR2(4),  NO_OF_INCLUDED_SEGMENTS_SE VARCHAR2(10),  TRANS_SET_CTL_NUM_SE VARCHAR2(9),  AGNCY_QUALIFIER_CODE_LM VARCHAR2(2),  SRC_SUB_QUALIFIER_LM VARCHAR2(15),  TRANS_SET_ID_CODE_ST VARCHAR2(3),  TRANS_SET_CTL_NUM_ST VARCHAR2(9),  IMPLEMENT_CONVENTION_REF_ST VARCHAR2(35),  CODE_LST_QUALIFIER_CODE_LQ VARCHAR2(3),  IND_CODE_LQ NUMBER)
[Oracle] [FORGIVE_ALTER] ALTER TABLE EDI_MED_HISTORY ADD CONSTRAINT PK_EDI_MED_HISTORY PRIMARY KEY(ROW_ID)
;*****************************************************************************************

;********************************************************************
;PI_SUPP Fields
[ASSIGN %%1=ADD_STATE_FIELD(PI_SUPP,Date of Addmission (DN0513),DATE_OF_ADMISSION,3,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(PI_SUPP,Time of Addmisson (DN0622),TIME_OF_ADMISSION,4,6,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(PI_SUPP,Date of Discharge (DN0514),DATE_OF_DISCHARGE,3,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(PI_SUPP,Time of Discharge (DN0623),TIME_OF_DISCHARGE,4,6,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,REVENUE BILLED CODE (DN0559),REV_CODE,0,25,0,0,0,0,,)]

;EDI_MED_EXTRACTED COLUMN
[Oracle] [FORGIVE_ALTER]     ALTER TABLE FUNDS ADD EDI_MED_EXTRACTED NUMBER(10) NULL
[SQL Server] [FORGIVE_ALTER] ALTER TABLE FUNDS ADD EDI_MED_EXTRACTED INTEGER NULL

;STR_PARM_VALUE_LARGE_TEXT Column
[SQL Server][FORGIVE_ALTER] ALTER TABLE PARMS_NAME_VALUE ADD STR_PARM_VALUE_LARGE_TEXT TEXT 
[Oracle] [FORGIVE_ALTER] ALTER TABLE PARMS_NAME_VALUE ADD (STR_PARM_VALUE_LARGE_TEXT CLOB)

;EDI_DETAILS Table
[Oracle]  [FORGIVE_CREATETABLE] CREATE TABLE EDI_DETAILS(BATCH_NUMBER NUMBER(10),EXTRACT_TYPE NUMBER(5),CLAIM_ID NUMBER(10),DTTM_EXTRACTED VARCHAR2(14),EXTRACTED_BY_USER VARCHAR2(8),MTC VARCHAR2(3))
[Oracle]  [FORGIVE_CREATEINDEX] CREATE UNIQUE INDEX IDX_EDIDET_UNIQ ON EDI_DETAILS(BATCH_NUMBER,CLAIM_ID)
[SQL Server] [FORGIVE_CREATETABLE] CREATE TABLE EDI_DETAILS(BATCH_NUMBER INTEGER,EXTRACT_TYPE SMALLINT,CLAIM_ID INTEGER,DTTM_EXTRACTED VARCHAR(14),EXTRACTED_BY_USER VARCHAR(8),MTC VARCHAR(3))
[SQL Server] [FORGIVE_CREATEINDEX] CREATE UNIQUE INDEX IDX_EDIDET_UNIQ ON EDI_DETAILS(BATCH_NUMBER,CLAIM_ID)

;FL_FAC_NPI_TEXT Column
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Facility NPI,FL_FAC_NPI_TEXT,0,10,0,0,0,0,,)]
;mkaur24 06/19/2017
[ASSIGN %%1=ADD_STATE_FIELD(ENTITY_SUPP,EDI Insurer Type (DN0185),INSRUR_TYP,6,0,0,0,0,0,,INSURER_TYPE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI Benefit Adjustment Amount R3 (DN0093),ADJUST_AMT,2,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI Benefit Adjustment Start Date R3 (DN0094),ADJUST_START,3,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI Benefit Adjustment End Date R3 (DN0125),ADJUST_END,3,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(ENTITY_SUPP,EDI  R3 Claim Production Implementation Date, IAIA_IIICM_PD_DATE,3,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(ENTITY_SUPP,EDI Use Negative Payment,NEG_PAYMENT_FLAG,6,0,0,0,0,0,,YES_NO)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Pre-Existing Disability Ind (DN0069),PREEXIST,6,0,0,0,0,0,,YES_NO)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Employee Last Name Suffix (DN0255),NAME_SUFFIX_TEXT,0,4,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Tax Filing Status (DN0158),TAX_STATUS_EDI,6,0,0,0,0,0,,TAX_STATUS_EDI)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Release SSN Ind (DN0157),RLS_SSN,6,0,0,0,0,0,,YES_NO)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI No. of Withholdings (DN0214),WHOLDNGS,1,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Release Medical Records Ind (DN0150),RLS_MED,6,0,0,0,0,0,,YES_NO)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Employee ID Type (DN0270),EMP_ID_TYPE,6,0,0,0,0,0,,ID_TYPE)]
[ASSIGN %%1=ADD_STATE_FIELD(EMP_SUPP,EDI Education Level (DN0151),ED_LEVEL,1,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(CLAIM_SUPP,EDI Insolvent Insurer FEIN (DN0292),INSOLV_FEIN,0,9,0,0,0,0,,)]

;Florida Medical Bills Rev-F Dbupgrade Merged Changes

;   *** Please add new SQL at the end. ***
;
;************************************************************************************
; JM 09/27/2005 Florida Medical Bills EDI code tables
;************************************************************************************
;
;************************************************************************************
; JM Added Admission and Discharge Hours code table and values
;
[ASSIGN %%1=ADD_GLOSSARY(FL_HOURS,Florida Admission and Discharge Hours,3,1033)]
[ASSIGN %%1=ADD_CODE(00,1033,12:00 - 12:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(01,1033,1:00 - 1:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(02,1033,2:00 - 2:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(03,1033,3:00 - 3:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(04,1033,4:00 - 4:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(05,1033,5:00 - 5:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(06,1033,6:00 - 6:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(07,1033,7:00 - 7:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(08,1033,8:00 - 8:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(09,1033,9:00 - 9:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(10,1033,10:00 - 10:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(11,1033,11:00 - 11:59 AM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(12,1033,12:00 - 12:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(13,1033,1:00 - 1:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(14,1033,2:00 - 2:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(15,1033,3:00 - 3:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(16,1033,4:00 - 4:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(17,1033,5:00 - 5:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(18,1033,6:00 - 6:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(19,1033,7:00 - 7:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(20,1033,8:00 - 8:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(21,1033,9:00 - 9:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(22,1033,10:00 - 10:59 PM,FL_HOURS,0)]
[ASSIGN %%1=ADD_CODE(23,1033,11:00 - 11:59 PM,FL_HOURS,0)]
;
;************************************************************************************
; JM Added Payment Plan code table and values
;
[ASSIGN %%1=ADD_GLOSSARY(FL_PAYMENT_PLAN,Florida Payment Plan,3,1033)]
[ASSIGN %%1=ADD_CODE(CA,1033,Contracted Amount,FL_PAYMENT_PLAN,0)]
[ASSIGN %%1=ADD_CODE(MC,1033,Managed Care,FL_PAYMENT_PLAN,0)]
[ASSIGN %%1=ADD_CODE(RM,1033,Reimbursement Manual,FL_PAYMENT_PLAN,0)]
;
;************************************************************************************
; JM added Procedure Coding Method code table and values
;
;[ASSIGN %%1=ADD_GLOSSARY(FL_PROC_METHOD,Florida Procedure Coding Method,10,1033)]
;[ASSIGN %%1=ADD_CODE(4,1033,CPT Codes,FL_PROC_METHOD,0)]
;[ASSIGN %%1=ADD_CODE(5,1033,HCPCS Codes,FL_PROC_METHOD,0)]
;[ASSIGN %%1=ADD_CODE(9,1033,ICD-9 Codes,FL_PROC_METHOD,0)]
;
;
;************************************************************************************
; JM added Reason Code code table and values
;
[ASSIGN %%1=ADD_GLOSSARY(FL_REASON_CODE,Florida Medical Bill Reason Code,10,1033)]
[ASSIGN %%1=ADD_CODE(00,1033,Original Submission to the division,FL_REASON_CODE,0)]
[ASSIGN %%1=ADD_CODE(01,1033,Cancel/Withdraw–report sent to in error,FL_REASON_CODE,0)]
[ASSIGN %%1=ADD_CODE(02,1033,Correction of report previously rejected,FL_REASON_CODE,0)]
[ASSIGN %%1=ADD_CODE(03,1033,Replacement report for claims previously accepted,FL_REASON_CODE,0)]
[ASSIGN %%1=ADD_CODE(99,1033,Automatically Select Report Reason Code 00 or 02,FL_REASON_CODE,0)]
;
;
;************************************************************************************
; JM Added Type of Admission code table and values
;
[ASSIGN %%1=ADD_GLOSSARY(FL_ADMISSION_TYPE,Florida Admission Type,3,1033)]
[ASSIGN %%1=ADD_CODE(1,1033,Emergency,FL_ADMISSION_TYPE,0)]
[ASSIGN %%1=ADD_CODE(2,1033,Urgent,FL_ADMISSION_TYPE,0)]
[ASSIGN %%1=ADD_CODE(3,1033,Elective,FL_ADMISSION_TYPE,0)]
[ASSIGN %%1=ADD_CODE(4,1033,New Born,FL_ADMISSION_TYPE,0)]
;
;
;************************************************************************************
; JM Added Type of Report code table and values
;
[ASSIGN %%1=ADD_GLOSSARY(FL_REPORT_TYPE,Florida Report Type,3,1033)]
[ASSIGN %%1=ADD_CODE(111,1033,Inpatient Hospital [111],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(112,1033,Inpatient Hospital [112],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(113,1033,Inpatient Hospital [113],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(114,1033,Inpatient Hospital [114],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(117,1033,Inpatient Hospital [117],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(118,1033,Inpatient Hospital [118],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(331,1033,Home Health [331],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(332,1033,Home Health [332],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(333,1033,Home Health [333],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(334,1033,Home Health [334],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(337,1033,Home Health [337],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(338,1033,Home Health [338],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(339,1033,Home Health [339],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(813,1033,Hospice [813],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(817,1033,Hospice [817],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(818,1033,Hospice [818],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(823,1033,Hospice [823],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(827,1033,Hospice [827],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(828,1033,Hospice [828],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(212,1033,LTC and Assisted Living [212],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(213,1033,LTC and Assisted Living [213],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(214,1033,LTC and Assisted Living [214],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(216,1033,LTC and Assisted Living [216],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(217,1033,LTC and Assisted Living [217],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(218,1033,LTC and Assisted Living [218],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(131,1033,Outpatients [131],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(137,1033,Outpatients [137],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(138,1033,Outpatients [138],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(891,1033,PPEC [891],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(897,1033,PPEC [897],FL_REPORT_TYPE,0)]
[ASSIGN %%1=ADD_CODE(898,1033,PPEC [898],FL_REPORT_TYPE,0)]
;
;*****************************************************************************************************************
; JM 09/27/2005 Supplemental Fields for Florida Medical Bills EDI
;
;*****************************************************************************************************************
; Claim Supplemental Fields
;
;Submitter Location
;
[ASSIGN %%1=ADD_STATE_FIELD(CLAIM_SUPP,EDI FL Submitter Location,FL_SUB_LOC,0,20,0,0,0,0,,)]
;
;*****************************************************************************************************************
; Funds Supplemental Fields
;
;Admission Date
;Admission Hour
;Date Insurer Received Bill from Provider
;Date of Outpatient Service
;Diagnosis Code 1
;Diagnosis Code 2
;Diagnosis Code 3
;Diagnosis Code 4
;Discharge Hour
;Other Procedure Code
;Payment Plan
;Principal Procedure Code
;Procedure Coding Method
;Provider
;Report Reason
;Type of Admission/Visit
;Type of Report
;
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Admission Date,FL_ADMISSN,3,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Admission Time,FL_AD_HOUR,6,0,0,0,0,0,,FL_HOURS)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Admission/Visit Type,FL_ADMIT_TYPE,6,0,0,0,0,0,,FL_ADMISSION_TYPE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Date Insurer Received Bill from Provider,FL_RCVD_BILL,3,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Date of Outpatient Service,FL_PT_SRVC,3,0,0,0,0,0,,)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Diagnosis Code 1,FL_DIAG_1,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Diagnosis Code 2,FL_DIAG_2,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Diagnosis Code 3,FL_DIAG_3,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Diagnosis Code 4,FL_DIAG_4,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Discharge Hour,FL_DC_HOUR,6,0,0,0,0,0,,FL_HOURS)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Other Procedure Code,FL_OTHER_PROC,0,5,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Payment Plan,FL_PAY_PLAN,6,0,0,0,0,0,,FL_PAYMENT_PLAN)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Principal Procedure Code,FL_PRIN_PROC,0,5,0,0,0,0,,)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Procedure Coding Method,FL_PROC_METHOD,6,0,0,0,0,0,,FL_PROC_METHOD)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Provider,FL_PROVIDER,8,0,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Report Reason,FL_RPT_REAS,6,0,0,0,0,0,,FL_REASON_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Report Type,FL_RPT_TYPE,6,0,0,0,0,0,,FL_REPORT_TYPE)]
;*****************************************************************************************************************
; Entity Supplemental Fields
;
;Insurer Code Number
;Insurer Tax Id
;TPA Code Number
;
;jtodd22 06/24/2010 --deprecitated by base product development --[ASSIGN %%1=ADD_STATE_FIELD(ENTITY_SUPP,EDI FL Insurer Code Number,FL_INSR_NUM,0,5,0,0,0,0,,)]
;jtodd22 06/24/2010 --deprecitated by Florida--revision "E" uses Federal Tax ID [ASSIGN %%1=ADD_STATE_FIELD(ENTITY_SUPP,EDI FL Insurer Tax ID,FL_TAX_ID,0,9,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(ENTITY_SUPP,EDI FL TPA Code Number,FL_TPA_NUM,0,30,0,0,0,0,,)]
;
;
;************************************************************************************
; JM 11/18/2005 Florida Medical Bills Enhancements EDI code tables
;************************************************************************************
;
;
;************************************************************************************
; JM Added Pre-Payment Indicator code table and values
;
[ASSIGN %%1=ADD_GLOSSARY(FL_PRE_PMT,Florida Pre-Payment Indicator,3,1033)]
[ASSIGN %%1=ADD_CODE(E,1033,Employee Reimbursed,FL_PRE_PMT,0)]
[ASSIGN %%1=ADD_CODE(P,1033,Agreement between Provider and Insurer,FL_PRE_PMT,0)]
;
;*****************************************************************************************************************
; JM 11/18/2005 Supplemental Fields for Florida Medical Bills Enhancements EDI
;
;*****************************************************************************************************************
; Funds Supplemental Fields
;
;Duplicate Claim Override Indicator
;Pre-Payment Indicator

[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Duplicate Claim Override Indicator,FL_DUP_IND,6,0,0,0,0,0,,YES_NO)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Pre-Payment Indicator,FL_PRE_PMT,6,0,0,0,0,0,,FL_PRE_PMT)]
;
;jtodd22 07/10/2006 MITS 7489
;2006 MEIG, change to Revision C
;                        123456789012345678
[ASSIGN %%1=ADD_GLOSSARY(FL_PAYTCODE_CODE,Florida Payment Code,3,1033)]
;                            12345678901234567890123456789012345678901234567890
[ASSIGN %%1=ADD_CODE(R1,1033,Dates based on insurer payment/receipt-Reimbus Man,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(M1,1033,Dates based on insurer payment/receipt-Managed Car,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(C1,1033,Dates based on insurer payment/receipt-Contrtd Amt,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(R2,1033,Dates based on entity payment/receipt-Reimbus Manl,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(M2,1033,Dates based on entity payment/receipt-Managed Care,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(C2,1033,Dates based on entity payment/receipt-Contrted Amt,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(R3,1033,Dates based on entity payment-Reimbursement Manual,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(C3,1033,Dates based on entity payment-Managed Care        ,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(M3,1033,Dates based on entity payment-Contracted Amount   ,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(R4,1033,Dates based on insurer payment-Reimbursement Manul,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(R4,1033,Dates based on insurer payment-Managed Care       ,FL_PAYTCODE_CODE,0)]
[ASSIGN %%1=ADD_CODE(R4,1033,Dates based on insurer payment-Contracted Amount  ,FL_PAYTCODE_CODE,0)]
;
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Payment Code,FL_PAYTCODE_CODE,6,0,0,0,0,0,,FL_PAYTCODE_CODE)]
;
[FORGIVE_INSERT] INSERT INTO PARMS_NAME_VALUE (PARM_CATEGORY,PARM_NAME,STR_PARM_VALUE,PARM_DESC) VALUES (300,'Florida 2006 Date','20060901','Effective date of changes to Florida Medical Bills for EDI')
;end MITS 7489
;
;
;*****************************************************************************************************************
; JM 04/09/2007 Florida Medical Bills Revision D
;
;************************************************************************************
; Added Schedule/Unscheduled Indicator code table and values
;
[ASSIGN %%1=ADD_GLOSSARY(FL_SCHEDULED_IND,Florida Scheduled/Unscheduled Indicator,3,1033)]
[ASSIGN %%1=ADD_CODE(S,1033,Bill related to a scheduled outpatient procedure,FL_SCHEDULED_IND,0)]
[ASSIGN %%1=ADD_CODE(U,1033,Bill related to non-scheduled outpatient procedure,FL_SCHEDULED_IND,0)]
;
;*****************************************************************************************************************
; Funds Supplemental Fields
;
;Operation Physician
;Diagnosis Code 5-7
;Primary Diagnosis Code
;External Cause of Injury Code 1-2
;Other Procedure Code B-E
;Scheduled/Unscheduled Indicator
;Implant Total Paid
;
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Operating Physician,FL_OPER_PHYS,8,0,0,0,0,0,,)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Primary Diagnosis Code ,FL_PRIMARY_DIAG,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Diagnosis Code 5,FL_DIAG_5,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Diagnosis Code 6,FL_DIAG_6,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Diagnosis Code 7,FL_DIAG_7,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Cause Of Injury Code 1,FL_CAUSE_1,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Cause Of Injury Code 2,FL_CAUSE_2,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Cause Of Injury Code 3,FL_CAUSE_3,6,0,0,0,0,0,,DIAGNOSIS_CODE)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Other Procedure Code B,FL_OTHER_PROC_B,0,5,0,0,0,0,,)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Other Procedure Code C,FL_OTHER_PROC_C,0,5,0,0,0,0,,)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Other Procedure Code D,FL_OTHER_PROC_D,0,5,0,0,0,0,,)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Other Procedure Code E,FL_OTHER_PROC_E,0,5,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Scheduled/Unscheduled Indicator,FL_SCHEDULED_IND,6,0,0,0,0,0,,FL_SCHEDULED_IND)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Implant Total Paid,FL_IMPLANT_TOTAL,2,0,0,0,0,0,,)]
;
;
;
;*****************************************************************************************************************
; MITS 9926 JM 06/28/2007 Florida Medical Bills Revision D
; Added Force Med Bill Resubmit Funds Supplemental Field
;
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Force Med Bill Resubmit,FL_FORCE_MB_RE,6,0,0,0,0,0,,EDI_FILING_STATUS)]
;
;*****************************************************************************************************************
; MITS 9934 JM 07/16/2007 Florida Medical Bills Revision D
; Added Pharmacist Funds Supplemental Field
;
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Pharmasict,FL_PHARMACIST,8,0,0,0,0,0,,)]

;*****************************************************************************************************************
; MITS 10099 JM 07/30/2007 Florida Medical Bills Revision D
; Funds Supplemental Fields added
;
;Modifier Code 1
;Modifier Code 2
;Modifier Code 3
;Modifier Code 4
;
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Modifier Code 1,FL_MOD_1,6,0,0,0,0,0,,MODIFIER_CODES)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Modifier Code 2,FL_MOD_2,6,0,0,0,0,0,,MODIFIER_CODES)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Modifier Code 3,FL_MOD_3,6,0,0,0,0,0,,MODIFIER_CODES)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Modifier Code 4,FL_MOD_4,6,0,0,0,0,0,,MODIFIER_CODES)]
;
;jtodd22 06/24/2010 revision "E", client data patch
;
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Facility License,FL_FAC_LIC_TEXT,0,13,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Facility NPI,FL_FAC_NPI_TEXT,0,10,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Operating Physician License,FL_OP_PHY_LIC_TEXT,0,13,0,0,0,0,,)]



;*****************************************************************************************************************
; JIRA 14633 sdalvi3  Florida Medical Bills Revision F
; Funds Supplemental Fields added
;
;NDC NUMBER SECONDARY
;Sdalvi3 Jira 30248
[SQL Server] [FORGIVE_ALTER] ALTER TABLE INVOICE_DETAIL DROP COLUMN PHY_PHARM_NDC_SECONDARY 
[Oracle]     [FORGIVE_ALTER] ALTER TABLE INVOICE_DETAIL DROP COLUMN PHY_PHARM_NDC_SECONDARY 


;*****************************************************************************************************************
; JIRA 14633 sdalvi3  Florida Medical Bills Revision F
; Funds Supplemental Fields
;
;
;Principal ICD Diagnosis Code
;ICD Principal Procedure Code
;ICD Type Indicator
;ICD Diagnosis Code A
;ICD Diagnosis Code B
;ICD Diagnosis Code C
;ICD Diagnosis Code D
;ICD Diagnosis Code E
;ICD Diagnosis Code F
;ICD Diagnosis Code G
;ICD Diagnosis Code H
;ICD Diagnosis Code I
;ICD Diagnosis Code J
;ICD Diagnosis Code K
;ICD Diagnosis Code L
;ICD Procedure Code A
;ICD Procedure Code B
;ICD Procedure Code C
;ICD Procedure Code D
;ICD Procedure Code E

; JIRA 27697 sdalvi3  Florida Medical Bills Revision F

[ASSIGN %%1=ADD_GLOSSARY(FL_ICD_TYPE_INDICATOR,ICD Type Indicator,10,1033)]
[ASSIGN %%1=ADD_CODE(0,1033,0 - ICD-10 (Record 09 and 90),FL_ICD_TYPE_INDICATOR,0)]
[ASSIGN %%1=ADD_CODE(9,1033,9 - ICD-9 (Record 09 and 90),FL_ICD_TYPE_INDICATOR,0)]
[ASSIGN %%1=ADD_CODE(B,1033,B - ICD-9 (Record 11),FL_ICD_TYPE_INDICATOR,0)]
[ASSIGN %%1=ADD_CODE(AB,1033,AB - ICD-10 (Record 11),FL_ICD_TYPE_INDICATOR,0)]
;Sdalvi3 Jira 29784
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Principal ICD Diagnosis Code,FL_Prin_ICD_DIAG,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;Sdalvi3 Jira 30925 Size Update
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Principal Procedure Code,FL_ICD_PRIN_PROC,0,8,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Principal Procedure Code,FL_ICD_PRIN_PROC,6,5,0,0,0,0,,PROCEDURE_CODE)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Type Indicator,FL_ICD_Type_indicator,6,0,0,0,0,0,,FL_ICD_TYPE_INDICATOR)] 
;Sdalvi3 Jira 29784 Start
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code A,FL_ICD_DIAG_A,6,0,0,0,0,0,,Diagnosis_Code_ICD10)] 
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code B,FL_ICD_DIAG_B,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code C,FL_ICD_DIAG_C,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code D,FL_ICD_DIAG_D,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code E,FL_ICD_DIAG_E,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code F,FL_ICD_DIAG_F,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code G,FL_ICD_DIAG_G,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code H,FL_ICD_DIAG_H,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code I,FL_ICD_DIAG_I,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code J,FL_ICD_DIAG_J,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code K,FL_ICD_DIAG_K,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Diagnosis Code L,FL_ICD_DIAG_L,6,0,0,0,0,0,,Diagnosis_Code_ICD10)]
;Sdalvi3 Jira 29784 End
;Sdalvi3 Jira 30925 Size Update
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Procedure Code A,FL_ICD_PROC_A,0,8,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Procedure Code B,FL_ICD_PROC_B,0,8,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Procedure Code C,FL_ICD_PROC_C,0,8,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Procedure Code D,FL_ICD_PROC_D,0,8,0,0,0,0,,)]
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL ICD Procedure Code E,FL_ICD_PROC_E,0,8,0,0,0,0,,)]
;Sdalvi3 Jira 30840 Resubmission code
[ASSIGN %%1=ADD_STATE_FIELD(FUNDS_SUPP,EDI FL Resubmission Code,RESUBMISSION_CODE,0,11,0,0,0,0,,)]







;*****************************************************************************************************************


