/****** Object:  Table [dbo].[EMP_SUPP]    Script Date: 12/12/2013 15:06:44 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMP_SUPP]') AND type in (N'U'))
DROP TABLE [dbo].[EMP_SUPP]

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_DIS_EMP_SUPP_GRID_INPUT]') AND type in (N'U'))
DROP TABLE [dbo].[T_DIS_EMP_SUPP_GRID_INPUT]

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_DIS_EMP_SUPP_GRID_WORD]') AND type in (N'U'))
DROP TABLE [dbo].[T_DIS_EMP_SUPP_GRID_WORD]

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_DIS_EMP_APPOINT_GRID]') AND type in (N'U'))
DROP TABLE [dbo].[T_DIS_EMP_APPOINT_GRID]

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON


CREATE TABLE [dbo].[T_DIS_EMP_SUPP_GRID_WORD](
	[DA_ROW_ID] [int] NULL,
	[JOBID] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
	[RECORD_ID] [int] NULL, 
	[ROW_NUMBER] [int] NULL,
	[ROW] [varchar](8000) NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[T_DIS_EMP_SUPP_GRID_INPUT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[RECORD_ID] [int] NULL, 
	[EMP_APPOINT_GRID] [varchar](8000) NULL,
PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[T_DIS_EMP_APPOINT_GRID](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,  
	[INPUT_ROW_ID] [int] NULL,
	[FIELD_ID] [int] NULL,
	[RECORD_ID] [int] NULL,
	[ROW_NUM] [int] NULL,
	[COL_NUM] [int] NULL,
	[CELL_VALUE] [varchar](150) NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[EMP_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EMPLOYEE_EID] [int] NULL,
	[REG_TEMP_CODE] [int] NULL,
	[ACTION_DATE] [varchar](8) NULL,
	[HIRE_STATE] [int] NULL,
	[JOB_FAMILY_CODE] [int] NULL,
	[UNION_CODE] [int] NULL,
	[ADDR3RD_TEXT] [varchar](50) NULL,
	[MED_COST_AMT] [float] NULL,
	[DENTAL_COST_AMT] [float] NULL,
	[LIFE_COST_AMT] [float] NULL,
	[SPOUSE_COST_AMT] [float] NULL,
	[DPNDNT_COST_AMT] [float] NULL,
	[VISION_COST_AMT] [float] NULL,
	[LEGAL_COST_AMT] [float] NULL,
	[RETIRE_DATE] [varchar](8) NULL,
	[EXT_SK_FULL_NUM] [float] NULL,
	[EXT_SK_HALF_NUM] [float] NULL,
	[SICK_BAL_NUM] [float] NULL,
	[VACA_BAL_NUM] [float] NULL,
	[PTO_BAL_NUM] [float] NULL,
	[EMP_STATUS__CODE] [int] NULL,
	[LTD_COST_AMT] [float] NULL,
	[MD_LEAVE_ST_DATE] [varchar] (8) NULL,
	[MD_LEAVE_EN_DATE] [varchar] (8) NULL,
	[FUND_CODE_TEXT] [varchar] (10) NULL
 CONSTRAINT [PK_EMP_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


SET ANSI_PADDING OFF


