-- ============================================================
--   Table:	DATA_INTEGRATOR_TEMPLATES
--   DATE:	09/17/2012
--   ipuri:  	Mits:29803 
--   mrishi2: 	JIRA 14239 Added new columns for Claim types
--   Template-RMA_16.2 and above MMSEA Medicare
-- =============================================================


delete from DATA_INTEGRATOR_TEMPLATES where MODULE_NAME='MMSEA'
INSERT INTO DATA_INTEGRATOR_TEMPLATES VALUES ((ISNULL((SELECT MAX(ROW_ID) FROM DATA_INTEGRATOR_TEMPLATES),0) + 1),'MMSEA','<MMSEA><RRE_ID></RRE_ID><TYPE_OF_FILE>Export</TYPE_OF_FILE><FILE_FORMAT></FILE_FORMAT><TEST_EXPORT>0</TEST_EXPORT><IMPORTFILE_NAME></IMPORTFILE_NAME><PRIMARY_CLAIMANT>0</PRIMARY_CLAIMANT><TPOCS_THRESHOLD>0</TPOCS_THRESHOLD><TIN_IMPORTFILE_NAME></TIN_IMPORTFILE_NAME><DIARY_NOTIFICATION_SEND>-1</DIARY_NOTIFICATION_SEND><DIARY_NOTIFICATION_CURR_ADJ>-1</DIARY_NOTIFICATION_CURR_ADJ><DIARY_SEND_OTH_USER_ID></DIARY_SEND_OTH_USER_ID><DIARY_SEND_OTH_GROUP_ID></DIARY_SEND_OTH_GROUP_ID><DIARY_SEND_OTH_USER_NAME></DIARY_SEND_OTH_USER_NAME><DIARY_SEND_OTH_GROUP_NAME></DIARY_SEND_OTH_GROUP_NAME><ClaimType></ClaimType></MMSEA>')
