
USE [DA_RMX_STAGING]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ADJUST_DATED_TEXT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[TEXT_TYPE_CODE] [int] NULL,
	[ADJ_DTTEXT_ROW_ID] [int] NULL,
	[ADJ_ROW_ID] [int] NULL,
	[DATE_ENTERED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENTERED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_ENTERED] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATED_TEXT] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATED_TEXT_HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_ADJUST_DATED_TEXT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[BOND_ABS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[BOND_ABS_ID] [int] NOT NULL,
	[BOND_NUM_TEXT] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOND_TYPE_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOND_LINE_CODE] [int] NULL,
	[EFF_DATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPIR_DATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOND_AMT_AMT] [float] NULL,
	[PREMIUM_AMT] [float] NULL,
	[BILL_NAME_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BILL_ADDR_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BILL_CITY_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BILL_ZIP_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BILL_ACCT_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRINCIPAL_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_TEXT] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BILL_STATE_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OBLIGEE_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOND_CLASS_CODE] [int] NULL,
	[OLD_BOND_NO_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQUESTER_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQ_ADDR_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQ_CITY_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQ_STATE_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQ_ZIP_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQ_PHONE_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORDERED_BY_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORDER_ADDR_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORDER_CITY_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORDER_STATE_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORDER_ZIP_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORDER_PHONE_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTH_BY_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTH_ADDR_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTH_CITY_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTH_STATE_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTH_ZIP_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTH_PHONE_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_EXEC_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PAID_DATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOND_STATUS_CODE] [int] NULL,
	[DATE_CANC_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOND_DETAIL_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_BOND_ABS] PRIMARY KEY CLUSTERED 
( 	[DA_ROW_ID] ASC,
	[JOBID] ASC
	
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[CERTIFICATE](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CERTIFICATE_ID] [int] NOT NULL,
	[JOB_NO_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JOB_DESC_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AGENCY_NAME_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AGENCY_PHON_TEXT] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSURED_NAM_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSURED_ADD_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSURED_CIT_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSURED_ST_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSURED_ZIP_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSURED_PH_TEXT] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GEN_LIAB_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INS_NAME_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_NUMBER_NUM] [float] NULL,
	[EXPIR_DATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BI_EA_AGG_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PD_EA_AGG_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BI_PD_COMB_NUM] [float] NULL,
	[PI_AGG_NUM] [float] NULL,
	[AUTO_LIAB_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BI_EA_PERS_NUM] [float] NULL,
	[BI_EA_ACC_NUM] [float] NULL,
	[PD_EA_OCC_NUM] [float] NULL,
	[BI_PD_COMB_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXCESS_LIAB_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BI_PD_AGG_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_COMP_NUM] [float] NULL,
	[WORK_COMP_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WC_EA_ACC_NUM] [float] NULL,
	[OPER_DESC_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ISSUE_DT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_CERTIFICATE] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[CODE_FIELD_MAP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[ROW_ID] [int] NOT NULL,
	[TABLE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIELD_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODE_TABLE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABLE_ID] [int] NOT NULL,
 CONSTRAINT [PK_ROW_ID] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[CODES](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[IND_STANDARD_CODE] [int] NULL,
	[LINE_OF_BUS_CODE] [int] NULL,
	[CODE_ID] [int] NULL,
	[TABLE_ID] [int] NULL,
	[SHORT_CODE] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RELATED_CODE_ID] [int] NULL,
	[DELETED_FLAG] [smallint] NULL,
	[TRIGGER_DATE_FIELD] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFF_START_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFF_END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORG_GROUP_EID] [int] NULL,
 CONSTRAINT [PK_CODES] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[CODES_TEXT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CODE_ID] [int] NULL,
	[LANGUAGE_CODE] [int] NULL,
	[SHORT_CODE] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODE_DESC] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_CODES_TEXT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[COMPL_MGT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[COMPL_MGT_ID] [int] NOT NULL,
	[COMP_NO_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DT_RECV_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMP_TYPE_CODE] [int] NULL,
	[COMP_SRC_CODE] [int] NULL,
	[ACT_REQ_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FILED_AGNST_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REF_TO_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_COMPL_MGT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[CONTRCT_MGT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CONTRCT_MGT_ID] [int] NOT NULL,
	[CONT_TYPE_CODE] [int] NULL,
	[CONTR_CAT_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUBJECTOR_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUBJECTEE_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DETAILS_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFF_DATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPIR_DATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RENEW_DATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INDEMNITY_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUBROGATION_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TERM_INFO_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONDITIONS_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTH_SIGN_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PAYMENTS_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WARRANTY_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_CONTRCT_MGT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[DIRECTORY](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[DIRECTORY_ID] [int] NOT NULL,
	[LAST_NAME_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIRST_NAME_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDRESS_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CITY_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZIP_CODE_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HOME_PHONE_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_PHONE_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FAX_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TITLE_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORGANIZ_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTACT_TYP_CODE] [int] NULL,
	[CONTACT_STA_CODE] [int] NULL,
	[RECALL_DT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOTES_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_DIRECTORY] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[DISABILITY_CLASS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CLASS_ROW_ID] [int] NULL,
	[PLAN_ID] [int] NULL,
	[CLASS_NAME] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLASS_DESC] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ELIG_BENE_PRD] [int] NULL,
	[BENE_PRD_TYPE] [int] NULL,
	[BENE_FROM_DT_TYPE] [int] NULL,
	[DIS_WAIT_PRD] [int] NULL,
	[DIS_CLNDR_WRK_CODE] [int] NULL,
	[DIS_PRD_TYPE] [int] NULL,
	[DIS_MAX_PRD] [int] NULL,
	[DIS_MAX_PRD_TYPE] [int] NULL,
	[FROM_DIS_PRD_TYPE] [int] NULL,
	[ALLOW_EXT] [int] NULL,
	[EXTEND_PRD] [int] NULL,
	[EXTEND_PRD_TYPE] [int] NULL,
	[MAX_TOT_DIS_PRD] [int] NULL,
	[MAX_TOT_PRD_TYPE] [int] NULL,
	[ACTUAL_WORK_WEEK] [smallint] NULL,
	[DAY7_WORK_WEEK] [smallint] NULL,
	[DAY5_WORK_WEEK] [smallint] NULL,
	[OTHER_WORK_WEEK] [smallint] NULL,
	[OTHER_DAYS] [int] NULL,
	[BENE_PRCTG_FLAG] [smallint] NULL,
	[BENE_PER_AMT] [float] NULL,
	[BENE_FLAT_AMT_FLAG] [smallint] NULL,
	[BENE_FLAT_AMT] [float] NULL,
	[BENE_TD_FLAG] [smallint] NULL,
	[BENE_BASED_CODE] [int] NULL,
	[WITHHOLD_FED_ITAX] [smallint] NULL,
	[WITHHOLD_FICA] [smallint] NULL,
	[WEEKLY_BENE_CAP] [float] NULL,
	[MAX_BEN_PER_CLAIM] [float] NULL,
	[MAX_BEN_PER_CAL_YR] [float] NULL,
	[WAGE_FOR_DIS_PRD] [float] NULL,
	[WAGE_FOR_CAL_YR] [float] NULL,
	[TAXABLE_PERCENT] [float] NULL,
	[WITHHOLD_MEDICARE] [smallint] NULL,
	[WITHHOLD_STATE] [smallint] NULL,
	[USE_VOUCHERS] [smallint] NULL,
	[DAY30_WORK_MONTH] [smallint] NULL,
	[ACTUAL_MONTH] [smallint] NULL,
	[UPPER_AGE_LIMIT] [int] NULL,
	[LOWER_AGE_LIMIT] [int] NULL,
	[SUPP_PERCENT] [float] NULL,
	[SUPP_FLAT_AMT] [float] NULL,
	[SUPP_BANK_ACC_ID] [int] NULL,
	[SUPP_SUB_ACC_ID] [int] NULL,
	[SUPP_TR_TYPE_CODE] [int] NULL,
	[SUPP_SEP_PAY_FLAG] [smallint] NULL,
	[PENSION_AMT] [float] NULL,
	[SS_AMT] [float] NULL,
	[OTHER_AMT] [float] NULL,
	[PRORATE_OFF_FLAG] [smallint] NULL,
	[FULLPAY_ONLY_FLAG] [smallint] NULL,
	[OTH_OFF1] [float] NULL,
	[OTH_OFF2] [float] NULL,
	[OTH_OFF3] [float] NULL,
	[POST_TAX_DED1] [float] NULL,
	[POST_TAX_DED2] [float] NULL,
 CONSTRAINT [PK_DISABILITY_CLASS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[DISABILITY_PLAN](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PLAN_ID] [int] NULL,
	[PLAN_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLAN_NAME] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLAN_DESCRIPTION] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLAN_STATUS_CODE] [int] NULL,
	[PREMIUM] [float] NULL,
	[BANK_ACC_ID] [int] NULL,
	[EFFECTIVE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPIRATION_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ISSUE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REVIEW_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RENEWAL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CANCEL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PREF_DAY_CODE] [int] NULL,
	[PREF_PAY_SCH_CODE] [int] NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[START_PAY_PERIOD] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRINT_BEFORE_END] [smallint] NULL,
	[SUB_ACC_ROW_ID] [int] NULL,
	[PREF_DAY_OF_M_CODE] [int] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_DISABILITY_PLAN] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[EMP_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EMPLOYEE_EID] [int] NULL,
	[COPHYSEXAM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_EMP_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[EMP_X_DEPENDENT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EMP_DEP_ROW_ID] [int] NULL,
	[EMPLOYEE_EID] [int] NOT NULL,
	[DEPENDENT_EID] [int] NOT NULL,
	[HEALTH_PLAN_FLAG] [smallint] NULL,
	[RELATION_CODE] [int] NULL,
	[DEPENDENT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_EMP_X_DEPENDENT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[EMP_X_VIOLATION](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[VIOLATION_ID] [int] NOT NULL,
	[EMPLOYEE_EID] [int] NULL,
	[VIOLATION_CODE] [int] NULL,
	[VIOLATION_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_EMP_X_VIOLATION] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]



CREATE TABLE [dbo].[EMPLOYEE](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[COUNTY_OF_RESIDNC] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVLIC_STATE] [int] NULL,
	[INSURABLE_FLAG] [smallint] NULL,
	[LAST_VERIFIED_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUM_OF_VIOLATIONS] [int] NULL,
	[TERM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_PERMIT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_PERMIT_NUMBER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMPLOYEE_EID] [int] NULL,
	[ACTIVE_FLAG] [smallint] NULL,
	[EMPLOYEE_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MARITAL_STAT_CODE] [int] NULL,
	[DATE_HIRED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POSITION_CODE] [int] NULL,
	[DEPT_ASSIGNED_EID] [int] NULL,
	[SUPERVISOR_EID] [int] NULL,
	[EXEMPT_STATUS_FLAG] [smallint] NULL,
	[NO_OF_EXEMPTIONS] [int] NULL,
	[FULL_TIME_FLAG] [smallint] NULL,
	[HOURLY_RATE] [float] NULL,
	[WEEKLY_HOURS] [float] NULL,
	[WEEKLY_RATE] [float] NULL,
	[WORK_SUN_FLAG] [smallint] NULL,
	[WORK_MON_FLAG] [smallint] NULL,
	[WORK_TUE_FLAG] [smallint] NULL,
	[WORK_WED_FLAG] [smallint] NULL,
	[WORK_THU_FLAG] [smallint] NULL,
	[WORK_FRI_FLAG] [smallint] NULL,
	[WORK_SAT_FLAG] [smallint] NULL,
	[PAY_TYPE_CODE] [int] NULL,
	[PAY_AMOUNT] [float] NULL,
	[DRIVERS_LIC_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVERSLICTYPECODE] [int] NULL,
	[DATE_DRIVERSLICEXP] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVLIC_RSTRCTCODE] [int] NULL,
	[NCCI_CLASS_CODE] [int] NULL,
	[DATE_OF_DEATH] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SEC_DEPT_EID] [int] NULL,
	[JOB_CLASS_CODE] [int] NULL,
	[MONTHLY_RATE] [float] NULL,
	[ELIG_DIS_BEN_FLAG] [smallint] NULL,
	[DIS_OPTION_CODE] [int] NULL,
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[ENTITY](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[BUSINESS_TYPE_CODE] [int] NULL,
	[COUNTY] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NATURE_OF_BUSINESS] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIC_CODE] [int] NULL,
	[SIC_CODE_DESC] [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WC_FILING_NUMBER] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENTITY_ID] [int] NULL,
	[ENTITY_TABLE_ID] [int] NULL,
	[LAST_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAST_NAME_SOUNDEX] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIRST_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ALSO_KNOWN_AS] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABBREVIATION] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COST_CENTER_CODE] [int] NULL,
	[ADDR1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDR2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CITY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COUNTRY_CODE] [int] NULL,
	[STATE_ID] [int] NULL,
	[ZIP_CODE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARENT_EID] [int] NULL,
	[TAX_ID] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTACT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMAIL_TYPE_CODE] [int] NULL,
	[EMAIL_ADDRESS] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SEX_CODE] [int] NULL,
	[BIRTH_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PHONE1] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PHONE2] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FAX_NUMBER] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DELETED_FLAG] [smallint] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[TRIGGER_DATE_FIELD] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFF_START_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFF_END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARENT_1099_EID] [int] NULL,
	[REPORT_1099_FLAG] [smallint] NULL,
	[MIDDLE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TITLE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAICS_CODE] [int] NULL,
	[RM_USER_ID] [int] NULL,
	[FREEZE_PAYMENTS] [int] NULL,
	[ORGANIZATION_TYPE] [int] NULL,
	[NPI_NUMBER] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MMSEA_TIN_EDT_FLAG] [smallint] NULL,
 CONSTRAINT [PK_ENTITY] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[ENTITY_EXPOSURE](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EXPOSURE_ROW_ID] [int] NOT NULL,
	[ENTITY_ID] [int] NULL,
	[START_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NO_OF_EMPLOYEES] [int] NULL,
	[NO_OF_WORK_HOURS] [int] NULL,
	[PAYROLL_AMOUNT] [float] NULL,
	[ASSET_VALUE] [float] NULL,
	[SQUARE_FOOTAGE] [int] NULL,
	[VEHICLE_COUNT] [int] NULL,
	[TOTAL_REVENUE] [float] NULL,
	[OTHER_BASE] [float] NULL,
	[RISK_MGMT_OVERHEAD] [float] NULL,
	[USER_GENERATD_FLAG] [smallint] NULL,
 CONSTRAINT [PK_ENTITY_EXPOSURE] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[ENT_EXPOSURE_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EXPOSURE_ROW_ID] [int] NOT NULL,
 CONSTRAINT [PK_ENT_EXPOSURE_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[ENTITY_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[ENTITY_ID] [int] NULL,
	[INDEX_BUREAU_NUMB] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STE_AGNT_BRU_IDNT] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_ENTITY_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[FUNDS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[AUTO_CHECK_DETAIL] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROLLUP_ID] [int] NULL,
	[VOID_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDR1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDR2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTO_CHECK_FLAG] [smallint] NULL,
	[CITY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLAIMANT_EID] [int] NULL,
	[COUNTRY_CODE] [int] NULL,
	[FIRST_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAST_NAME] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRECHECK_FLAG] [smallint] NULL,
	[STATE_ID] [int] NULL,
	[UNIT_ID] [int] NULL,
	[ZIP_CODE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRANS_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[CLAIM_NUMBER] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CTL_NUMBER] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VOID_FLAG] [smallint] NULL,
	[DATE_OF_CHECK] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHECK_MEMO] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRANS_NUMBER] [bigint] NULL,
	[TRANS_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PAYEE_EID] [int] NULL,
	[PAYEE_TYPE_CODE] [int] NULL,
	[ACCOUNT_ID] [int] NULL,
	[AMOUNT] [float] NULL,
	[STATUS_CODE] [int] NULL,
	[FILED_1099_FLAG] [smallint] NULL,
	[CLEARED_FLAG] [smallint] NULL,
	[PAYMENT_FLAG] [smallint] NULL,
	[COLLECTION_FLAG] [smallint] NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOTES] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CRC] [int] NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BATCH_NUMBER] [int] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[ENCLOSURE_FLAG] [smallint] NULL,
	[APPROVE_USER] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_APPROVAL] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUB_ACCOUNT_ID] [int] NULL,
	[SETTLEMENT_FLAG] [smallint] NULL,
	[APPROVER_ID] [int] NULL,
	[VOUCHER_FLAG] [smallint] NULL,
	[WEEKS_PAID_CODE] [int] NULL,
	[NUM_OF_PAID_DAYS] [int] NULL,
	[TAX_PAYMENT_FLAG] [smallint] NULL,
	[RESUBMIT_EDI] [smallint] NULL,
	[SUPP_PAYMENT_FLAG] [smallint] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REISSUE_FLAG] [smallint] NULL,
	[REISSUE_BY] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REISSUE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REISSUE_PARENT_ID] [int] NULL,
	[NOTES_HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REISSUE_REASON_CODE] [int] NULL DEFAULT ((0)),
	[MIDDLE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_FUNDS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[FUNDS_DEPOSIT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[DEPOSIT_ID] [int] NULL,
	[CTL_NUMBER] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BANK_ACC_ID] [int] NULL,
	[SUB_ACC_ID] [int] NULL,
	[TRANS_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMOUNT] [float] NULL,
	[CLEARED_FLAG] [smallint] NULL,
	[VOID_FLAG] [smallint] NULL,
	[ADDED_BY_USER] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATE_BY_USER] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESCRIPTION] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VOIDCLEAR_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEPOSIT_TYPE] [smallint] NULL,
	[ADJUST_CODE] [int] NULL,
	[UPDATED_BY_USER] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
 CONSTRAINT [PK_FUNDS_DEPOSIT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[FUNDS_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[TRANS_ID] [int] NULL,
	[INT_CLAIM_TEXT] [varchar](21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_FUNDS_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[FUNDS_TRANS_SPLIT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[SUM_AMOUNT] [float] NULL,
	[SPLIT_ROW_ID] [int] NULL,
	[TRANS_ID] [int] NULL,
	[TRANS_TYPE_CODE] [int] NULL,
	[RESERVE_TYPE_CODE] [int] NULL,
	[AMOUNT] [float] NULL,
	[GL_ACCOUNT_CODE] [int] NULL,
	[FROM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TO_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVOICED_BY] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVOICE_AMOUNT] [float] NULL,
	[INVOICE_NUMBER] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PO_NUMBER] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CRC] [int] NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVOICE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BILL_RCVD_BY_CARRIER_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUPP_PAYMENT_FLAG] [smallint] NULL,
 CONSTRAINT [PK_FUNDS_TRANS_SPLIT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[FUNDS_TRANS_SPLIT_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[SPLIT_ROW_ID] [int] NULL,
 CONSTRAINT [PK_FUNDS_TRANS_SPLIT_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[HAZ_MAT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[HAZ_MAT_ID] [int] NOT NULL,
	[PROD_NAME_TEXT] [varchar](75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTH_NAMES_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOTES_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_HAZ_MAT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[MED_STAFF](	
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[STAFF_EID] [int] NOT NULL,
	[MED_STAFF_NUMBER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIMARY_POLICY_ID] [int] NOT NULL,
	[HOME_ADDR1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HOME_ADDR2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HOME_CITY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HOME_STATE_ID] [int] NOT NULL,
	[HOME_ZIP_CODE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MARITAL_STAT_CODE] [int] NOT NULL,
	[BEEPER_NUMBER] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CELLULAR_NUMBER] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMERGENCY_CONTACT] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STAFF_STATUS_CODE] [int] NOT NULL,
	[STAFF_POS_CODE] [int] NOT NULL,
	[STAFF_CAT_CODE] [int] NOT NULL,
	[DEPT_ASSIGNED_EID] [int] NOT NULL,
	[HIRE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIC_NUM] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIC_STATE] [int] NOT NULL,
	[LIC_ISSUE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIC_EXPIRY_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIC_DEA_NUM] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIC_DEA_EXP_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_MED_STAFF] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[MED_STAFF_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[STAFF_EID] [int] NOT NULL,
 CONSTRAINT [PK_MED_STAFF_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[ORG_HIERARCHY](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[DEPARTMENT_EID] [int] NOT NULL,
	[FACILITY_EID] [int] NULL,
	[LOCATION_EID] [int] NULL,
	[DIVISION_EID] [int] NULL,
	[REGION_EID] [int] NULL,
	[OPERATION_EID] [int] NULL,
	[COMPANY_EID] [int] NULL,
	[CLIENT_EID] [int] NULL,
 CONSTRAINT [PK_ORG_HIERARCHY] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PATIENT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PATIENT_ID] [int] NOT NULL,
	[PATIENT_EID] [int] NOT NULL,
	[PATIENT_ACCT_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEDICAL_RCD_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_OF_ADMISSION] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_OF_ADMISSION] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_OF_DISCHARGE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_OF_DISCHARGE] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADMISSION_REASON] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADM_TYPE_CODE] [int] NOT NULL,
	[ADM_SOURCE_CODE] [int] NOT NULL,
	[ACUITY_LEVEL_CODE] [int] NOT NULL,
	[CARDIAC_ARREST] [smallint] NULL,
	[PATIENT_STAT_CODE] [int] NOT NULL,
	[PATIENT_COND_CODE] [int] NOT NULL,
	[DISCHARGE_DSP_CODE] [int] NOT NULL,
	[EXP_LENGTH_OF_STAY] [int] NOT NULL,
	[EXPECTED_COST] [float] NULL,
	[INS_PLAN_GROUP_NO] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QI_SIGNIF_CODE] [int] NOT NULL,
	[EPISODE_OF_CARE_ID] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATIENT_TYPE_CODE] [int] NOT NULL,
	[HEIGHT] [float] NULL,
	[WEIGHT] [float] NULL,
	[MARITAL_STAT_CODE] [int] NOT NULL,
	[RACE_ENTH_CODE] [int] NOT NULL,
	[DATE_OF_DEATH] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIMARY_PAY_CODE] [int] NOT NULL,
	[SECOND_PAY_CODE] [int] NOT NULL,
	[EMERGENCY_CONTACT] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMERGENCY_CONT_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATIENT_ROOM_NO] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FACILITY_UNIT_CODE] [int] NOT NULL,
	[FACILITY_DEPT_EID] [int] NOT NULL,
	[HCO_ID_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCO_SITE_ID_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRI_PHYSICIAN_EID] [int] NOT NULL,
	[ADM_PHYSICIAN_EID] [int] NOT NULL,
	[NB_APGAR_SCORE] [int] NULL,
	[NB_BIRTH_WEIGHT] [float] NULL,
	[NB_LEN_OF_GEST] [int] NULL,
	[NB_NICU_STAY] [int] NULL,
	[NB_NICU_ADM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NB_NICU_DISCH_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NB_CEPHALIC_MOLD] [int] NULL,
	[NB_EPS_OF_CARE_ID] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NBM_PARITY] [int] NULL,
	[NBM_PRIOR_C_SECT] [int] NULL,
	[NBM_MED_IND_LABOR] [int] NULL,
	[NBM_LIVE_BIRTHS] [int] NULL,
	[NBM_STILL_BIRTHS] [int] NULL,
	[NBM_GRAVIDA] [int] NULL,
	[NBM_EPS_OF_CARE_ID] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISABILITY_CODE] [int] NULL,
	[ILLNESS_CODE] [int] NULL,
	[LOST_CONSC_FLAG] [int] NULL,
	[WHY_AT_FACILITY] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PATIENT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[PATIENT_ACT_TAKEN](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PATIENT_ID] [int] NOT NULL,
	[ACTION_CODE] [int] NOT NULL,
 CONSTRAINT [PK_PATIENT_ACT_TAKEN] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PATIENT_ATTN_PHYS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PATIENT_ID] [int] NOT NULL,
	[PHYSICIAN_EID] [int] NOT NULL,
 CONSTRAINT [PK_PATIENT_ATTN_PHYS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PATIENT_DIAGNOSIS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PATIENT_ID] [int] NOT NULL,
	[DIAGNOSIS_CODE] [int] NOT NULL,
 CONSTRAINT [PK_PATIENT_DIAGNOSIS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PATIENT_DRG_CODES](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PATIENT_ID] [int] NOT NULL,
	[DRG_CODE] [int] NOT NULL,
 CONSTRAINT [PK_PATIENT_DRG_CODES] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[PATIENT_PROC_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PROC_ROW_ID] [int] NOT NULL,
 CONSTRAINT [PK_PATIENT_PROC_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[PATIENT_PROCEDURE](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PROC_ROW_ID] [int] NOT NULL,
	[PATIENT_ID] [int] NOT NULL,
	[PROCEDURE_CODE] [int] NOT NULL,
	[PROC_TYPE_CODE] [int] NOT NULL,
	[DATE_OF_PROCEDURE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SURGEON_EID] [int] NOT NULL,
	[ANESTH_ADMIN_FLAG] [smallint] NULL,
	[ANESTH_TYPE_CODE] [int] NOT NULL,
	[ANESTH_EID] [int] NOT NULL,
	[ASA_PS_CLASS_CODE] [int] NOT NULL,
	[COMPLICATION_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIOR_TO_ANES_FLAG] [smallint] NULL,
	[ICC_LEVEL_CODE] [int] NOT NULL,
	[LEN_OF_TIME] [float] NULL,
	[COMPLICATIONS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PATIENT_PROCEDURE] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[PATIENT_SUPP](	
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INVALID_ROW] [int] NULL,
	[INPUT_ROW_ID] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PATIENT_ID] [int] NOT NULL,
 CONSTRAINT [PK_PATIENT_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[PERSON_INVOLVED](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[COUNTY_OF_RESIDNC] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVLIC_STATE] [int] NULL,
	[EST_LEN_DISABILITY] [int] NULL,
	[HIRED_IN_STE_FLAG] [smallint] NULL,
	[INSURABLE_FLAG] [smallint] NULL,
	[LAST_VERIFIED_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUM_OF_VIOLATIONS] [int] NULL,
	[OSHA_ACC_DESC] [varchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OSHA_REC_FLAG] [int] NULL,
	[REGULAR_JOB_FLAG] [smallint] NULL,
	[TERM_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_PERMIT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_PERMIT_NUMBER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORKDAY_START_TIME] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PI_ROW_ID] [int] NULL,
	[EVENT_ID] [int] NULL,
	[PI_EID] [int] NULL,
	[PI_TYPE_CODE] [int] NULL,
	[INJURY_ILLNESS_FLG] [int] NULL,
	[DATE_OF_DEATH] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REHAB_TEXT] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESC_BY_WITNESS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATIENT_ACCT_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEDICAL_RCD_NO] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INS_PLAN_GROUP_NO] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_OF_ADMISSION] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_OF_DISCHARGE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADM_TYPE_CODE] [int] NULL,
	[ADM_SOURCE_CODE] [int] NULL,
	[ADMISSION_REASON] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACUITY_LEVEL_CODE] [int] NULL,
	[PATIENT_STAT_CODE] [int] NULL,
	[PATIENT_COND_CODE] [int] NULL,
	[DISCHARGE_DSP_CODE] [int] NULL,
	[EXP_LENGTH_OF_STAY] [int] NULL,
	[EXPECTED_COST] [float] NULL,
	[QI_SIGNIF_CODE] [int] NULL,
	[EPISODE_OF_CARE_ID] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATIENT_TYPE_CODE] [int] NULL,
	[MARITAL_STAT_CODE] [int] NULL,
	[RACE_ENTH_CODE] [int] NULL,
	[WEIGHT] [int] NULL,
	[PRIMARY_PAY_CODE] [int] NULL,
	[EMERGENCY_CONTACT] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMERGENCY_CONT_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PATIENT_ROOM_NO] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FACILITY_UNIT_CODE] [int] NULL,
	[FACILITY_DEPT_EID] [int] NULL,
	[HCO_ID_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HCO_SITE_ID_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WHY_AT_FACILITY] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLAIM_AMOUNT] [float] NULL,
	[LOST_WORK_FLAG] [smallint] NULL,
	[LEN_OF_SVC_DAYS] [int] NULL,
	[POSITION_CODE] [int] NULL,
	[DEPT_ASSIGNED_EID] [int] NULL,
	[SUPERVISOR_EID] [int] NULL,
	[EXEMPT_STATUS_FLAG] [smallint] NULL,
	[NO_OF_EXEMPTIONS] [int] NULL,
	[FULL_TIME_FLAG] [smallint] NULL,
	[HOURLY_RATE] [float] NULL,
	[WEEKLY_HOURS] [float] NULL,
	[WEEKLY_RATE] [float] NULL,
	[WORK_SUN_FLAG] [smallint] NULL,
	[WORK_MON_FLAG] [smallint] NULL,
	[WORK_TUE_FLAG] [smallint] NULL,
	[WORK_WED_FLAG] [smallint] NULL,
	[WORK_THU_FLAG] [smallint] NULL,
	[WORK_FRI_FLAG] [smallint] NULL,
	[WORK_SAT_FLAG] [smallint] NULL,
	[DRIVERS_LIC_NO] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVERSLICTYPECODE] [int] NULL,
	[DATE_DRIVERSLICEXP] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRIVLIC_RSTRCTCODE] [int] NULL,
	[NCCI_CLASS_CODE] [int] NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INJURY_CAT_CODE] [int] NULL,
	[PAY_AMOUNT] [float] NULL,
	[ACTIVE_FLAG] [smallint] NULL,
	[EMPLOYEE_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE_HIRED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISABILITY_CODE] [int] NULL,
	[ILLNESS_CODE] [int] NULL,
	[PAY_TYPE_CODE] [int] NULL,
	[LOST_CONSC_FLAG] [smallint] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[PATIENT_ID] [int] NULL,
	[EST_RTW_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OSHA_ESTAB_EID] [int] NULL,
	[MAJOR_HAND_CODE] [int] NULL,
	[HRANGE_START_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HRANGE_END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JOB_CLASS_CODE] [int] NULL,
	[OTHER_TREATMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHER_MEDCOND] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STD_DISABIL_TYPE] [int] NULL,
	[CUSTOM_FED_TAX_PER] [float] NULL,
	[CUSTOM_SS_TAX_PER] [float] NULL,
	[CUSTOM_MED_TAX_PER] [float] NULL,
	[CUSTOM_ST_TAX_PER] [float] NULL,
	[MONTHLY_RATE] [float] NULL,
	[ELIG_DIS_BEN_FLAG] [smallint] NULL,
	[DIS_OPTION_CODE] [int] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PERSON_INVOLVED] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[PHYS_CERTS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CERT_ID] [int] NOT NULL,
	[PHYS_EID] [int] NOT NULL,
	[NAME_CODE] [int] NOT NULL,
	[STATUS_CODE] [int] NOT NULL,
	[BOARD_CODE] [int] NOT NULL,
	[INT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PHYS_CERTS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PHYS_EDUCATION](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[EDUC_ID] [int] NOT NULL,
	[PHYS_EID] [int] NOT NULL,
	[EDUC_TYPE_CODE] [int] NOT NULL,
	[INSTITUTION_EID] [int] NOT NULL,
	[DEGREE_TYPE] [int] NOT NULL,
	[DEGREE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PHYS_EDUCATION] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[PHYS_PREV_HOSP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PREV_HOSP_ID] [int] NOT NULL,
	[PHYS_EID] [int] NOT NULL,
	[STATUS_CODE] [int] NOT NULL,
	[HOSPITAL_EID] [int] NOT NULL,
	[PRIV_CODE] [int] NOT NULL,
	[INT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PHYS_PREV_HOSP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PHYS_PRIVS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PRIV_ID] [int] NOT NULL,
	[PHYS_EID] [int] NOT NULL,
	[CATEGORY_CODE] [int] NOT NULL,
	[TYPE_CODE] [int] NOT NULL,
	[STATUS_CODE] [int] NOT NULL,
	[INT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PHYS_PRIVS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PHYS_SUB_SPECIALTY](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PHYS_EID] [int] NOT NULL,
	[SPECIALTY_CODE] [int] NOT NULL,
 CONSTRAINT [PK_PHYS_SUB_SPECIALTY] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PHYS_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PHYS_EID] [int] NOT NULL,
 CONSTRAINT [PK_PHYS_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PHYSICIAN](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PHYS_EID] [int] NOT NULL,
	[PHYSICIAN_NUMBER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[MED_STAFF_NUMBER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEDICARE_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIMARY_SPECIALTY] [int] NOT NULL,
	[PRIMARY_POLICY_ID] [int] NOT NULL,
	[HOME_ADDR1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HOME_ADDR2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HOME_CITY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HOME_STATE_ID] [int] NOT NULL,
	[HOME_ZIP_CODE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MARITAL_STAT_CODE] [int] NOT NULL,
	[BEEPER_NUMBER] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CELLULAR_NUMBER] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAILING_ADDR1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAILING_ADDR2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAILING_CITY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAILING_STATE_ID] [int] NOT NULL,
	[MAILING_ZIP_CODE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMERGENCY_CONTACT] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STAFF_STATUS_CODE] [int] NOT NULL,
	[STAFF_TYPE_CODE] [int] NOT NULL,
	[STAFF_CAT_CODE] [int] NOT NULL,
	[INTERNAL_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEPT_ASSIGNED_EID] [int] NOT NULL,
	[APPOINT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REAPPOINT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIC_STATE] [int] NOT NULL,
	[LIC_NUM] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIC_ISSUE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIC_EXPIRY_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIC_DEA_NUM] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIC_DEA_EXP_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEMBERSHIP] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONT_EDUCATION] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEACHING_EXP] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PHYSICIAN] PRIMARY KEY CLUSTERED 
(	[DA_ROW_ID] ASC,
	[JOBID] ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[POLICY](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POLICY_ID] [int] NULL,
	[POLICY_NAME] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POLICY_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POLICY_STATUS_CODE] [int] NULL,
	[INSURER_EID] [int] NULL,
	[ISSUE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REVIEW_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RENEWAL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFFECTIVE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPIRATION_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CANCEL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PREMIUM] [float] NULL,
	[TRIGGER_CLAIM_FLAG] [smallint] NULL,
	[PRIMARY_POLICY_FLG] [smallint] NULL,
	[COMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BROKER_EID] [int] NULL,
	[BANK_ACC_ID] [int] NULL,
	[SUB_ACC_ROW_ID] [int] NULL,
	[HTMLCOMMENTS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_POLICY] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[POLICY_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[POLICY_ID] [int] NULL,
 CONSTRAINT [PK_POLICY_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[POLICY_X_CVG_TYPE](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[CLAIM_LIMIT] [float] NULL,
	[NOTIFICATION_UID] [int] NULL,
	[POLCVG_ROW_ID] [int] NOT NULL,
	[POLICY_ID] [int] NULL,
	[COVERAGE_TYPE_CODE] [int] NULL,
	[POLICY_LIMIT] [float] NULL,
	[OCCURRENCE_LIMIT] [float] NULL,
	[TOTAL_PAYMENTS] [float] NULL,
	[REMARKS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXCEPTIONS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CANCEL_NOTICE_DAYS] [int] NULL,
	[SELF_INSURE_DEDUCT] [float] NULL,
	[NEXT_POLICY_ID] [int] NULL,
	[BROKER_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SECTION_NUMBER_CODE] [int] NULL,
 CONSTRAINT [PK_POLICY_X_CVG_TYPE] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[POLICY_X_INSURED](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[POLICY_ID] [int] NOT NULL,
	[INSURED_EID] [int] NOT NULL,
 CONSTRAINT [PK_POLICY_X_INSURED] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[POLICY_X_INSURER](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[IN_ROW_ID] [int] NOT NULL,
	[POLICY_ID] [int] NULL,
	[INSURER_CODE] [int] NULL,
	[RES_PERCENTAGE] [float] NULL,
	[PRIMARY_INSURER] [smallint] NULL,
	[PREMIUM_AMOUNT] [float] NULL,
	[PART_OF_TOTAL_LAYER] [float] NULL,
	[PORTION_OF_PART_OF_LAYER] [float] NULL,
	[INSTAL_PAYMENT_AMT] [float] NULL,
	[INSTAL_SCHEDULE_CODE] [int] NULL,
	[SPECIAL_CIRCUM_MEMO] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAYER_NUM_CODE] [int] NULL,
	[OCCURENCE_LIMIT] [float] NULL,
	[COVERAGE_DESC] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMMENT_MEMO] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_POLICY_X_INSURER] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[PROJ_TRACK](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PROJ_TRACK_ID] [int] NOT NULL,
	[ACT_TYPE_CODE] [int] NULL,
	[ACTIV_DESC_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ASSIGN_BY_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ASSIGN_TO_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIORITY_CODE] [int] NULL,
	[EST_HOURS_NUM] [float] NULL,
	[ACT_HOURS_NUM] [float] NULL,
	[DUE_DATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REVIEW_DATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMPLETE_DT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATUS_CODE] [int] NULL,
	[MAT_USED_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAT_COST_AMT] [float] NULL,
	[NOTES_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PROJ_TRACK] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[PROP_MGT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[PROP_MGT_ID] [int] NOT NULL,
	[PROP_ID_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOCATION_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OWNERSHIP_CODE] [int] NULL,
	[PROP_TYPE_CODE] [int] NULL,
	[PROP_CAT_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REPORTED_BY_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DT_UPDATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REV_DATE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DETAIL_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORIG_VALUE_AMT] [float] NULL,
	[CURR_VALUE_AMT] [float] NULL,
	[REPLACE_VAL_AMT] [float] NULL,
	[CONT_ORG_VL_AMT] [float] NULL,
	[CONT_REP_VL_AMT] [float] NULL,
	[CONT_CUR_VL_AMT] [float] NULL,
	[INSTALL_DT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTACT_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTACT_ADD_TEXT] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONT_CITY_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONT_STATE_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONT_ZIP_TEXT] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONT_PHONE_TEXT] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COVERAGE_CODE] [int] NULL,
	[DAMAGES_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IMPROVEMENT_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOTES_TXCD] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_PROP_MGT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[RESERVE_CURRENT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[BALANCE_AMOUNT] [float] NULL,
	[RC_ROW_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[UNIT_ID] [int] NULL,
	[CLAIMANT_EID] [int] NULL,
	[RESERVE_TYPE_CODE] [int] NULL,
	[RESERVE_AMOUNT] [float] NULL,
	[INCURRED_AMOUNT] [float] NULL,
	[COLLECTION_TOTAL] [float] NULL,
	[PAID_TOTAL] [float] NULL,
	[DATE_ENTERED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENTERED_BY_USER] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REASON] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CRC] [int] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[RES_STATUS_CODE] [int] NULL,
	[ALLOCATED_AMOUNT] [float] NULL,
 CONSTRAINT [PK_RESERVE_CURRENT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[RESERVE_HISTORY](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[BALANCE_AMOUNT] [float] NULL,
	[CHANGE_AMOUNT] [float] NULL,
	[RSV_ROW_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[CLAIMANT_EID] [int] NULL,
	[UNIT_ID] [int] NULL,
	[RESERVE_TYPE_CODE] [int] NULL,
	[RESERVE_AMOUNT] [float] NULL,
	[COLLECTION_TOTAL] [float] NULL,
	[INCURRED_AMOUNT] [float] NULL,
	[PAID_TOTAL] [float] NULL,
	[DATE_ENTERED] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ENTERED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REASON] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_ADDED] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDED_BY_USER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CRC] [int] NULL,
	[SEC_DEPT_EID] [int] NULL,
	[RES_STATUS_CODE] [int] NULL,
	[CLOSED_FLAG] [int] NULL,
	[AUTO_ADJ_FLAG] [int] NULL,
 CONSTRAINT [PK_RESERVE_HISTORY] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[STAFF_CERTS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[STAFF_CERT_ID] [int] NOT NULL,
	[STAFF_EID] [int] NOT NULL,
	[NAME_CODE] [int] NOT NULL,
	[INT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_STAFF_CERTS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[STAFF_PRIVS](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,	[STAFF_PRIV_ID] [int] NOT NULL,
	[STAFF_EID] [int] NOT NULL,
	[CATEGORY_CODE] [int] NOT NULL,
	[TYPE_CODE] [int] NOT NULL,
	[STATUS_CODE] [int] NOT NULL,
	[INT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[END_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_STAFF_PRIVS] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[UNIT_X_CLAIM](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[UNIT_ROW_ID] [int] NOT NULL,
	[UNIT_ID] [int] NULL,
	[CLAIM_ID] [int] NULL,
	[VEHICLE_MAKE] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_YEAR] [int] NULL,
	[HOME_DEPT_EID] [int] NULL,
	[LICENSE_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_ROW_ID] [int] NULL,
	[DAMAGE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNIT_TYPE_CODE] [int] NULL,
	[VIN] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_UNIT_X_CLAIM] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[UNIT_X_CLAIM_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,	[STAFF_PRIV_ID] [int] NOT NULL,
	[UNIT_ROW_ID] [int] NOT NULL,
 CONSTRAINT [PK_UNIT_X_CLAIM_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]



CREATE TABLE [dbo].[VEHICLE](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[DISPOSAL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LEASE_AMOUNT] [float] NULL,
	[LEASE_EXPIRE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LEASE_FLAG] [smallint] NULL,
	[LEASE_NUMBER] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LEASE_TERM] [int] NULL,
	[LEASING_CO_EID] [int] NULL,
	[LICENSE_RNWL_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_MODEL] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNIT_ID] [int] NULL,
	[VEHICLE_MAKE] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_YEAR] [int] NULL,
	[UNIT_TYPE_CODE] [int] NULL,
	[HOME_DEPT_EID] [int] NULL,
	[LICENSE_NUMBER] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE_ROW_ID] [int] NULL,
	[GROSS_WEIGHT] [int] NULL,
	[VIN] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORIGINAL_COST] [float] NULL,
	[PURCHASE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEDUCTIBLE] [float] NULL,
	[LAST_SERVICE_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE_OF_SERVICE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSURANCE_COVERAGE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DELETED_FLAG] [smallint] NULL,
 CONSTRAINT [PK_VEHICLE] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


CREATE TABLE [dbo].[VEHICLE_SUPP](
	[DA_ROW_ID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[JOBID] [int] NOT NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[UNIT_ID] [int] NULL,
 CONSTRAINT [PK_VEHICLE_SUPP] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[VEHICLE_X_ACC_DATE](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,	[UNIT_ID] [int] NOT NULL,
	[ACCIDENT_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CLAIM_ID] [int] NOT NULL,
	[VEH_X_ACC_DATE_ROW_ID] [int] NULL,
 CONSTRAINT [PK_VEHICLE_X_ACC_DATE] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[VEHICLE_X_INSPCT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[INVALID_ROW] [int] NULL,
	[UPDATE_ROW] [int] NULL,
	[UNIT_INSP_ROW_ID] [int] NOT NULL,
	[UNIT_ID] [int] NULL,
	[INSPECTION_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSPECTION_RESULT] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_VEHICLE_X_INSPCT] PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[ERROR_LOG] (
	[ERR_LOG_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INPUT_ROW_ID] [int] NULL,
	[MODULE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WORK_FLOW_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATA_FLOW_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERROR_TIME] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERROR_TITLE] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERROR_DESC] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IS_VALIDATION] [int] NULL,
	[ERROR_TABLE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABLE_ROW_ID] [int] NULL,
	[ERROR_COLUMNS] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_ERROR_LOG] PRIMARY KEY CLUSTERED
(
	[ERR_LOG_ROW_ID] ASC,
	[JOBID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[DA_STATISTICS] (
	[JOBID] [int] NOT NULL,
	[PASS_COUNT] [int] NOT NULL,
	[IS_VALIDATION] [int] NULL,
	[IMPORT_MODULE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABLE_NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INPUT_ROW_COUNT] [int] NULL,
	[START_VALID_ROW_COUNT] [int] NULL,
	[START_INVALID_ROW_COUNT] [int] NULL,
	[END_VALID_ROW_COUNT] [int] NULL,
	[END_INVALID_ROW_COUNT] [int] NULL,
	[TOTAL_ROWS] [int] NULL,
	[TOTAL_FAILED_VALIDATIONS] [int] NULL,
	[START_TIME] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[END_TIME] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_DA_STATISTICS] PRIMARY KEY CLUSTERED
(
	[JOBID] ASC,
	[PASS_COUNT] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[DIS_OPTIONSET](
	[JOBID] [int] NOT NULL,
	[VERIFICATION_FLAG] [int] NOT NULL,
	[NUMBER_OF_AREAS_IMPORTING] [int] NOT NULL,
	[EMPLOYEES_FLAG] [int] NULL,
	[EMPLOYEES_IMPORT_SUPP] [int] NULL,
	[EMPLOYEES_MATCH_EMPLOYEE_ID] [int] NULL,
	[EMPLOYEES_UPDATE_BLANK_ZERO] [int] NULL,
	[EMPLOYEES_UPDATE_ADDRESS_BLANK_ZERO] [int] NULL,
	[EMPLOYEES_CREATE_NEW_CODES] [int] NULL,
	[EMPLOYEES_MATCH_ENTITY_ID] [int] NULL,
	[ORGHIER_FLAG] [int] NULL,
	[ORGHIER_IMPORT_SUPP] [int] NULL,
	[ORGHIER_UPDATE_BLANK_ZERO] [int] NULL,
	[ORGHIER_CREATE_NEW_CODES] [int] NULL,
	[FUNDS_FLAG] [int] NULL,
	[FUNDS_IMPORT_SUPP] [int] NULL,
	[FUNDS_MATCH_PAYEE_NAME] [int] NULL,
	[FUNDS_MATCH_PAYEE_TAX_ID] [int] NULL,
	[FUNDS_CREATE_NEW_CODES] [int] NULL,
	[FUNDS_OPEN_CLAIMS_ONLY] [int] NULL,
	[FUNDS_CHECK_DUPLICATE_PAYMENTS] [int] NULL,
	[FUNDS_ACCEPT_DUPLICATE_CHECK_NUMBER] [int] NULL,
	[FUNDS_IMPORT_CLEARED_PAYMENTS] [int] NULL,
	[FUNDS_MATCH_ENTITY_ID] [int] NULL,
	[FUNDSDEPOSIT_FLAG] [int] NULL,
	[FUNDSDEPOSIT_UPDATE_BLANK_ZERO] [int] NULL,
	[FUNDSDEPOSIT_CREATE_NEW_CODES] [int] NULL,
	[VEHICLES_FLAG] [int] NULL,
	[VEHICLES_IMPORT_SUPP] [int] NULL,
	[VEHICLES_UPDATE_BLANK_ZERO] [int] NULL,
	[VEHICLES_CREATE_NEW_CODES] [int] NULL,
	[ENTITES_FLAG] [int] NULL,
	[ENTITES_IMPORT_SUPP] [int] NULL,
	[ENTITES_UPDATE_BLANK_ZERO] [int] NULL,
	[ENTITES_CREATE_NEW_CODES] [int] NULL,
	[ENTITES_MATCH_BY] [varchar](100) NULL,
	[POLICIES_FLAG] [int] NULL,
	[POLICIES_IMPORT_SUPP] [int] NULL,
	[POLICIES_CREATE_NEW_CODES] [int] NULL,
	[RESERVES_FLAG] [int] NULL,
	[RESERVES_IMPORT_SUPP] [int] NULL,
	[RESERVES_CREATE_NEW_CODES] [int] NULL,
	[RESERVES_CHECK_DUPLICATE_RESERVES] [int] NULL,
	[ORGEXPO_FLAG] [int] NULL,
	[ORGEXPO_IMPORT_SUPP] [int] NULL,
	[ORGEXPO_NEW_RECORDS_ONLY] [int] NULL,
	[ORGEXPO_UPDATE_BLANK_ZERO] [int] NULL,
	[ORGEXPO_CREATE_NEW_CODES] [int] NULL,
	[PATIENTS_FLAG] [int] NULL,
	[PATIENTS_IMPORT_SUPP] [int] NULL,
	[PATIENTS_VALIDATE_DATA] [int] NULL,
	[PATIENTS_MATCH_PATIENT] [int] NULL,
	[PATIENTS_CREATE_NEW_CODES] [int] NULL,
	[PATIENT_MATCH_PATIENT_NUMBER] [int] NULL,
	[PHYSICIANS_FLAG] [int] NULL,
	[PHYSICIANS_IMPORT_SUPP] [int] NULL,
	[PHYSICIANS_VALIDATE_DATA] [int] NULL,
	[PHYSICIANS_CREATE_NEW_CODES] [int] NULL,
	[PHYSICIANS_MATCH_PHYSICIANS_NUMBER] [int] NULL,
	[MEDICALSTAFF_FLAG] [int] NULL,
	[MEDICALSTAFF_IMPORT_SUPP] [int] NULL,
	[MEDICALSTAFF_VALIDATE_DATA] [int] NULL,
	[MEDICALSTAFF_CREATE_NEW_CODES] [int] NULL,
	[ADMINTRACK_FLAG] [int] NULL,
	[ADMINTRACK_AREA] [varchar](100)NULL,
	[ADMINTRACK_ADD_UPDATE] [int] NULL,
	[ADMINTRACK_CREATE_NEW_CODES] [int],
 CONSTRAINT [PK_DIS_OPTIONSET] PRIMARY KEY CLUSTERED 
(
	[JOBID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

