IF OBJECT_ID('DDS_SUPP_FIELDS', 'P') IS NOT NULL
    DROP PROCEDURE DDS_SUPP_FIELDS;
GO

CREATE PROCEDURE DDS_SUPP_FIELDS
(
@P_TABLENAME VARCHAR(50), 
@P_SFIELD VARCHAR(50),
@P_RMDBNAME VARCHAR(50)
) AS
DECLARE @V_SQL NVARCHAR(MAX);-- = N'';
DECLARE @V_RMDBNAME VARCHAR(50);-- = N'';
BEGIN
IF @P_SFIELD IS NULL 
BEGIN
	 SET @V_RMDBNAME = '['+@P_RMDBNAME +'].[DBO].';
     --SET @V_SQL =  'SELECT DISTINCT UPPER(SD.SYS_FIELD_NAME), SD.FIELD_ID FROM '+@V_RMDBNAME+'SUPP_DICTIONARY SD  WHERE SD.SUPP_TABLE_NAME = ' + ''''+@P_TABLENAME+'''' ;   
     SET @V_SQL =  'SELECT DISTINCT UPPER(SD.SYS_FIELD_NAME), SD.FIELD_ID FROM '+@V_RMDBNAME+'SUPP_DICTIONARY SD  WHERE SD.SUPP_TABLE_NAME = @TABLENAME_P' ;   
     SET  @V_SQL=@V_SQL +' AND SD.FIELD_TYPE NOT IN (7,20,31,10,25,12, 22,13)  AND SD.DELETE_FLAG = 0 ' ;

Execute sp_Executesql @V_SQL, 
 N' @TABLENAME_P VARCHAR(50)',
 @TABLENAME_P = @P_TABLENAME;
     
END 
ELSE IF @P_SFIELD IS NOT NULL
BEGIN
     SET @V_RMDBNAME = '['+@P_RMDBNAME +'].[DBO].';
     --SET @V_SQL =  'SELECT SD.CODE_FILE_ID FROM '+@V_RMDBNAME+'SUPP_DICTIONARY SD  WHERE SD.FIELD_ID = ' + ''''+@P_SFIELD+'''' ;   
     SET @V_SQL =  'SELECT SD.CODE_FILE_ID FROM '+@V_RMDBNAME+'SUPP_DICTIONARY SD  WHERE SD.FIELD_ID = @FIELD_ID_P' ;   
     SET  @V_SQL=@V_SQL +' AND SD.FIELD_TYPE NOT IN (7,20,31,10,25,12, 22,13)  AND SD.DELETE_FLAG = 0 ' ;
--PRINT @V_SQL
Execute sp_Executesql @V_SQL, 
 N' @FIELD_ID_P VARCHAR(50)',
 @FIELD_ID_P = @P_SFIELD;     
     
END      
     --PRINT @V_SQL
--     SELECT DISTINCT UPPER(SD.SYS_FIELD_NAME), SD.FIELD_ID FROM INFORMATION_SCHEMA.COLUMNS C RIGHT OUTER JOIN SUPP_DICTIONARY SD  
--ON UPPER(C.COLUMN_NAME) = UPPER(SD.SYS_FIELD_NAME) COLLATE DATABASE_DEFAULT 
--WHERE SD.SUPP_TABLE_NAME = 'EMP_SUPP' AND SD.FIELD_TYPE <> 7 AND SD.FIELD_TYPE <> 20 AND SD.DELETE_FLAG = 0
--and ISNULL(UPPER(C.TABLE_name),'EMP_SUPP')  = UPPER(SD.SUPP_TABLE_NAME)

--EXEC(@V_SQL);
END
