using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersion("1.0.163.0")]
[assembly: AssemblyFileVersion("1.0.163.0")]
[assembly: AssemblyCompany("CSC")]
[assembly: AssemblyProduct("RISKMASTER X r5")]
[assembly: AssemblyCopyright("Copyright (c) 2008, CSC")]
[assembly: AssemblyTrademark("CSC")]
[assembly: AssemblyCulture("")]
[assembly: CLSCompliant(true)]
[assembly: ComVisibleAttribute(true)]
