-- ============================================================
--   SCRIPT HEADER (DATABASE STRUCTURE)
--   Database Type: Oracle
--   DI Module Name: DIS DA_RMX_STAGING
--Create tables
--Template_DIS_Oracle.sql
--07/19/2012
--===========================================
declare iExists NUMBER;
 BEGIN
--==========================================================
---CREATE ADDRESS_X_PHONEINFO table 
--============================================================
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='ADDRESS_X_PHONEINFO';
IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE ADDRESS_X_PHONEINFO(

	DA_ROW_ID number(10) NOT NULL,
	JOBID number(10) NOT NULL,
	INPUT_ROW_ID number(10) NULL,
	INVALID_ROW number(10) NULL,
	UPDATE_ROW number(10) NULL,
	ENTITY_ID number(10) NULL,
	PHONE_ID number(10) NOT NULL,
	PHONE_CODE number (10) NULL,
	PHONE_NO varchar(30) NULL	
)';
EXECUTE IMMEDIATE 'ALTER TABLE ADDRESS_X_PHONEINFO ADD CONSTRAINT ADDRESS_X_PHONEINFO PRIMARY KEY (DA_ROW_ID, JOBID)';

END IF;


--==========================================================
---CREATE CODES table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='CODES';
IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE CODES(

	DA_ROW_ID number (10) NOT NULL,
	JOBID number (10) NOT NULL,
	INPUT_ROW_ID number (10) NULL,
	INVALID_ROW number (10) NULL,
	UPDATE_ROW number (10) NULL,
	IND_STANDARD_CODE number (10) NULL,
	LINE_OF_BUS_CODE number (10) NULL,
	CODE_ID number (10) NULL,
	TABLE_ID number (10) NULL,
	SHORT_CODE varchar(25) NULL,
	RELATED_CODE_ID number (10) NULL,
	DELETED_FLAG number (10) NULL,
	TRIGGER_DATE_FIELD varchar(50) NULL,
	EFF_START_DATE varchar(8) NULL,
	EFF_END_DATE varchar(8) NULL,
	ORG_GROUP_EID number (10) NULL	
)';

  EXECUTE IMMEDIATE 'ALTER TABLE CODES ADD CONSTRAINT PK_CODES PRIMARY KEY (DA_ROW_ID,JOBID)';
END IF;

--==========================================================
---CREATE CODES_TEXT table 
--============================================================
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='CODES_TEXT';
IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE CODES_TEXT(
	DA_ROW_ID number (10) NOT NULL,
	JOBID number (10) NOT NULL,
	INPUT_ROW_ID number (10) NULL,
	INVALID_ROW number (10) NULL,
	UPDATE_ROW number (10) NULL,
	CODE_ID number (10) NULL,
	LANGUAGE_CODE number (10) NULL,
	SHORT_CODE varchar(25) NULL,
	CODE_DESC varchar(50) NULL
)';

  EXECUTE IMMEDIATE 'ALTER TABLE CODES_TEXT ADD CONSTRAINT PK_CODES_TEXT PRIMARY KEY (DA_ROW_ID,JOBID)';
END IF;

--==========================================================
---CREATE DA_STATISTICS table 
--============================================================
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='DA_STATISTICS';
IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE DA_STATISTICS(
	JOBID number (10) NOT NULL,
	PASS_COUNT number (10) NOT NULL,
	IS_VALIDATION number (10) NULL,
	IMPORT_MODULE_NAME varchar(50) NULL,
	TABLE_NAME varchar(50) NOT NULL,
	INPUT_ROW_COUNT number (10) NULL,
	START_VALID_ROW_COUNT number (10) NULL,
	START_INVALID_ROW_COUNT number (10) NULL,
	END_VALID_ROW_COUNT number (10) NULL,
	END_INVALID_ROW_COUNT number (10) NULL,
	END_UPDATE_ROW_COUNT number (10) NULL,
	TOTAL_ROWS number (10) NULL,
	TOTAL_FAILED_VALIDATIONS number (10) NULL,
	START_TIME varchar(14) NULL,
	END_TIME varchar(14) NULL
)';

  EXECUTE IMMEDIATE 'ALTER TABLE DA_STATISTICS ADD CONSTRAINT PK_DA_STATISTICS PRIMARY KEY (JOBID,PASS_COUNT,TABLE_NAME)';
END IF;

--==========================================================
---CREATE EMP_X_DEPENDENT table 
--============================================================
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EMP_X_DEPENDENT';
IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EMP_X_DEPENDENT(

	DA_ROW_ID number (10)  NOT NULL,
	JOBID number (10)  NOT NULL,
	INPUT_ROW_ID number (10)  NULL,
	INVALID_ROW number (10)  NULL,
	UPDATE_ROW number (10)  NULL,
	EMP_DEP_ROW_ID number (10)  NULL,
	EMPLOYEE_EID number (10)  NULL,
	DEPENDENT_EID number (10)  NULL,
	HEALTH_PLAN_FLAG number (5) NULL,
	RELATION_CODE number (10)  NULL,
	DEPENDENT_ROW_ID number (10)  NULL
)';

  EXECUTE IMMEDIATE 'ALTER TABLE EMP_X_DEPENDENT ADD CONSTRAINT PK_EMP_X_DEPENDENT PRIMARY KEY (DA_ROW_ID,JOBID)';
END IF;
--==========================================================
---CREATE EMP_X_VIOLATION table 
--============================================================
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EMP_X_VIOLATION';
IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EMP_X_VIOLATION(

	DA_ROW_ID number (10) NOT NULL,
	JOBID number (10) NOT NULL,
	INPUT_ROW_ID number (10) NULL,
	INVALID_ROW number (10) NULL,
	UPDATE_ROW number (10) NULL,
	VIOLATION_ID number (10) NULL,
	EMPLOYEE_EID number (10) NULL,
	VIOLATION_CODE number (10) NULL,
	VIOLATION_DATE varchar(8) NULL

)';
  EXECUTE IMMEDIATE 'ALTER TABLE EMP_X_VIOLATION ADD CONSTRAINT PK_EMP_X_VIOLATION PRIMARY KEY (DA_ROW_ID,JOBID)';
END IF;
--==========================================================
---CREATE EMPLOYEE table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EMPLOYEE';
IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EMPLOYEE(

	DA_ROW_ID number (10) NOT NULL,
	JOBID number (10) NOT NULL,
	INPUT_ROW_ID number (10) NULL,
	INVALID_ROW number (10) NULL,
	UPDATE_ROW number (10) NULL,
	COUNTY_OF_RESIDNC varchar(50) NULL,
	DRIVLIC_STATE number (10) NULL,
	INSURABLE_FLAG number (10)  NULL,
	LAST_VERIFIED_DATE varchar(8) NULL,
	NUM_OF_VIOLATIONS number (10) NULL,
	TERM_DATE varchar(8) NULL,
	WORK_PERMIT_DATE varchar(8) NULL,
	WORK_PERMIT_NUMBER varchar(50) NULL,
	EMPLOYEE_EID number (10) NULL,
	ACTIVE_FLAG number (10)  NULL,
	EMPLOYEE_NUMBER varchar(20) NULL,
	MARITAL_STAT_CODE number (10) NULL,
	DATE_HIRED varchar(8) NULL,
	POSITION_CODE number (10) NULL,
	DEPT_ASSIGNED_EID number (10) NULL,
	SUPERVISOR_EID number (10) NULL,
	EXEMPT_STATUS_FLAG number (10)  NULL,
	NO_OF_EXEMPTIONS number (10) NULL,
	FULL_TIME_FLAG number (10)  NULL,
	HOURLY_RATE float NULL,
	WEEKLY_HOURS float NULL,
	WEEKLY_RATE float NULL,
	WORK_SUN_FLAG number (10)  NULL,
	WORK_MON_FLAG number (10)  NULL,
	WORK_TUE_FLAG number (10)  NULL,
	WORK_WED_FLAG number (10)  NULL,
	WORK_THU_FLAG number (10)  NULL,
	WORK_FRI_FLAG number (10)  NULL,
	WORK_SAT_FLAG number (10)  NULL,
	PAY_TYPE_CODE number (10) NULL,
	PAY_AMOUNT float NULL,
	DRIVERS_LIC_NO varchar(20) NULL,
	DRIVERSLICTYPECODE number (10) NULL,
	DATE_DRIVERSLICEXP varchar(8) NULL,
	DRIVLIC_RSTRCTCODE number (10) NULL,
	NCCI_CLASS_CODE number (10) NULL,
	DATE_OF_DEATH varchar(8) NULL,
	SEC_DEPT_EID number (10) NULL,
	JOB_CLASS_CODE number (10) NULL,
	MONTHLY_RATE float NULL,
	ELIG_DIS_BEN_FLAG number (10)  NULL,
	DIS_OPTION_CODE number (10) NULL,
	STAGING_ID number (10) NULL


)';
  EXECUTE IMMEDIATE 'ALTER TABLE EMPLOYEE ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY (DA_ROW_ID,JOBID)';
END IF;

--==========================================================
---CREATE ENTITY table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='ENTITY';
IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE ENTITY(
	DA_ROW_ID number (10)NOT NULL,
	JOBID number (10)NOT NULL,
	INPUT_ROW_ID number (10)NULL,
	INVALID_ROW number (10)NULL,
	UPDATE_ROW number (10)NULL,
	BUSINESS_TYPE_CODE number (10)NULL,
	COUNTY varchar(30) NULL,
	NATURE_OF_BUSINESS varchar(50) NULL,
	SIC_CODE number (10)NULL,
	SIC_CODE_DESC varchar(150) NULL,
	WC_FILING_NUMBER varchar(30) NULL,
	ENTITY_ID number (10)NULL,
	ENTITY_TABLE_ID number (10)NULL,
	LAST_NAME varchar(50) NULL,
	LAST_NAME_SOUNDEX varchar(8) NULL,
	FIRST_NAME varchar(50) NULL,
	ALSO_KNOWN_AS varchar(50) NULL,
	ABBREVIATION varchar(25) NULL,
	COST_CENTER_CODE number (10)NULL,
	ADDR1 varchar(50) NULL,
	ADDR2 varchar(50) NULL,
	CITY varchar(50) NULL,
	COUNTRY_CODE number (10)NULL,
	STATE_ID number (10)NULL,
	ZIP_CODE varchar(10) NULL,
	PARENT_EID number (10)NULL,
	TAX_ID varchar(20) NULL,
	CONTACT varchar(50) NULL,
	COMMENTS varchar(4000) NULL,
	EMAIL_TYPE_CODE number (10)NULL,
	EMAIL_ADDRESS varchar(100) NULL,
	SEX_CODE number (10)NULL,
	BIRTH_DATE varchar(8) NULL,
	PHONE1 varchar(30) NULL,
	PHONE2 varchar(30) NULL,
	FAX_NUMBER varchar(30) NULL,
	DTTM_RCD_ADDED varchar(14) NULL,
	DTTM_RCD_LAST_UPD varchar(14) NULL,
	UPDATED_BY_USER varchar(50) NULL,
	ADDED_BY_USER varchar(50) NULL,
	DELETED_FLAG number (5)NULL,
	SEC_DEPT_EID number (10)NULL,
	TRIGGER_DATE_FIELD varchar(50) NULL,
	EFF_START_DATE varchar(8) NULL,
	EFF_END_DATE varchar(8) NULL,
	PARENT_1099_EID number (10)NULL,
	REPORT_1099_FLAG number (5)NULL,
	MIDDLE_NAME varchar(50) NULL,
	TITLE varchar(50) NULL,
	NAICS_CODE number (10)NULL,
	RM_USER_ID number (10)NULL,
	FREEZE_PAYMENTS number (10)NULL,
	ORGANIZATION_TYPE number (10)NULL,
	NPI_NUMBER varchar(10) NULL,
	HTMLCOMMENTS varchar(4000) NULL,
	MMSEA_TIN_EDT_FLAG number (5)NULL,
	AUTO_DISCOUNT number (10,2) NULL,
	DISCOUNT_FLAG number (10)NULL,
	ENTITY_APPROVAL_STATUS number (10)NULL,
	ENTITY_REJECT_COMMENTS CLOB NULL,
	FROI_ACORD_PASSWORD varchar(15) NULL,
	MMSEA_OFE_STE_TEXT varchar(9) NULL,
	MMSEA_REPRTER_TEXT varchar(9) NULL,
	STAGING_ID number (10)NULL



)';

  EXECUTE IMMEDIATE 'ALTER TABLE ENTITY ADD CONSTRAINT PK_ENTITY PRIMARY KEY (DA_ROW_ID,JOBID)';
END IF;

--==========================================================
---CREATE ENTITY_X_ADDRESSES table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='ENTITY_X_ADDRESSES';
IF iExists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE ENTITY_X_ADDRESSES(

	DA_ROW_ID  number (10)  NOT NULL,
	JOBID  number (10)  NOT NULL,
	INPUT_ROW_ID  number (10)  NULL,
	INVALID_ROW  number (10)  NULL,
	UPDATE_ROW  number (10)  NULL,
	ENTITY_ID  number (10)  NULL,
	ADDRESS_ID  number (10)  NOT NULL,
	ADDR1 varchar(50) NULL,
	ADDR2 varchar(50) NULL,
	CITY varchar(50) NULL,
	COUNTY varchar(30) NULL,
	COUNTRY_CODE  number (10)  NULL,
	STATE_ID  number (10)  NULL,
	ZIP_CODE varchar(10) NULL,
	EMAIL_ADDRESS varchar(100) NULL,
	FAX_NUMBER varchar(30) NULL,
	PRIMARY_ADD_FLAG  number (5)  NULL


)';
  EXECUTE IMMEDIATE 'ALTER TABLE ENTITY_X_ADDRESSES ADD CONSTRAINT PK_ENTITY_X_ADDRESSES PRIMARY KEY (DA_ROW_ID, JOBID)';
END IF;

--==========================================================
---CREATE ERROR_LOG table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='ERROR_LOG';
IF iExists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE ERROR_LOG(

	ERR_LOG_ROW_ID   number(10) NOT NULL,
	JOBID   number(10) NOT NULL,
	INPUT_ROW_ID   number(10) NULL,
	MODULE_NAME varchar(50) NULL,
	WORK_FLOW_NAME varchar(50) NULL,
	DATA_FLOW_NAME varchar(50) NULL,
	ERROR_TIME varchar(14) NULL,
	ERROR_TITLE varchar(100) NULL,
	ERROR_DESC varchar(4000) NULL,
	IS_VALIDATION   number(10) NULL,
	ERROR_TABLE varchar(50) NULL,
	TABLE_ROW_ID  number(10) NULL,
	ERROR_COLUMNS varchar(4000) NULL


)';

  EXECUTE IMMEDIATE 'ALTER TABLE ERROR_LOG ADD CONSTRAINT PK_ERROR_LOG PRIMARY KEY (ERR_LOG_ROW_ID, JOBID)';
END IF;


--==========================================================
---CREATE PATIENT table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='PATIENT';
IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE PATIENT(
        
	DA_ROW_ID number (10) NOT NULL,
	JOBID  number (10) NOT NULL,
	INPUT_ROW_ID  number (10) NULL,
	INVALID_ROW  number (10) NULL,
	UPDATE_ROW  number (10) NULL,
	PATIENT_ID  number (10)  NULL,
	PATIENT_EID  number (10) NULL,
	PATIENT_ACCT_NO varchar(20) NULL,
	MEDICAL_RCD_NO varchar(20) NULL,
	DATE_OF_ADMISSION varchar(8) NULL,
	TIME_OF_ADMISSION varchar(6) NULL,
	DATE_OF_DISCHARGE varchar(8) NULL,
	TIME_OF_DISCHARGE varchar(6) NULL,
	ADMISSION_REASON varchar(4000) NULL,
	ADM_TYPE_CODE  number (10) NULL,
	ADM_SOURCE_CODE  number (10) NULL,
	ACUITY_LEVEL_CODE  number (10) NULL,
	CARDIAC_ARREST smallint NULL,
	PATIENT_STAT_CODE  number (10) NULL,
	PATIENT_COND_CODE  number (10) NULL,
	DISCHARGE_DSP_CODE  number (10) NULL,
	EXP_LENGTH_OF_STAY  number (10) NULL,
	EXPECTED_COST  number (10,2) NULL,
	INS_PLAN_GROUP_NO varchar(16) NULL,
	QI_SIGNIF_CODE  number (10) NULL,
	EPISODE_OF_CARE_ID varchar(8) NULL,
	PATIENT_TYPE_CODE  number (10) NULL,
	HEIGHT  number (10,2) NULL,
	WEIGHT  number (10,2) NULL,
	MARITAL_STAT_CODE  number (10) NULL,
	RACE_ENTH_CODE  number (10) NULL,
	DATE_OF_DEATH varchar(8) NULL,
	PRIMARY_PAY_CODE  number (10) NULL,
	SECOND_PAY_CODE  number (10) NULL,
	EMERGENCY_CONTACT varchar(20) NULL,
	EMERGENCY_CONT_NO varchar(20) NULL,
	PATIENT_ROOM_NO varchar(14) NULL,
	FACILITY_UNIT_CODE  number (10) NULL,
	FACILITY_DEPT_EID  number (10) NULL,
	HCO_ID_NO varchar(20) NULL,
	HCO_SITE_ID_NO varchar(20) NULL,
	PRI_PHYSICIAN_EID  number (10) NULL,
	ADM_PHYSICIAN_EID  number (10) NULL,
	NB_APGAR_SCORE  number (10) NULL,
	NB_BIRTH_WEIGHT  number (10,2) NULL,
	NB_LEN_OF_GEST  number (10) NULL,
	NB_NICU_STAY  number (10) NULL,
	NB_NICU_ADM_DATE varchar(8) NULL,
	NB_NICU_DISCH_DATE varchar(8) NULL,
	NB_CEPHALIC_MOLD  number (10) NULL,
	NB_EPS_OF_CARE_ID varchar(8) NULL,
	NBM_PARITY  number (10) NULL,
	NBM_PRIOR_C_SECT  number (10) NULL,
	NBM_MED_IND_LABOR  number (10) NULL,
	NBM_LIVE_BIRTHS  number (10) NULL,
	NBM_STILL_BIRTHS  number (10) NULL,
	NBM_GRAVIDA  number (10) NULL,
	NBM_EPS_OF_CARE_ID varchar(8) NULL,
	DISABILITY_CODE  number (10) NULL,
	ILLNESS_CODE  number (10) NULL,
	LOST_CONSC_FLAG  number (10) NULL,
	WHY_AT_FACILITY varchar(255) NULL


)';

  EXECUTE IMMEDIATE 'ALTER TABLE PATIENT ADD CONSTRAINT  PK_PATIENT PRIMARY KEY (DA_ROW_ID, JOBID)';

END IF;

--==========================================================
---CREATE PHYSICIAN table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='PHYSICIAN';
IF iExists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE PHYSICIAN(

	DA_ROW_ID  number (10)  NOT NULL,
	JOBID  number (10)  NOT NULL,
	INPUT_ROW_ID  number (10)  NULL,
	INVALID_ROW  number (10)  NULL,
	UPDATE_ROW  number (10)  NULL,
	PHYS_EID  number (10)  NULL,
	PHYSICIAN_NUMBER varchar(50) NULL,
	MED_STAFF_NUMBER varchar(50) NULL,
	MEDICARE_NUMBER varchar(20) NULL,
	PRIMARY_SPECIALTY  number (10)  NULL,
	PRIMARY_POLICY_ID  number (10)  NULL,
	HOME_ADDR1 varchar(50) NULL,
	HOME_ADDR2 varchar(50) NULL,
	HOME_CITY varchar(50) NULL,
	HOME_STATE_ID  number (10)  NULL,
	HOME_ZIP_CODE varchar(10) NULL,
	MARITAL_STAT_CODE  number (10)  NULL,
	BEEPER_NUMBER varchar(30) NULL,
	CELLULAR_NUMBER varchar(30) NULL,
	MAILING_ADDR1 varchar(50) NULL,
	MAILING_ADDR2 varchar(50) NULL,
	MAILING_CITY varchar(50) NULL,
	MAILING_STATE_ID  number (10)  NULL,
	MAILING_ZIP_CODE varchar(10) NULL,
	EMERGENCY_CONTACT varchar(30) NULL,
	STAFF_STATUS_CODE  number (10)  NULL,
	STAFF_TYPE_CODE  number (10)  NULL,
	STAFF_CAT_CODE  number (10)  NULL,
	INTERNAL_NUMBER varchar(20) NULL,
	DEPT_ASSIGNED_EID  number (10)  NULL,
	APPOINT_DATE varchar(8) NULL,
	REAPPOINT_DATE varchar(8) NULL,
	LIC_STATE  number (10)  NULL,
	LIC_NUM varchar(20) NULL,
	LIC_ISSUE_DATE varchar(8) NULL,
	LIC_EXPIRY_DATE varchar(8) NULL,
	LIC_DEA_NUM varchar(20) NULL,
	LIC_DEA_EXP_DATE varchar(8) NULL,
	MEMBERSHIP varchar(20) NULL,
	CONT_EDUCATION varchar(20) NULL,
	TEACHING_EXP varchar(20) NULL
	


)';
  EXECUTE IMMEDIATE 'ALTER TABLE PHYSICIAN ADD CONSTRAINT PK_PHYSICIAN PRIMARY KEY (DA_ROW_ID, JOBID)';

END IF;

--==========================================================
---CREATE DIS_OPTIONSET table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='DIS_OPTIONSET';
IF iExists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE DIS_OPTIONSET(

	JOBID number (10) NOT NULL,
	VERIFICATION_FLAG number (10) NULL,
	NUMBER_OF_AREAS_IMPORTING number (10) NULL,
	EMPLOYEES_FLAG number (10) NULL,
	EMPLOYEES_IMPORT_SUPP number (10) NULL,
	EMPLOYEES_MATCH_EMPLOYEE_ID number (10) NULL,
	EMPLOYEES_UPDATE_BLANK_ZERO number (10) NULL,
        EMP_UPDATE_ADDRESS_BLANK_ZERO   number (10) NULL,
	EMPLOYEES_CREATE_NEW_CODES number (10) NULL,
	EMPLOYEES_MATCH_ENTITY_ID number (10) NULL,
	ORGHIER_FLAG number (10) NULL,
	ORGHIER_IMPORT_SUPP number (10) NULL,
	ORGHIER_UPDATE_BLANK_ZERO number (10) NULL,
	ORGHIER_CREATE_NEW_CODES number (10) NULL,
	FUNDS_FLAG number (10) NULL,
	FUNDS_IMPORT_SUPP number (10) NULL,
	FUNDS_MATCH_PAYEE_NAME number (10) NULL,
	FUNDS_MATCH_PAYEE_TAX_ID number (10) NULL,
	FUNDS_CREATE_NEW_CODES number (10) NULL,
	FUNDS_OPEN_CLAIMS_ONLY number (10) NULL,
	FUNDS_CHECK_DUPLICATE_PAYMENTS number (10) NULL,
	FUNDS_ACCEPT_DUP_CHECK_NUMBER   number (10) NULL,
	FUNDS_IMPORT_CLEARED_PAYMENTS number (10) NULL,
	FUNDS_MATCH_ENTITY_ID number (10) NULL,
	FUNDSDEPOSIT_FLAG number (10) NULL,
	FUNDSDEPOSIT_UPDATE_BLANK_ZERO number (10) NULL,
	FUNDSDEPOSIT_CREATE_NEW_CODES number (10) NULL,
	VEHICLES_FLAG number (10) NULL,
	VEHICLES_IMPORT_SUPP number (10) NULL,
	VEHICLES_UPDATE_BLANK_ZERO number (10) NULL,
	VEHICLES_CREATE_NEW_CODES number (10) NULL,
	ENTITIES_FLAG number (10) NULL,
	ENTITIES_IMPORT_SUPP number (10) NULL,
	ENTITIES_UPDATE_BLANK_ZERO number (10) NULL,
	ENTITIES_CREATE_NEW_CODES number (10) NULL,
	POLICIES_FLAG number (10) NULL,
	POLICIES_IMPORT_SUPP number (10) NULL,
	POLICIES_CREATE_NEW_CODES number (10) NULL,
	RESERVES_FLAG number (10) NULL,
	RESERVES_IMPORT_SUPP number (10) NULL,
	RESERVES_CREATE_NEW_CODES number (10) NULL,
	RESERVES_CHECK_DUPLICATE number (10) NULL,
	ORGEXPO_FLAG number (10) NULL,
	ORGEXPO_IMPORT_SUPP number (10) NULL,
	ORGEXPO_NEW_RECORDS_ONLY number (10) NULL,
	ORGEXPO_UPDATE_BLANK_ZERO number (10) NULL,
	ORGEXPO_CREATE_NEW_CODES number (10) NULL,
	PATIENTS_FLAG number (10) NULL,
	PATIENTS_IMPORT_SUPP number (10) NULL,
	PATIENTS_VALIDATE_DATA number (10) NULL,
	PATIENTS_MATCH_PATIENT number (10) NULL,
	PATIENTS_CREATE_NEW_CODES number (10) NULL,
	PATIENT_MATCH_PATIENT_NUMBER number (10) NULL,
	PHYSICIANS_FLAG number (10) NULL,
	PHYSICIANS_IMPORT_SUPP number (10) NULL,
	PHYSICIANS_VALIDATE_DATA number (10) NULL,
	PHYSICIANS_CREATE_NEW_CODES number (10) NULL,
	PHYSICIANS_MATCH_PHY_NUMBER number (10) NULL,
	MEDICALSTAFF_FLAG number (10) NULL,
	MEDICALSTAFF_IMPORT_SUPP number (10) NULL,
	MEDICALSTAFF_VALIDATE_DATA number (10) NULL,
	MEDICALSTAFF_CREATE_NEW_CODES number (10) NULL,
	ADMINTRACK_FLAG number (10) NULL,
	ADMINTRACK_AREA varchar(100)NULL,
	ADMINTRACK_ADD_UPDATE number (10) NULL,
	ADMINTRACK_CREATE_NEW_CODES number (10) NULL,
	ADMINTRACK_MATCH_FIELD varchar(50) NULL,
	ENTITIES_MATCH_BY_TAXID number (10) NULL,
	ENTITIES_MATCH_BY_NAME number (10) NULL,
	ENTITIES_MATCH_BY_Abbrev number (10) NULL,
	DIARY_TO_USERS varchar(100) NULL
)';

  EXECUTE IMMEDIATE 'ALTER TABLE DIS_OPTIONSET ADD CONSTRAINT PK_DIS_OPTIONSET PRIMARY KEY (JOBID)';

END IF;

--==========================================================
---CREATE T_DIS_ADDRESS_X_PHONEINFO table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='T_DIS_ADDRESS_X_PHONEINFO';
IF iExists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE T_DIS_ADDRESS_X_PHONEINFO(

	DA_ROW_ID number (10) NOT NULL,
	JOBID number (10) NOT NULL,
	ENTITY_ID number (10) NULL


)';
  EXECUTE IMMEDIATE 'ALTER TABLE T_DIS_ADDRESS_X_PHONEINFO ADD CONSTRAINT PK_T_DIS_ADDRESS_X_PHONEINFO PRIMARY KEY (DA_ROW_ID, JOBID)';

END IF;

--==========================================================
---CREATE T_DIS_EMP_X_DEPENDENT table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='T_DIS_EMP_X_DEPENDENT';
IF iExists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE T_DIS_EMP_X_DEPENDENT(

	JOBID number (10)  NOT NULL,
	DA_ROW_ID number (10)  NOT NULL,
	EMPLOYEE_EID number (10)  NULL,
	DEPENDENT_EID number (10)  NULL

)';
  EXECUTE IMMEDIATE 'ALTER TABLE T_DIS_EMP_X_DEPENDENT ADD CONSTRAINT PK_T_DIS_EMP_X_DEPENDENT PRIMARY KEY (DA_ROW_ID, JOBID)';

END IF;

--==========================================================
---CREATE T_DIS_EMP_X_VIOLATION table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='T_DIS_EMP_X_VIOLATION';
IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE T_DIS_EMP_X_VIOLATION(

	JOBID number (10) NOT NULL,
	DA_ROW_ID number (10)  NOT NULL,
	EMPLOYEE_EID number (10) NULL,
	DEPENDENT_EID number (10)  NULL


)';
  EXECUTE IMMEDIATE 'ALTER TABLE T_DIS_EMP_X_VIOLATION ADD CONSTRAINT PK_T_DIS_EMP_X_VIOLATION PRIMARY KEY (DA_ROW_ID, JOBID)';

END IF;
--==========================================================
---CREATE T_DIS_EMPLOYEE table 
--============================================================

SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='T_DIS_EMPLOYEE';
IF iExists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE T_DIS_EMPLOYEE(

	JOBID number (10)  NOT NULL,
	DA_ROW_ID number (10)  NOT NULL,
	EMPLOYEE_EID varchar(50) NULL,
	EMP_ENTITY_ID varchar(50) NULL,
	SUPERVISOR_EID varchar(50) NULL,
	DEPT_ASSIGNED_EID varchar(50) NULL


)';
  EXECUTE IMMEDIATE 'ALTER TABLE T_DIS_EMPLOYEE ADD CONSTRAINT PK_T_DIS_EMPLOYEE PRIMARY KEY (DA_ROW_ID, JOBID)';

END IF;

--==========================================================
---CREATE T_DIS_ENTITY table 
--============================================================
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='T_DIS_ENTITY';
IF iExists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE T_DIS_ENTITY
(
	JOBID number (10)  NOT NULL,
	DA_ROW_ID number (10) NOT NULL,
	ENTITY_ID varchar(50) NULL,
	ENTITY_TABLE_ID varchar(50) NULL,
	SIC_CODE varchar(50) NULL,
	PARENT_EID varchar(50) NULL,
	PARENT_ABBREV varchar(50) NULL,
	PARENT_1099_EID varchar(50) NULL,
	EXTERNAL_KEY varchar(50) NULL



)';
  EXECUTE IMMEDIATE 'ALTER TABLE T_DIS_ENTITY ADD CONSTRAINT PK_T_DIS_ENTITY PRIMARY KEY (DA_ROW_ID, JOBID)';
END IF;

--==========================================================
---CREATE T_DIS_ENTITY_X_ADDRESSES table 
--============================================================
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='T_DIS_ENTITY_X_ADDRESSES';
IF iExists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE T_DIS_ENTITY_X_ADDRESSES
(
	DA_ROW_ID number (10) NOT NULL,
	JOBID number (10)NOT NULL,
	ENTITY_ID number (10) NULL



)';
  EXECUTE IMMEDIATE 'ALTER TABLE T_DIS_ENTITY_X_ADDRESSES ADD CONSTRAINT PK_T_DIS_ENTITY_X_ADDRESSES PRIMARY KEY (DA_ROW_ID, JOBID)';
END IF;

--==========================================================
---CREATE T_DIS_ORG_HIER table 
--============================================================
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='T_DIS_ORG_HIER';
IF iExists = 0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE T_DIS_ORG_HIER
(
	DA_ROW_ID number (10) NOT NULL,
	JOBID number (10) NOT NULL,
	ENTITY_ID_SOURCE number (10) NULL,
	ENTITY_TABLE_DESC varchar(18) NULL,
	PARENT_EID_SOURCE number (10) NULL,
	PARENT_ABBREV_DESC varchar(25) NULL
)';
  EXECUTE IMMEDIATE 'ALTER TABLE T_DIS_ORG_HIER ADD CONSTRAINT PK_T_DIS_ORG_HIER PRIMARY KEY (DA_ROW_ID, JOBID)';
  
  END IF;

--==========================================================
---CREATE UNIQUE_CODE table 
--============================================================
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='UNIQUE_CODE';
IF iExists = 0 THEN

EXECUTE IMMEDIATE
'CREATE TABLE UNIQUE_CODE
(
	JOBID number (10) NOT NULL,
	DA_ROW_ID number (10) NOT NULL,
	TABLE_ID number (10) NULL,
	CODE_ID number (10) NULL,
	LINE_OF_BUS_CODE number (10) NULL,
	RELATED_CODE_ID number (10) NULL,
	NEW_CODE number (10) NULL,
	SHORT_CODE varchar(25) NULL,
	CODE_TABLE_NAME varchar(30) NULL,
    DELETED_FLAG number (10) NULL


)';
EXECUTE IMMEDIATE
'ALTER TABLE UNIQUE_CODE ADD CONSTRAINT PK_UNIQUE_CODE PRIMARY KEY (DA_ROW_ID, JOBID)';

END IF;
END;