--   Template-RMA_16.1 And Onwards DDS
DECLARE
XML_STRING CLOB;

BEGIN

XML_STRING := '<DDS><gEVENTS_AVAILABLE></gEVENTS_AVAILABLE><gMED_WATCH_AVAILABLE></gMED_WATCH_AVAILABLE><gCLAIMS_AVAILABLE></gCLAIMS_AVAILABLE><gSTD_AVAILABLE></gSTD_AVAILABLE><gADJUSTER_NOTES_AVAILABLE></gADJUSTER_NOTES_AVAILABLE><gPAYMENTS_AVAILABLE></gPAYMENTS_AVAILABLE><gPAYMENT_SUB_ACCOUNT></gPAYMENT_SUB_ACCOUNT><gPAYMENT_BANK_ACCOUNT></gPAYMENT_BANK_ACCOUNT><gENHANCED_NOTES_AVAILABLE></gENHANCED_NOTES_AVAILABLE><gPERFORM_VERIFICATION></gPERFORM_VERIFICATION><gCHK_DUPLICATE_ENTITY></gCHK_DUPLICATE_ENTITY><gALLOW_NEW_CODES></gALLOW_NEW_CODES><gALLOW_NEW_EMPLOYEES></gALLOW_NEW_EMPLOYEES><gALLOW_NEW_DEPARTMENT></gALLOW_NEW_DEPARTMENT><gCHK_CREATE_NEWENTITY></gCHK_CREATE_NEWENTITY><gEMPLOYEE_MATCH_BY_NAME></gEMPLOYEE_MATCH_BY_NAME><gEMPLOYEE_MATCH_BY_TAX_ID></gEMPLOYEE_MATCH_BY_TAX_ID><gEMPLOYEE_MATCH_BY_DOB></gEMPLOYEE_MATCH_BY_DOB>
<gEMPLOYEE_MATCH_BY_EMP_NUM></gEMPLOYEE_MATCH_BY_EMP_NUM><gNON_EMP_MATCH_BY_NAME></gNON_EMP_MATCH_BY_NAME><gNON_EMP_MATCH_BY_TAX_ID></gNON_EMP_MATCH_BY_TAX_ID><gNON_EMP_MATCH_BY_DOB></gNON_EMP_MATCH_BY_DOB><gCREATE_PI_ENT_IF_TAXID_EMPTY></gCREATE_PI_ENT_IF_TAXID_EMPTY><gALLOW_NEW_CLAIMS></gALLOW_NEW_CLAIMS><gID_CLAIMANT_BY_NAME_GCVA></gID_CLAIMANT_BY_NAME_GCVA><gID_CLAIMANT_BY_SUFFIX_GCVA></gID_CLAIMANT_BY_SUFFIX_GCVA><gUPDATE_CLAIMANT_NAME_GCVA></gUPDATE_CLAIMANT_NAME_GCVA><gCRT_ENT_IF_TAXID_EMPTY_GCVA></gCRT_ENT_IF_TAXID_EMPTY_GCVA><gUPDATE_CLAIMANT_NAME_WC></gUPDATE_CLAIMANT_NAME_WC><gATTACH_TRANS_ID_TO_CHECK_NO></gATTACH_TRANS_ID_TO_CHECK_NO><gRECALCULATE_RESERVES></gRECALCULATE_RESERVES><gDONT_CHECK_DUPLICATE_PAYMENTS></gDONT_CHECK_DUPLICATE_PAYMENTS><gCHECK_DUPLICATE_RESERVE_TRANS><gID_CLAIMANT_BY_Suffix></gID_CLAIMANT_BY_Suffix><gID_CLAIMANT_BY_NAME></gID_CLAIMANT_BY_NAME></gCHECK_DUPLICATE_RESERVE_TRANS><gVALIDATE_SUPPLEMENTALS></gVALIDATE_SUPPLEMENTALS><gSET_ADJUSTER_AS_CURRENT></gSET_ADJUSTER_AS_CURRENT><gEN_ENT_MATCH_BY_NAME></gEN_ENT_MATCH_BY_NAME><gEN_ENT_MATCH_BY_TAX_ID></gEN_ENT_MATCH_BY_TAX_ID><gEN_ENT_MATCH_BY_ABBRV></gEN_ENT_MATCH_BY_ABBRV><gCONFIG_ID></gCONFIG_ID><gEVENT_SUPP></gEVENT_SUPP><gCLAIM_SUPP></gCLAIM_SUPP><gPAYMENT_SUPP></gPAYMENT_SUPP><gORGSEC_FLAG></gORGSEC_FLAG><gDIARY_TO_USERS></gDIARY_TO_USERS><gUSE_TRANSACTIONS></gUSE_TRANSACTIONS><gVALID_START_DATE></gVALID_START_DATE><gVALID_END_DATE></gVALID_END_DATE><gEVENT_IMPORTFILE_NAME></gEVENT_IMPORTFILE_NAME><gMEDWATCH_IMPORTFILE_NAME></gMEDWATCH_IMPORTFILE_NAME><gCLAIM_IMPORTFILE_NAME></gCLAIM_IMPORTFILE_NAME><gSTD_PLAN_IMPORTFILE_NAME></gSTD_PLAN_IMPORTFILE_NAME><gSTD_CLASS_IMPORTFILE_NAME></gSTD_CLASS_IMPORTFILE_NAME><gADJUSTER_IMPORTFILE_NAME></gADJUSTER_IMPORTFILE_NAME><gPAYMENT_IMPORTFILE_NAME></gPAYMENT_IMPORTFILE_NAME><gEN_IMPORTFILE_NAME></gEN_IMPORTFILE_NAME></DDS>';

DELETE from DATA_INTEGRATOR_TEMPLATES where MODULE_NAME='DDS';

INSERT INTO DATA_INTEGRATOR_TEMPLATES VALUES ((NVL((SELECT MAX(ROW_ID) FROM DATA_INTEGRATOR_TEMPLATES),0) + 1), 'DDS', XML_STRING);
COMMIT;
END ;


 