--============================================================
--   DI Module Name: DA EDI Medical and Florida Medical
--   DESCRIPTION: Structure Definition Script for Staging database of DA EDI Medical.
--	 Template_MEDEDI(rmA16.4 onwards)
--   Script Date: 03/17/2017 
--	 Author		: kkaur25
--==============================================================


IF ((SELECT COUNT(*) AS isRMDB FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='SYS_PARMS')=1)
	BEGIN
		PRINT 'Error: Script Execution Aborted - Script trying to execute on RISKMASTER database not on DA Staging database. Please open the correct Staging database and execute this script.';
	END
ELSE
BEGIN
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_OPTIONS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_OPTIONS]
BEGIN
CREATE TABLE [DBO].[EDI_MEDICAL_OPTIONS](
[JOBID] [INT] NOT NULL , 
[MEDICAL_BILL_TYPE][INT]NULL,
[OPTIONSET_ID] [INT] NOT NULL , 
[DATEOPTION] [INT]  NULL , 
[DATEFROM] [VARCHAR](8)  NULL , 
[DATETO] [VARCHAR](8)  NULL , 
[REPORT_PERIOD_DATETO] [VARCHAR](8)  NULL,
[REPORT_PERIOD_DATEFROM] [VARCHAR](8)  NULL,
[EXTRACTFILENAME] [VARCHAR](1024)  NULL , 
[IAIABC_TRASN_ID_NUM] [VARCHAR](50)  NULL , 
[IAIABC_SENDER_ID] [VARCHAR](50)  NULL , 
[IAIABC_RECEIVER_ID] [VARCHAR](50)  NULL ,
[STR_PARM_NAME][VARCHAR](100) NULL,
[CreateNewCtl]int null,
[FLMedBillType]int null,
[ExtractPreviousData] int null,
[RISKMASTR_ProducInd] varchar(1) null,
[BillTypeFlag] int null,

CONSTRAINT [PK_EDI_MEDICAL_OPTIONS] PRIMARY KEY CLUSTERED
	( [JOBID],
	[OPTIONSET_ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDIMEDICALEXSOURCE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDIMEDICALEXSOURCE]
BEGIN

CREATE TABLE [DBO].[EDIMEDICALEXSOURCE](
OPTIONSETID [INT]  NOT NULL, 
		CONTROLNO [VARCHAR](50)  NULL, 
		BSRCODE [VARCHAR](50)  NULL,
		CLAIM_ID [int] NULL,
		STATEABBRE [VARCHAR](50)  NULL,
		STATE_ROW_ID [INT]  NULL,
		TRANS_ID [INT]  NULL )
END


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_EXTRACT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_EXTRACT]
BEGIN
CREATE TABLE [dbo].[EDI_MEDICAL_EXTRACT](
	[JOBID] [int] NOT NULL,
	[DA_ROW_ID] [int] NOT NULL,
	[INVALID_ROW_ID] [int] NULL,
	[REPORT_PERIOD_DATETO] [VARCHAR](8)  NULL,
	[REPORT_PERIOD_DATEFROM] [VARCHAR](8)  NULL,
	[MEDI_CLAIM_ID] [int] NOT NULL,
	[MEDI_ORIGINATOR_TRANS_ID_NUM][varchar](50) NULL,
	[MEDI_DATE_TRNSMSSN_SENT][varchar](8) NULL,
	[MEDI_TIME_TRNSMSSN_SENT][varchar](6) NULL,
	[MEDI_SENDER_ID][varchar](9) NULL,
	[MEDI_RECEIVER_ID][varchar](9) NULL,
	[MEDI_REPORTING_PERIOD] [int] NULL,
	[MEDI_INSURER_EID][int] NULL,
	[MEDI_INSURER_NAME] [varchar](255) NULL,		--mpandey24 Added
	[MEDI_INSURER_ZIP] [varchar](10) NULL,			--mpandey24 Added
	[MEDI_INSURER_TID] [varchar](20) NULL,			--mpandey24 Added
	[MEDI_CLAIM_ADMIN_NAME][varchar](50) NULL,
	[MEDI_CLAIM_ADMINI_FEIN][varchar](9) NULL,
	[MEDI_CLAIM_ADMIN_POST_CODE][varchar](10) NULL,
	[MEDI_EMPLOYER_EID][int] NULL,
	[MEDI_DATE_OF_INJURY][varchar](8) NULL,
	[EMP_LAST_NAME] [varchar](255) NULL,
	[EMP_FIRST_NAME] [varchar](255) NULL,
	[EMP_MIDDLE_NAME] [varchar](255) NULL,
	[EMP_SUFFIX_COMMON] [int] NULL,
	[EMP_TAX_ID] [varchar](20) NULL,
	[EMP_ADDR1] [varchar](100) NULL,
	[EMP_ADDR2] [varchar](100) NULL,
	[EMP_CITY] [varchar](50) NULL,
	[EMP_STATE_ID] [varchar](25) NULL,
	[EMP_COUNTRY_CODE] [varchar](25) NULL,
	[EMP_SEX_CODE] [varchar](25) NULL,
	[EMP_BIRTH_DATE] [varchar](8) NULL,
	[EMP_PHONE1] [varchar](30) NULL,
	[EMP_ZIP_CODE][varchar](10) NULL,
	[MEDI_EMPL_NAME_SUFFIX][varchar](4) NULL,
	[MEDI_EMPL_GREEN_CARD] [varchar](15) NULL,
	[MEDI_EMPL_JUR_ID] [varchar](15) NULL,
	[MEDI_EMPL_PASSPORT] [varchar](15) NULL,
	[MEDI_EMPL_EMP_VISA] [varchar](15) NULL,
	[MEDI_CLAIM_ADMIN_CLM_NUM][varchar](25) NULL,
	[MEDI_JURIS_CLM_NUM][varchar](25) NULL,
	[MEDI_BILL_PRO_UNI_BILL_ID_NUM][int] NULL,
	[MEDI_TOT_CHARGE_BILL][decimal](10,2) NULL,
	[MEDI_BILL_TYPE_CODE] [int] NULL,
	[MEDI_FACLITY_TYPE_CODE] [int] NULL,
	[MEDI_PLCE_OF_SRVC_BILL_CODE][int] NULL,
	[MEDI_BILL_FORMAT_CODE][int]NULL,
	[MEDI_BILL_FREQ_TYPE_CODE][INT]NULL,
	[MEDI_PROV_AGRMNT_CODE][INT]NULL,
	[MEDI_BILL_SUB_RSN_CODE][INT]NULL,
	[MEDI_DATE_INSRER_RCVD_BILL][varchar](8) NULL,
	[MEDI_ADMISN_DATE][varchar](12) NULL,
	[MEDI_ADMISN_HOUR][varchar](12) NULL,
	[MEDI_DSCHRGE_DATE][varchar](12) NULL,
	[MEDI_DSCHRGE_HOUR][varchar](12) NULL,
	[MEDI_SRVC_BILL_DATETO][varchar](8) NULL,
	[MEDI_SRVC_BILL_DATEFROM][varchar](8) NULL,
	[MEDI_PRSCRPTN_DATETO][varchar](8) NULL,
	[MEDI_PRSCRPTN_DATEFROM][varchar](8) NULL,
	[MEDI_DATE_OF_BILL][varchar](8) NULL,
	[MEDI_DATE_INSRD_PAID_BILL][varchar](8) NULL,
	[MEDI_ADMSSN_TYPE_CODE] [int] NULL,
	[MEDI_ADMSSN_TYPE_SHORT_CODE] [varchar](25) NULL,
	[MEDI_CONTRCT_TYPE_CODE] [int] NULL,
	[MEDI_CONTRCT_TYPE_SHORT_CODE] [varchar](25) NULL,
	[MEDI_TOT_AMT_PAID_PER_BILL][decimal](10,2) NULL,
	[MEDI_UNIQ_BILL_ID_NUM][varchar](50) NULL,
	[MEDI_TRANS_TRACK_NUM][varchar](50)NULL,
	[MEDI_TRTMNT_AUTHOR_NUM][varchar](50) NULL,
	[MEDI_LMPSM_PYMNT_CODE][int]NULL,
	[MEDI_LMPSM_PYMNT_SHRT_CODE][varchar](25)NULL,
	[MEDI_PRNCPL_DIG_CODE][int]NULL,
	[MEDI_ADMTNG_DIAG_CODE][int]NULL,
	[MEDI_BILD_DRG_CODE][int] NULL,
	[MEDI_BIL_PRV_EID][int] NULL,
	[MEDI_BIL_PRV_NAME_SUFFIX][varchar](4) NULL,
	[MEDI_BIL_PRV_PRM_SPL_CODE][int] NULL,
	[MEDI_BIL_PRV_STE_LIC_NUM][varchar](50) NULL,
	[MEDI_RENDRNGBILL_EID][int] NULL,
	[MEDI_RENDRNGBILL_NAME_SUFFIX][varchar](4) NULL,
	[MEDI_RENDRNGBILL_PRM_SPL_CODE][int] NULL,
	[MEDI_RENDRNGBILL_STE_LIC_NUM][varchar](50) NULL,
	[MEDI_SUPERVISE_EID][int] NULL,
	[MEDI_SUPERVISE_SUFFIX][varchar](4) NULL,
	[MEDI_SUPERVISE_PRM_SPL_CODE][int] NULL,
	[MEDI_SUPERVISE_STE_LIC_NUM][varchar](50) NULL,
	[MEDI_FACILITY_EID][int] NULL,
	[MEDI_FACILITY_STE_LIC_NUM][varchar](50) NULL,
	[MEDI_FACILITY_SRVC_LOC_ID][int]NULL,
	[MEDI_REFERRNG_EID][int] NULL,
	[MEDI_REFERRNG_SUFFIX][varchar](4) NULL,
	[MEDI_REFERRNG_STE_LIC_NUM][varchar](50) NULL,
	[MEDI_REFER_FIRST_NAME][varchar](255) NULL,
	[MEDI_REFER_LAST_NAME][varchar](255) NULL,
	[MEDI_REFER_MIDDLE_NAME][varchar](255) NULL,
	[MEDI_REFER_NPI][varchar](10) NULL,
	[MEDI_MCO_NAME][varchar](255) NULL,
	[MEDI_MCO_SSN][varchar](9) NULL,
	[MEDI_MCO_IDNUM][int] NULL,
	[MEDI_BILL_ADJUST_GRP_CODE][int] NULL,
	[MEDI_PRIOR_ACT_AMT_PAID][decimal](20,2) NULL,
	[MEDI_LINE_NUM][int] NULL,
	[MEDI_PROC_DESC][varchar](80) NULL,
	[MEDI_TOT_CHARGE_PER_LINE][decimal](10,2) NULL,
	[MEDI_DAY_PER_UNT_CODE][int] NULL,
	[MEDI_DAY_PER_UNT_BLD][varchar](2) NULL,
	[MEDI_PLC_OF_SRVC_LNE_CODE][int] NULL,
	[MEDI_DIAGNOSIS_PTR][varchar](1) NULL,
	[MEDI_REV_BLD_CODE][int] NULL,
	[MEDI_PRSCRPTN_LINE_NUM][varchar](50) NULL,
	[MEDI_NDC_BLD_CODE][int] NULL,
	[MEDI_DSPNS_AS_WRTN_CODE][int] NULL,
	[MEDI_DRUG_NAME][varchar](80) NULL,
	[MEDI_CMP_DRG_INDI][varchar](2) NULL,
	[MEDI_SRVC_LINE_DATETO][varchar](17) NULL,
	[MEDI_SRVC_LINE_DATEFROM][varchar](17) NULL,
	[MEDI_PRCRPTN_LINE_DATE][varchar](8) NULL,
	[MEDI_DRG_SUPP_DISP][varchar](15) NULL,
	[MEDI_DRG_SUPP_NO_DAYS][varchar](15) NULL,
	[MEDI_CNTRCT_TYPE_CODE][int] NULL,
	[MEDI_TRMNT_LINE_AUTHOR_NUM][varchar](50) NULL,
	[MEDI_DRG_SUPP_DIS_FEE][varchar](15) NULL,
	[MEDI_DRG_SUPP_BLD_AMT][decimal](10,2) NULL,
	[MEDI_LINE_ITM_TAX_CHRG_AMT][decimal](10,2) NULL,
	[MEDI_RENDRNGLINE_EID][int] NULL,
	[MEDI_RENDRNGLINE_NAME_SUFFIX][varchar](4) NULL,
	[MEDI_RENDRNGLINE_PRM_SPL_CODE][int] NULL,
	[MEDI_RENDRNGLINE_STE_LIC_NUM][varchar](50) NULL,
	[MEDI_TOT_AMT_PAID_PRLINE][decimal](10,2) NULL,
	[MEDI_RVN_PAID_CODE][int] NULL,
	[MEDI_DAY_PER_UNT_PAID][varchar](2) NULL,
	[MEDI_LINE_ITM_PRIOR_ACT_AMT][decimal](10,2) NULL,
	[MEDI_LINE_ITM_TAX_PAID_AMT][decimal](10,2) NULL,
	[MEDI_FILING_STATE_ID][INT] null,
	[MEDI_EMPLOYEE_EID][INT] null,
	[MEDI_ADMIN_EID] [INT] Null,
	[MEDI_CLAIM_TYPE_CODE] [INT] Null,
	[MEDI_PRIMARY_POLICY_ID] [int] Null,
	[MEDI_IS_CARRIER_CLAIM][int] Null,	
	[MEDI_PI_DEPT_ASSIGNED_EID] [int] Null,
	[MEDI_DATE_OF_EVENT] [varchar] (8) Null,
	[MEDI_EVENT_ID] int null,
	[MEDI_DEF_CARRIER_EID]int null,
	[MEDI_CLMADMIN_ORG_LEVEL] int null,
	[MEDI_PRINT_CLAIM_ADMIN]int null,
	[MEDI_CLAIMADMIN_TPA_EID] int null,
	[MEDI_DEF_CLAIM_ADMIN_EID]int null,
	[MEDI_EMPLOYER_LEVEL] int null,
	[MEDI_VIRGIN_PARENT_LEVEL] int null,
	[MEDI_DEPT_USE_DEF_CARRIER] int Null,
	[MEDI_CTL_NUMBER] [varchar](50) Null,
	[MEDI_CARRIER_ORG_LEVEL] int null,
	[MEDI_JURIS_ROW_ID] int null,
	[MEDI_CARRIER_EID] int null,
	[MEDI_PRIN_PROC_CODE] [varchar](25) null,
	[MEDI_PRNCPL_PROC_DATE] [varchar](8) null,
	[BSRCODE] varchar (50) null,
	[MEDI_BILLING_FORMAT_CODE] [Varchar](25) null,
	[MEDI_CONTRACT_TYPE_CODE][Varchar](25) null,
	[MEDI_NDC_PAID_CODE][Varchar](25) null,
	[MEDI_JURIS_PROC_BLD_CODE][Varchar](25) null,
	[MEDI_JURIS_PROC_PD_CDE][Varchar](25) null,
	[MEDI_BILL_ADJ_GRP_CODE][Varchar](25) null,
	[MEDI_DAYS_UNITS_CODE][Varchar](25) null,
	[MEDI_DISPENSE_WRITTEN_CODE][Varchar](25) null,
	[MEDI_ADMISSION_TYPE_CODE][Varchar](5) null,
	[MEDI_OUTPATIENT_VISIT_CODE][Varchar](5) null,
	[MEDI_CERT_NUMBER][Varchar](64) null,        --Added for florida MED 
[MEDI_CODELICENSE_NUMBER][Varchar](64) null, --Added for florida MED 


	CONSTRAINT [PK_EDI_MEDICAL_EXTRACT] PRIMARY KEY CLUSTERED
	(
		[DA_ROW_ID] ASC,
		[JOBID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY] 
	

END
	
	
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_ENTITY]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_ENTITY]
BEGIN

CREATE TABLE [dbo].[EDI_MEDICAL_ENTITY](
	[JOBID] [int] NOT NULL,
	[DA_ROW_ID][int] NOT NULL,
	[ENTITY_ID] [int] NOT NULL,
	[ABBREVIATION] [varchar](25) NULL,
	[ADDR1] [varchar](100) NULL,
	[ADDR2] [varchar](100) NULL,
	[ALSO_KNOWN_AS] [varchar](50) NULL,
	[BUSINESS_TYPE_CODE] [int] NULL,
	[CITY] [varchar](50) NULL,
	[COMMENTS] [varchar](4000) NULL,
	[CONTACT] [varchar](50) NULL,
	[COUNTRY_SCODE] [varchar](25) NULL,
	[COUNTY] [varchar](30) NULL,
	[NATURE_OF_BUSINESS] [varchar](50) NULL,
	[ORGANIZATION_TYPE] [int] NULL,
	[SIC_CODE] [int] NULL,
	[SIC_CODE_DESC] [varchar](150) NULL,
	[NAICS_CODE] [int] NULL,
	[ENTITY_TABLE_ID] [int] NULL,
	[LAST_NAME] [varchar](255) NULL,
	[FIRST_NAME] [varchar](255) NULL,
	[STATE_ID] [int] NULL,
	[ZIP_CODE] [varchar](10) NULL,
	[PARENT_EID] [int] NULL,
	[TAX_ID] [varchar](20) NULL,
	[EMAIL_TYPE_CODE] [int] NULL,
	[EMAIL_ADDRESS] [varchar](100) NULL,
	[SEX_CODE] [int] NULL,
	[BIRTH_DATE] [varchar](8) NULL,
	[PHONE1] [varchar](30) NULL,
	[PHONE2] [varchar](30) NULL,
	[FAX_NUMBER] [varchar](30) NULL,
	[DTTM_RCD_ADDED] [varchar](14) NULL,
	[DTTM_RCD_LAST_UPD] [varchar](14) NULL,
	[UPDATED_BY_USER] [varchar](50) NULL,
	[ADDED_BY_USER] [varchar](50) NULL,
	[DELETED_FLAG] [int] NULL,
	[EFF_START_DATE] [varchar](8) NULL,
	[EFF_END_DATE] [varchar](8) NULL,
	[TRIGGER_DATE_FIELD] [varchar](50) NULL,
	[RM_USER_ID] [int] NULL,
	[MIDDLE_NAME] [varchar](255) NULL,
	[TITLE] [varchar](50) NULL,
	[NPI_NUMBER] [varchar](10) NULL,
CONSTRAINT [PK_EDI_MEDICAL_ENTITY] PRIMARY KEY CLUSTERED
	(
		[DA_ROW_ID] ASC,
		[JOBID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY] 
	

END

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_CODES]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_CODES]
BEGIN

CREATE TABLE [dbo].[EDI_MEDICAL_CODES](
	[JOBID] [int] NOT NULL,
	[DA_ROW_ID][int] NOT NULL,
	[MEDI_DIAG_CODE_ELMNT_NAME][varchar](6)NULL,
	[MEDI_DIAG_SHORT_CODE][varchar](25)NULL,
	[MEDI_COLUMN_NAME][varchar](25) NULL,
	[MEDI_PROCEDRE_DATE][varchar](8) NULL,
	[MEDI_ADJSTMNT_AMT][DECIMAL](20,2) NULL,
	[MEDI_ADJSTMNT_UNIT][int] NULL,
	CONSTRAINT [PK_EDI_MEDICAL_CODES] PRIMARY KEY CLUSTERED
	(
		[DA_ROW_ID] ASC,
		[JOBID] ASC
	)
	
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY] 
	

END

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_ADJUSTMENT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_ADJUSTMENT]
BEGIN

CREATE TABLE [dbo].[EDI_MEDICAL_ADJUSTMENT](
	[JOBID] [int] NOT NULL,
	[DA_ROW_ID][int] NOT NULL,
	[MEDI_ADJST_GRP_CODE][varchar](25) NULL,
	[MEDI_ADJST_RSN_CODE][varchar](25) NULL,
	[MEDI_ADJST_AMT][decimal](10,2) NULL,
	[MEDI_ADJST_UNIT][decimal](10,2) NULL,
	[MEDI_SERVICE_OR_BILL][varchar](10) NULL,
	CONSTRAINT [PK_EDI_MEDICAL_ADJUSTMENT] PRIMARY KEY CLUSTERED
	(
		[DA_ROW_ID] ASC,
		[JOBID] ASC
	)
	
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY] 
	

END
	
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[ERROR_LOG]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[ERROR_LOG]
BEGIN
	CREATE TABLE [dbo].[ERROR_LOG] (
		[ERR_LOG_ROW_ID] [int] NOT NULL,
		[JOBID] [int] NOT NULL,
		[INPUT_ROW_ID] [int] NULL,
		[MODULE_NAME] [varchar](50) NULL,
		[WORK_FLOW_NAME] [varchar](50) NULL,
		[DATA_FLOW_NAME] [varchar](50) NULL,
		[ERROR_TIME] [varchar](14) NULL,
		[ERROR_TITLE] [varchar](100) NULL,
		[ERROR_DESC] [varchar](4000) NULL,
		[IS_VALIDATION] [int] NULL,
		[ERROR_TABLE] [varchar](50) NULL,
		[TABLE_ROW_ID] [int] NULL,
		[ERROR_COLUMNS] [varchar](4000) NULL,
	 CONSTRAINT [PK_ERROR_LOG] PRIMARY KEY CLUSTERED
	(
		[ERR_LOG_ROW_ID] ASC,
		[JOBID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[PROCESS_LOG]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[PROCESS_LOG]
BEGIN

CREATE TABLE [DBO].[PROCESS_LOG](
[DA_ROW_ID] [int]  NULL,
[JOBID] [int] NOT NULL,
		[PROCESS_DESC] [varchar](500) NULL,
        [DISPLAY_ORDER] [int]  NULL,
        [TRANS_ID] [int]  NULL,
        [IDENTIFIER] [int] NULL,
		[CLAIM_NUMBER] VARCHAR(25)  NULL , 
[ERROR_RECORDS] VARCHAR(500)  NULL,
[RULE_FAILED]VARCHAR(255)  NULL,


)

END


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_EXPORT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_EXPORT]
BEGIN

CREATE TABLE [dbo].[EDI_MEDICAL_EXPORT](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[INVALID_ROW] [int] NULL,
	[TRANS_ID][int] NULL,
	[MEDI_CTL_NUMBER] [varchar](50) Null,
	[MEDI_CLAIM_ADMIN_EID] [int] NULL,
	[MEDI_INSURER_EID][int] NULL,
	[JURIS_STATE_ID][varchar](25) NULL,
	[DN0615_TO_REPORT_PERIOD] [VARCHAR](8)  NULL,
	[DN0615_FROM_REPORT_PERIOD] [VARCHAR](8)  NULL,
	[DN0532_ORIGIN_TRANS_ID_NUM][varchar](50) NULL,
	[DN0100_DATE_TRNSMSSN_SENT][varchar](8) NULL,
	[DN0101_TIME_TRNSMSSN_SENT][varchar](6) NULL,
	[DN0098_SENDER_ID][varchar](25) NULL,
	[DN0099_RECEIVER_ID][varchar](25) NULL,
	[DN0007_INSURER_NAME][varchar](255) NULL,
	[DN0006_INSURER_FEIN][varchar](9) NULL,
	[DN0616_INSURER_POST_CODE][varchar](10) NULL,
	[DN0188_CLAIM_ADMIN_NAME][varchar](255) NULL,
	[DN0187_CLAIM_ADMIN_FEIN][varchar](9) NULL,
	[DN0014_CLAIM_ADMIN_POST_CODE][varchar](10) NULL,
	[DN0018_EMPLOYER_NAME][varchar](255) NULL,
	[DN0016_EMPLOYER_FEIN][varchar](9) NULL,
	[DN0031_DATE_OF_INJURY][varchar](8) NULL,
	[DN0043_EMPLOYEE_LAST_NAME] [varchar](255) NULL,
	[DN0044_EMPLOYEE_FIRST_NAME] [varchar](255) NULL,
	[DN0045_EMPLOYEE_MIDDLE_Name] [varchar](255) NULL,
	[DN0255_EMPLAST_NAME_SUFFIX][varchar](4) NULL,
	[DN0042_EMPLOYEE_SSN][varchar](9) NULL,
	[DN0153_EMPLOYEE_GREEN_CARD] [varchar](15) NULL,
	[DN0154_EMPID_ASSIGNEDBY_JURIS] [varchar](15) NULL,
	[DN0156_EMPLOYEE_PASSPORT_NUM] [varchar](15) NULL,
	[DN0152_EMPLOYEEE_VISA] [varchar](15) NULL,
	[DN0046_EMPLOYEE_MAIL_PRIMADD] [varchar](255) NULL,
	[DN0047_EMPLOYEE_MAIL_SECADD] [varchar](255) NULL,
	[DN0048_EMPLOYEE_MAIL_CITY] [varchar](100) NULL,
	[DN0049_EMPLOYEE_MAIL_STATECODE] [varchar](25) NULL,
	[DN0050_EMPLOYEE_MAIL_POSTCODE] [varchar](10) NULL,
	[DN0155_EMPLOYEE_MAIL_COUNTRY] [varchar](25) NULL,
	[DN0052_EMPLOYEE_DOB] [varchar](8) NULL,
	[DN0053_EMPLOYEE_GENDER] [varchar](3) NULL,
	[DN0015_CLAIM_ADMIN_CLAM_NUM] [varchar](50) NULL,
	[DN0005_JURIS_CLAM_NUM] [varchar](50) NULL,
	[DN0051_EMPLOYEE_PHONE_NUM] [varchar](30) NULL,
	[DN0523_BILL_PRO_UNI_ID_NUM][varchar](38) NULL,
	[DN0501_TOT_CHARGE_BILL][decimal](10,2) NULL,
	[DN0502_BILL_TYPE_CODE] [varchar](25) NULL,
	[DN0504_FACLITY_CODE] [varchar](25) NULL,
	[DN0555_PLCE_OF_SRVC_BILL_CODE][varchar](25) NULL,
	[DN0503_BILL_FORMAT_CODE][varchar](25)NULL,
	[DN0505_BILL_FREQ_TPE_SHRT_CODE][varchar](25)NULL,
	[DN0507_PROV_AGRMNT_SHRT_CODE][varchar](25)NULL,
	[DN0508_BILL_SUB_RSN_SHRT_CODE][varchar](25)NULL,
	[DN0511_DATE_INSRER_RCVD_BILL][varchar](8) NULL,
	[DN0513_ADMISN_DATE][varchar](12) NULL,
	[DN0622_ADMISN_HOUR][varchar](12) NULL,
	[DN0514_DSCHRGE_DATE][varchar](8) NULL,
	[DN0623_DSCHRGE_HOUR][varchar](12) NULL,
	[DN0509_SRVC_BILL_DATETO][varchar](17) NULL,
	[DN0509_SRVC_BILL_DATEFROM][varchar](17) NULL,
	[DN0527_PRSCRPTN_DATETO][varchar](17) NULL,
	[DN0527_PRSCRPTN_DATEFROM][varchar](17) NULL,
	[DN0510_DATE_OF_BILL][varchar](8) NULL,
	[DN0512_DATE_INSRD_PAID_BILL][varchar](8) NULL,
	[DN0577_ADMSSN_TYPE_CODE][varchar](25) NULL,
	[DN0515_CONTRCT_TYPE_CODE] [varchar](25) NULL,
	[DN0516_TOT_AMT_PAID_PR_BILL][decimal](10,2) NULL,
	[DN0500_UNIQ_BILL_ID_NUM][varchar](50) NULL,
	[DN0266_TRANS_TRACK_NUM][varchar](50)NULL,
	[DN0581_TRTMNT_AUTHOR_NUM][varchar](50) NULL,
	[DN0293_LMPSM_PYMNT_CODE][varchar](25)NULL,
	[DN0521_PRNCPL_DIG_CODE][varchar](25)NULL,
	[DN0533_01_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0535_ADMTNG_DIAG_CODE][varchar](25)NULL,
	[DN0522_01_DIAG_CODE][varchar](25)NULL,
	[DN0522_02_DIAG_CODE][varchar](25)NULL,
	[DN0533_02_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0522_03_DIAG_CODE][varchar](25)NULL,
	[DN0533_03_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0522_04_DIAG_CODE][varchar](25)NULL,
	[DN0533_04_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0522_05_DIAG_CODE][varchar](25)NULL,
	[DN0533_05_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0522_06_DIAG_CODE][varchar](25)NULL,
	[DN0533_06_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0522_07_DIAG_CODE][varchar](25)NULL,
	[DN0533_07_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0522_08_DIAG_CODE][varchar](25)NULL,
	[DN0533_08_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0522_09_DIAG_CODE][varchar](25)NULL,
	[DN0533_09_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0522_10_DIAG_CODE][varchar](25)NULL,
	[DN0533_10_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0522_11_DIAG_CODE][varchar](25)NULL,
	[DN0533_11_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0522_12_DIAG_CODE][varchar](25)NULL,
	[DN0533_12_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0533_13_PRSNT_ADMSN_INDC][varchar](2)NULL,
	[DN0520_OUT_RSN_CODE][varchar](25) NULL,
	[DN0520_1_OUT_RSN_CODE][varchar](25) NULL,
	[DN0520_2_OUT_RSN_CODE][varchar](25) NULL,
	[DN0521_PRNCPL_DIG_CODE1][varchar](25)NULL,
	[DN0522_02_DIAG_CODE2][varchar](30)NULL,
	[DN0522_03_DIAG_CODE3][varchar](30)NULL,
	[DN0522_04_DIAG_CODE4][varchar](30)NULL,
	[DN0522_05_DIAG_CODE5][varchar](30)NULL,
	[DN0522_06_DIAG_CODE6][varchar](30)NULL,
	[DN0522_07_DIAG_CODE7][varchar](30)NULL,
	[DN0522_08_DIAG_CODE8][varchar](30)NULL,
	[DN0522_09_DIAG_CODE9][varchar](30)NULL,
	[DN0522_10_DIAG_CODE10][varchar](30)NULL,
	[DN0522_11_DIAG_CODE11][varchar](30)NULL,
	[DN0522_12_DIAG_CODE12][varchar](30)NULL,
	[DN0525_PRNCPL_PROC_CODE][varchar](25) NULL,
	[DN0550_PRNCPL_PROC_DATE][varchar](8) NULL,
	[DN0736_01_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_01_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_02_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_02_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_03_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_03_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_04_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_04_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_05_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_05_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_06_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_06_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_07_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_07_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_08_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_08_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_09_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_09_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_10_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_10_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_11_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_11_OT_PROC_DATE][varchar](8) NULL,
	[DN0736_12_OT_PROC_CODE][varchar](25) NULL,
	[DN0524_12_OT_PROC_DATE][varchar](8) NULL,
	[DN0556_1_CONDITION_CODE][varchar](25) NULL,
	[DN0556_2_CONDITION_CODE][varchar](25) NULL,
	[DN0556_3_CONDITION_CODE][varchar](25) NULL,
	[DN0556_4_CONDITION_CODE][varchar](25) NULL,
	[DN0556_5_CONDITION_CODE][varchar](25) NULL,
	[DN0556_6_CONDITION_CODE][varchar](25) NULL,
	[DN0556_7_CONDITION_CODE][varchar](25) NULL,
	[DN0556_8_CONDITION_CODE][varchar](25) NULL,
	[DN0556_9_CONDITION_CODE][varchar](25) NULL,
	[DN0556_10_CONDITION_CODE][varchar](25) NULL,
	[DN0556_11_CONDITION_CODE][varchar](25) NULL,
	[DN0556_12_CONDITION_CODE][varchar](25) NULL,
	[DN0549_PAID_DRG_CODE][varchar](25) NULL,
	[DN0548_BILD_DRG_CODE][varchar](25) NULL,
	[DN0528_BILLING_LAST_NAME] [varchar](255) NULL,
	[DN0529_BILLING_FIRST_NAME] [varchar](255) NULL,
	[DN0530_BILLING_MIDDLE_Name] [varchar](255) NULL,
	[DN0531_BILLING_NAME_SUFFIX][varchar](4) NULL,
	[DN0634_BILLING_NPI][varchar](10) NULL,
	[DN0537_BIL_PRV_PRM_SPL_CODE][varchar](25) NULL,
	[DN0538_BILLING_MAIL_PRIMADD] [varchar](100) NULL,
	[DN0539_BILLING_MAIL_SECADD] [varchar](100) NULL,
	[DN0540_BILLING_MAIL_CITY] [varchar](100) NULL,
	[DN0541_BILLING_MAIL_STATECODE] [varchar](25) NULL,
	[DN0542_BILLING_MAIL_POSTCODE] [varchar](25) NULL,
	[DN0569_BILLING_MAIL_COUNTRY] [varchar](25) NULL,
	[DN0629_BILLING_SSN][varchar](20) NULL,
	[DN0630_BIL_PRV_STE_LIC_NUM][varchar](50) NULL,
	[DN0638_RENDER_LAST_NAME] [varchar](255) NULL,
	[DN0639_RENDER_FIRST_NAME] [varchar](255) NULL,
	[DN0640_RENDER_MIDDLE_Name] [varchar](255) NULL,
	[DN0641_RENDER_NAME_SUFFIX][varchar](4) NULL,
	[DN0647_RENDER_NPI][varchar](10) NULL,
	[DN0651_RENDER_PRV_PRM_SPL_CODE][varchar](25) NULL,
	[DN0642_RENDER_SSN][varchar](9) NULL,
	[DN0643_RENDER_PRV_STE_LIC_NUM][varchar](50) NULL,
	[DN0658_SUPERV_LAST_NAME] [varchar](255) NULL,
	[DN0659_SUPERV_FIRST_NAME] [varchar](255) NULL,
	[DN0660_SUPERV_MIDDLE_Name] [varchar](255) NULL,
	[DN0661_SUPERV_NAME_SUFFIX][varchar](4) NULL,
	[DN0667_SUPERV_NPI][varchar](10) NULL,
	[DN0671_SUPERV_PRV_PRM_SPL_CODE][varchar](25) NULL,
	[DN0663_SUPERV_PRV_STE_LIC_NUM][varchar](50) NULL,
	[DN0678_FACILITY_LAST_NAME] [varchar](255) NULL,
	[DN0682_FACILITY_NPI][varchar](30) NULL,
	[DN0684_FACILITY_MAIL_PRIMADD] [varchar](255) NULL,
	[DN0685_FACILITY_MAIL_SECADD] [varchar](255) NULL,
	[DN0686_FACILITY_MAIL_CITY] [varchar](50) NULL,
	[DN0687_FACILITY_MAIL_STATECODE] [varchar](25) NULL,
	[DN0688_FACILITY_MAIL_POSTCODE] [varchar](10) NULL,
	[DN0689_FACILITY_MAIL_COUNTRY] [varchar](25) NULL,
	[DN0680_FAC_PRV_STE_LIC_NUM][varchar](50) NULL,
	[DN0683_FACILITY_SRVC_LOC_ID][varchar](50)NULL,
	[DN0690_REFER_LAST_NAME] [varchar](255) NULL,
	[DN0691_REFER_FIRST_NAME] [varchar](255) NULL,
	[DN0692_REFER_MIDDLE_Name] [varchar](255) NULL,
	[DN0693_REFER_NAME_SUFFIX][varchar](4) NULL,
	[DN0699_REFER_NPI][varchar](10) NULL,
	[DN0695_REFER_PRV_STE_LIC_NUM][varchar](50) NULL,
	[DN0209_MCO_NAME][varchar](255) NULL,
	[DN0704_MCO_SSN][varchar](9) NULL,
	[DN0208_MCO_IDNUM][int] NULL,
	[DN0543_01_BL_ADJ_GRP_CODE][varchar](25) NULL,
	[DN0544_01_BL_ADJ_RSN_CODE][varchar](25) NULL,
	[DN0545_01_BL_ADJ_AMT][decimal](10,2) NULL,
	[DN0546_01_BL_ADJ_UNITS][varchar](15) NULL,
	[DN0544_02_BL_ADJ_RSN_CODE][varchar](25) NULL,
	[DN0545_02_BL_ADJ_AMT][decimal](10,2) NULL,
	[DN0546_02_BL_ADJ_UNITS][varchar](15) NULL,
	[DN0544_03_BL_ADJ_RSN_CODE][varchar](25) NULL,
	[DN0545_03_BL_ADJ_AMT][decimal](10,2) NULL,
	[DN0546_03_BL_ADJ_UNITS][varchar](15) NULL,
	[DN0760_PRIOR_ACT_AMT_PAID][decimal](10,2) NULL,
	[DN0547_01_LINE_NUM][varchar](50) NULL,
	[DN0714_HCPCS_LN_PROCBLD_CDE][varchar](25) NULL,
	[DN0715_JURIS_PROC_BLD_CODE][varchar](25) NULL,
	[DN0721_NDC_BLD_CODE][varchar](25) NULL,
	[DN0551_01_PROC_DESC][varchar](80) NULL,
	[DN0552_01_TOT_CHARGE_PER_LINE][decimal](10,2) NULL,
	[DN0553_01_DAY_PER_UNT_CODE][varchar](25) NULL,
	[DN0554_01_DAY_PER_UNT_BLD][varchar](2) NULL,
	[DN0600_01_PLC_OF_SRVC_LNE_CODE][varchar](25) NULL,
	[DN0557_01_DIAGNOSIS_PTR][varchar](1) NULL,
	[DN0557_02_DIAGNOSIS_PTR][varchar](1) NULL,
	[DN0557_03_DIAGNOSIS_PTR][varchar](1) NULL,
	[DN0557_04_DIAGNOSIS_PTR][varchar](1) NULL,
	[DN0742_PRV_AGRMNT_LINE_CODE][varchar](25) NULL,
	[DN0559_REV_BLD_CODE][varchar](25) NULL,
	[DN0714_1_HCPCS_LN_PROCBLD_CDE][varchar](25) NULL,
	[DN0715_1_JURIS_PROC_BLD_CODE][varchar](25) NULL,
	[DN0625_HIPPS_CODE][varchar](25) NULL,
	[DN0551_02_PROC_DESC][varchar](80) NULL,
	[DN0552_02_TOT_CHARGE_PER_LINE][decimal](10,2) NULL,
	[DN0553_02_DAY_PER_UNT_CODE][varchar](25) NULL,
	[DN0554_02_DAY_PER_UNT_BLD][varchar](2) NULL,
	[DN0719_ADA_PROC_BLD_CDE][varchar](25) NULL,
	[DN0714_2_HCPCS_LN_PROCBLD_CDE][varchar](25) NULL,
	[DN0551_03_PROC_DESC][varchar](80) NULL,
	[DN0552_03_TOT_CHARGE_PER_LINE][decimal](10,2) NULL,
	[DN0600_02_PLC_OF_SRVC_LNE_CODE][varchar](25) NULL,
	[DN0557_05_DIAGNOSIS_PTR][varchar](1) NULL,
	[DN0557_06_DIAGNOSIS_PTR][varchar](1) NULL,
	[DN0557_07_DIAGNOSIS_PTR][varchar](1) NULL,
	[DN0557_08_DIAGNOSIS_PTR][varchar](1) NULL,
	[DN0561_01_PRSCRPTN_LINE_NUM][varchar](50) NULL,
	[DN0714_3_HCPCS_LN_PROCBLD_CDE][varchar](25) NULL,
	[DN0715_2_JURIS_PROC_BLD_CODE][varchar](25) NULL,
	[DN0721_01_NDC_BLD_CODE][varchar](25) NULL,
	[DN0562_DSPNS_AS_WRTN_CODE][varchar](25) NULL,
	[DN0563_DRUG_NAME][varchar](80) NULL,
	[DN0762_CMP_DRG_INDI][varchar](2) NULL,
	[DN0605_SRVC_LINE_DATETO][varchar](17) NULL,
	[DN0605_SRVC_LINE_DATEFROM][varchar](17) NULL,
	[DN0604_PRCRPTN_LINE_DATE][varchar](8) NULL,
	[DN0570_DRG_SUPP_DISP][varchar](15) NULL,
	[DN0571_DRG_SUPP_NO_DAYS][varchar](15) NULL,
	[DN0741_CNTRCT_TYPE_CODE][varchar](25) NULL,
	[DN0738_TRMNT_LINE_AUTHOR_NUM][varchar](50) NULL,
	[DN0579_DRG_SUPP_DIS_FEE][varchar](15) NULL,
	[DN0572_DRG_SUPP_BLD_AMT][decimal](10,2) NULL,
	[DN0627_LINE_ITM_TAX_CHRG_AMT][decimal](10,2) NULL,
	[DN0721_02_NDC_BLD_CODE][varchar](25) NULL,
	[DN0721_03_NDC_BLD_CODE][varchar](25) NULL,
	[DN0553_03_DAY_PER_UNT_CODE][varchar](25) NULL,
	[DN0561_02_PRSCRPTN_LINE_NUM][varchar](50) NULL,
	[DN0589_RENDERL_LAST_NAME] [varchar](255) NULL,
	[DN0587_RENDERL_FIRST_NAME] [varchar](255) NULL,
	[DN0591_RENDERL_MIDDLE_Name] [varchar](255) NULL,
	[DN0588_RENDERL_NAME_SUFFIX][varchar](4) NULL,
	[DN0592_RENDERL_NPI][varchar](10) NULL,
	[DN0595_RENDERLPRV_PRM_SPL_CODE][varchar](25) NULL,
	[DN0586_RENDERL_SSN][varchar](9) NULL,
	[DN0599_RENDERL_PRV_STE_LIC_NUM][varchar](50) NULL,
	[DN0574_TOT_AMT_PAID_PRLINE][decimal](10,2) NULL,
	[DN0722_ADA_PROC_PD_CDE][varchar](25) NULL,
	[DN0726_HCPCS_LN_PROCPD_CDE][varchar](25) NULL,
	[DN0727_HCPCS_MOD_CODE][varchar](25) NULL,
	[DN0728_NDC_PAID_CODE][varchar](25) NULL,
	[DN0729_JURIS_PROC_PD_CDE][varchar](25) NULL,
	[DN0727_01_HCPCS_MOD_CODE][varchar](25) NULL,
	[DN0730_01_JURIS_MOD_CODE][varchar](25) NULL,
	[DN0727_02_HCPCS_MOD_CODE][varchar](25) NULL,
	[DN0730_02_JURIS_MOD_CODE][varchar](25) NULL,
	[DN0727_03_HCPCS_MOD_CODE][varchar](25) NULL,
	[DN0730_03_JURIS_MOD_CODE][varchar](25) NULL,
	[DN0727_04_HCPCS_MOD_CODE][varchar](25) NULL,
	[DN0730_04_JURIS_MOD_CODE][varchar](25) NULL,
	[DN0576_RVN_PAID_CODE][varchar](25) NULL,
	[DN0580_DAY_PER_UNT_PAID][varchar](2) NULL,
	[DN0547_02_LINE_NUM][varchar](50) NULL,
	[DN0731_01_SVC_ADJ_GRP_CODE][varchar](25) NULL,
	[DN0732_01_SVC_ADJ_RSN_CODE][varchar](25) NULL,
	[DN0733_01_SVC_ADJ_AMT][decimal](10,2) NULL,
	[DN0734_01_SVC_ADJ_UNITS][varchar](15) NULL,
	[DN0732_02_SVC_ADJ_RSN_CODE][varchar](25) NULL,
	[DN0733_02_SVC_ADJ_AMT][decimal](10,2) NULL,
	[DN0734_02_SVC_ADJ_UNITS][varchar](15) NULL,
	[DN0732_03_SVC_ADJ_RSN_CODE][varchar](25) NULL,
	[DN0733_03_SVC_ADJ_AMT][decimal](10,2) NULL,
	[DN0734_03_SVC_ADJ_UNITS][varchar](15) NULL,
	[DN0732_04_SVC_ADJ_RSN_CODE][varchar](25) NULL,
	[DN0733_04_SVC_ADJ_AMT][decimal](10,2) NULL,
	[DN0734_04_SVC_ADJ_UNITS][varchar](15) NULL,
	[DN0732_05_SVC_ADJ_RSN_CODE][varchar](25) NULL,
	[DN0733_05_SVC_ADJ_AMT][decimal](10,2) NULL,
	[DN0734_05_SVC_ADJ_UNITS][varchar](15) NULL,
	[DN0761_LINE_ITM_PRIOR_ACT_AMT][decimal](10,2) NULL,
	[DN0628_LINE_ITM_TAX_PAID_AMT][decimal](10,2) NULL,
	[DN0717_HCPCS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0717_01_HCPCS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0717_02_HCPCS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0717_03_HCPCS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0717_04_HCPCS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0717_05_HCPCS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0717_06_HCPCS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0717_07_HCPCS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0718_JURIS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0718_01_JURIS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0718_02_JURIS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0718_03_JURIS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0718_04_JURIS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0718_05_JURIS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0718_06_JURIS_MOD_BLD_CODE][varchar](15) NULL,
	[DN0718_07_JURIS_MOD_BLD_CODE][varchar](15) NULL,
[MEDI_EMPLOYEE_EID][INT] NULL,
[MEDI_EMPLOYER_EID][INT]NULL,	
[ENTITY_TYP_QULFR_INS][INT]NULL,
[ENTITY_TYP_QULFR_EMP][INT]NULL,
[DN0019_Empr_Phys_PrimAddr][VARCHAR](255)NULL, --MKAUR24 START
[DN0020_Empr_Phys_SecAddr][VARCHAR](255)NULL, 
[DN0021_Empr_Phys_City][VARCHAR](100)NULL, 
[DN0022_Empr_Phys_State_Code][VARCHAR](100)NULL, 
 [DN0023_Empr_Phys_Pstl_Code][VARCHAR](100)NULL, 
  [DN0164_Empr_Phys_Cntry_Code][VARCHAR](100)NULL,
  [ENTITY_TYP_QULFR_BILLP][INT]NULL,
[MEDI_CERT_NUMBER][Varchar](64) null,        --Added for florida MED 
[MEDI_CODELICENSE_NUMBER][Varchar](64) null, --Added for florida MED 
[MEDI_CLAIMADMIN_TPA_EID] [INT]NULL,	--Added for florida MED 
[FEDI_REISSUE_REASON_CODE][VARCHAR](25)NULL, --Added for florida MED
[FEDI_TPA_LICNENSE_CODE] [VARCHAR](9)NULL, --Added for florida MED
[FEDI_REPORT_TYPE_CODE][VARCHAR](25)NULL, --Added for florida MED
[FL_FORCE_MB_RE] [INT]NULL,	--Added for florida MED 
[PHY_EID_INV_DET] [int] NULL, --Added for florida MED 
[FL_LICENSE][varchar](25) NULL, --Added for florida MED 
[ZIP_CODE_INV_DET][varchar](10) NULL, --Added for florida MED 
[FEDI_PHY_TAX_ID][varchar](9) NULL, --Added for florida MED 
[FEDI_PHY_NAME][varchar](512) NULL, --Added for florida MED 
[JURIS_LIC_CODE_PHY][varchar](64) NULL, --Added for florida MED
[FL_OPER_PHYS_EID][int] NULL, --Added for florida MED
[MEDI_EVENT_ID] [int] NULL, --Added for florida MED
 [FEDI_DATE_OF_EVENT][varchar](8) NULL, --Added for florida MED
 --[FL_OPR_LIC_NUM][varchar](20) NULL, --Added for florida MED
 [FL_OP_PHY_LIC_TEXT][varchar](64) NULL, --Added for florida MED
 [FL_ADMISSN_DATE][varchar](8) NULL, --Added for florida MED
 [StatmentCoversFrom][varchar](8) NULL, --Added for florida MED
[StatementCoversThough][varchar](8) NULL, --Added for florida MED
[FL_AD_HOUR][int] NULL, --Added for florida MED
[FL_DC_HOUR][int] NULL, --Added for florida MED
[FACILITY_TAX_ID] [varchar](20) NULL, --Added for florida MED
[DATE_OF_CHECK][varchar](8) NULL, --Added for florida MED
[FL_RCVD_BILL][varchar](8) NULL, --Added for florida MED
[FUNDS_AMOUNT] decimal (10,2) NULL, --Added for florida MED
[FL_CAUSE_1][varchar](25) NULL, --Added for florida MED
[FL_CAUSE_2][varchar](25) NULL, --Added for florida MED
[FL_CAUSE_3][varchar](25) NULL, --Added for florida MED
[FL_RPT_REAS][varchar](25) NULL, --Added for florida MED
[FL_PRE_PMT][varchar](25) NULL, --Added for florida MED
[FL_ADMIT_TYPE][varchar](25) NULL, --Added for florida MED
[FL_PAYTCODE_CODE][varchar](25) NULL, --Added for florida MED
[MEDI_CLAIM_ID][varchar](25) NULL, --Added for florida MED
[FL_SUB_LOC][varchar](25) NULL, --Added for florida MED
[FL_ICD_TYPE_INDICATOR][varchar](25) NULL, --Added for florida MED
[PT_SERVICE_DATE][varchar](8) NULL, --Added for florida MED
[MEDICAL_CHARGE]decimal (10,2) NULL, --Added for florida MED
[PHARMACY_CHARGE]decimal (10,2) NULL, --Added for florida MED
[FL_PAY_PLAN] [varchar](25) NULL, --Added for florida MED
[FL_DUP_IND][varchar](25) NULL, --Added for florida MED
[FL_SCHEDULED_IND][varchar](25) NULL, --Added for florida MED
[FL_IMPLANT_TOTAL][varchar](25) NULL, --Added for florida MED
[FL_FAC_LIC_TEXT][varchar](13) NULL, --Added for florida MED
[FL_FAC_NPI_TEXT][varchar](10) NULL, --Added for florida MED
[FAC_LAST_NAME_TEXT][varchar](255) NULL, --Added for florida MED
[RESUBMISSION_CODE][varchar](11) NULL, --Added for florida MED
[PLACE_OF_SER_CODE][varchar](25) NULL, --Added for florida MED
[FL_PRIMARY_DIAG][varchar](25) NULL, --Added for florida MED
[CODE_NUMBER][varchar](10) NULL, --Added for florida MED
PRIMARY KEY CLUSTERED 
(
	[JOBID] ASC,
	[DA_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

end




IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_PAYMENT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_PAYMENT]
BEGIN

CREATE TABLE [DBO].[EDI_MEDICAL_PAYMENT](
[DA_ROW_ID] [INT]  NOT NULL , 
[JOBID] [INT]   NOT NULL , 
[CLAIM_ID] [INT]  NULL , 
[DN0523_BILL_PRO_UNI_BILL_ID_NUM][int] NULL,
[DN0501_TOT_CHARGE_BILL][decimal](10,2) NULL,
[DN0509_SRVC_BILL_DATE_RNGE][varchar](17) NULL,
[DN0510_DATE_OF_BILL][varchar](8) NULL,
[DN0512_DATE_INSRD_PAID_BILL][varchar](8) NULL,
[DN0516_TOT_AMT_PAID_PR_BILL][varchar](18) NULL,
[DN0266_TRANS_TRACK_NUM][varchar](50)NULL,
[DN0552_01_TOT_CHARGE_PER_LINE][varchar](18) NULL,
[DN0553_01_DAY_PER_UNT_CODE][varchar](25) NULL,
[DN0554_01_DAY_PER_UNT_BLD][varchar](2) NULL,
[DN0600_01_PLC_OF_SRVC_LNE_CODE][varchar](25) NULL,
[CONCATENATED_STRING][VARCHAR](4096)  NULL,
)


END


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_JURIS_STATES]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_JURIS_STATES]
BEGIN
CREATE TABLE [dbo].[EDI_MEDICAL_JURIS_STATES](
	[JOBID] [int] NOT NULL,
	[DN0004_JURISDICTION_CODE] [varchar](25) NOT NULL,
	[ROW_NUM] [int] NULL,
	[DA_ROW_ID] [int] NOT NULL,

)
END


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_ERROR_LOG]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_ERROR_LOG]
BEGIN
CREATE TABLE [DBO].[EDI_MEDICAL_ERROR_LOG](
[RULE_NAME] VARCHAR(20)  NULL , 
[JURISDICTION] VARCHAR(10)  NULL , 
[ERROR_MESSAGE] VARCHAR(500)  NULL,
[ERROR_TABLE] VARCHAR(30) NULL)
END

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_FTS_INVDET]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_FTS_INVDET]
BEGIN
CREATE TABLE [dbo].[EDI_MEDICAL_FTS_INVDET](
	[TRANS_ID] [int] NULL,
	[AMOUNT] [float] NULL,
	[BILL_RCVD_DATE] [varchar](8) NULL,
	[MEDI_BILL_ADJ_CODE] [varchar](25) NULL,
	[INVOICE_ID] [int] NULL,
	[FUNDS_SPLIT_ROW_ID] [int] NULL,
	[MEDI_FACLITY_TYPE_CODE] [varchar](25) NULL,
	[MEDI_PLCE_OF_SRVC_BILL_CODE] [varchar](25) NULL,
	[MEDI_BILL_FORMAT_CODE] [varchar](25) NULL,
	[MEDI_BILL_FREQ_TYPE_CODE] [varchar](25) NULL,
	[TYPE_OF_SER_CODE] [varchar](25) NULL,
	[BILLING_CODE_TEXT] [varchar](64) NULL,
	[UNITS_BILLED_NUM] [decimal](10,2) NULL,
	[MEDI_TOT_CHARGE_BILL] [decimal](10,2) NULL,
	[AMOUNT_TO_PAY] [decimal](10,2) NULL,
	[DRUG_NAME] [varchar](80) NULL,
	[PRESCRIP_DATE] [varchar](8) NULL,
	[HCPCS_CODE] [varchar](5) NULL,
	[MEDI_BILL_TYPE_CODE] [varchar](25) NULL,
	[FROM_DATE] [varchar](8) NULL,
	[TO_DATE] [varchar](8) NULL,
	[MEDI_BILL_PRO_UNI_BILL_ID_NUM] [varchar](30) NULL,
	[INVOICE_DETAIL_ID] [int] NULL,
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[PRESCRIP_NO] [varchar](30) NULL,
	[MEDI_NDC_BLD_CODE] [varchar](20) NULL,
	[DISPENSED] [varchar](25) NULL,
	[MEDS_QUANTITY] [int] NULL,
	[DAYS_SUPPLIED] [int] NULL,
	[UNITS_BILLED_TYPE] [varchar](4) NULL,
	[REV_CODE] [varchar](4) NULL,
	[MEDI_DIAGNOSIS_PTR] [varchar](4) NULL,
	[MEDI_CTL_NUMBER] [varchar](25) NULL,
	[MEDI_DRG_SUPP_BLD_AMT] [decimal](10, 2) NULL,
	[MEDI_ADJUSTMENT_AMT] [decimal](10, 2) NULL,
	[RX_USUAL_CHARGE] [decimal](10, 2) NULL,
	[PHY_EID_INV_DET] [int] NULL,
	[FL_LICENSE][varchar](25) NULL,
	[ZIP_CODE_INV_DET][varchar](10) NULL,
	[TABLE_CODE][int] NULL,
	[MODIFIER_CODE][varchar](25) NULL,
	[RX_IND][int] NULL,
	[CERTIFICATION][int] NULL,
	[PHY_PHARM_NDC_SEC][varchar](20) NULL,
	[MED_SUPPLY_FLAG][int] NULL,
	[PURCHASED_IND][int] NULL,
PRIMARY KEY CLUSTERED 
(	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
end


/****** Object:  Table [dbo].[EDI_MEDICAL_FUNDS_INV]    Script Date: 4/12/2017 5:59:26 PM ******/


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_FUNDS_INV]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_FUNDS_INV]
BEGIN

CREATE TABLE [dbo].[EDI_MEDICAL_FUNDS_INV](
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[TRANS_ID] [int] NULL,
	[MEDI_CTL_NUMBER] [varchar](50) Null,
	[MEDI_TOT_AMT_PAID_PER_BILL] [decimal](10,2) NULL,
	[MEDI_DATE_INSRER_RCVD_BIL] [varchar](8) NULL,
	[BILL_ADJUST_AMT] [decimal](10,2) NULL,
	[ADJUST_START] [varchar](8) NULL,
	[ADJUST_END] [varchar](8) NULL,
	[TOT_AMT_TO_PAY] [decimal](10,2) NULL,
	[TOT_AMT_BILLED] [decimal](10,2) NULL,
	[MEDI_BILL_ADJ_CODE] [varchar](25) NULL,
	[INVOICE_ID] [int] NULL,
	[PAYEE_EID] [int] NULL,
	[DN529_FIRST_NAME] [varchar](255) NULL,
	[DN528_LAST_NAME] [varchar](255) NULL,
	[DN531_SUFFIX_COMMON] [int] NULL,
	[DN530_MIDDLE_NAME] [varchar](255) NULL,
	[DN634_NPI_NUMBER] [varchar](10) NULL,
	[DN538_ADDR1] [varchar](100) NULL,
	[DN539_ADDR2] [varchar](100) NULL,
	[DN540_CITY] [varchar](50) NULL,
	[DN569_COUNTRY_CODE] [int] NULL,
	[DN541_STATE_ID] [int] NULL,
	[DN542_ZIP_CODE] [varchar](10) NULL,
	[DN629_TAX_ID] [varchar](20) NULL,
	[DN630_WC_FILING_NUMBER] [varchar](30) NULL,
	[DN537_BILL_PROV_PRI_SP_CODE] [int] NULL,
	[FACILITY_PAYEE_EID] [int] NULL,
	[FACILITY_LAST_NAME_TEXT] [varchar](255) NULL,
	[FACILITY_ADDR1_TEXT] [varchar](100) NULL,
	[FACILITY_ADDR2_TEXT] [varchar](100) NULL,
	[FACILITY_CITY_TEXT] [varchar](50) NULL,
	[FACLITY_STATE_ID] [int] NULL,
	[FACLITY_COUNTRY_CODE] [int] NULL,
	[FACLITY_POSTAL_CODE_TEXT] [varchar](15) NULL,
	[FACILITY_NPI_NUM] [varchar](30) NULL,
	[PROV_AGRMNT_CODE] [int] NULL,
	[BILL_SUB_RSN_CODE] [int] NULL,
	[MEDI_DATE_OF_BILL] [varchar](8) NULL,
	[MEDI_DATE_INSRD_PAID_BILL] [varchar](8) NULL,
	[MEDI_SRVC_BILL_DATETO] [varchar](8) NULL,
	[MEDI_SRVC_BILL_DATEFROM] [varchar](8) NULL,
	[MEDI_PRSCRPTN_DATETO] [varchar](8) NULL,
	[MEDI_PRSCRPTN_DATEFROM] [varchar](8) NULL,
	[MEDI_UNIQ_BILL_ID_NUM] [varchar](50) NULL,
	[MEDI_TRANS_TRACK_NUM] [varchar](25) NULL,
	[MEDI_PRNCPL_DIG_CODE] [int] NULL,
	[MEDI_PRIN_PROC_CODE] [varchar](25) null,
	[MEDI_PRNCPL_PROC_DATE] [varchar](8) null,
	[ADMTNG_DIAG_CODE] [int] NULL,
	[MEDI_BILLING_FORMAT_CODE] [Varchar](25) null,
	[MEDI_CONTRACT_TYPE_CODE] int NULL,
	[MEDI_SUPERVISE_EID]int NULL,
	[MEDI_NDC_PAID_CODE]int NULL,
	[MEDI_JURIS_PROC_BLD_CDE]int NULL,
	[MEDI_JURIS_PROC_PD_CODE]int NULL,
	[MEDI_BILL_ADJ_GRP_CODE]int NULL,
	[MEDI_DAYS_UNITS_CODE]int NULL,
	[MEDI_DISPENSE_WRITTEN_CODE]int NULL,
	[MEDI_ADMISSION_TYPE_CODE][Varchar](5) null,
	[MEDI_OUTPATIENT_VISIT_CODE][Varchar](5) null,
PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
end


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_INVDET_MOD]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_INVDET_MOD]
BEGIN


CREATE TABLE [dbo].[EDI_MEDICAL_INVDET_MOD](
	[JOBID] [int] NOT NULL,
	[DA_ROW_ID] [int] NOT NULL,
	[TRANS_ID] [int] NULL,
	[INVOICE_DETAIL_ID] [int] NULL,
	[MODIFIER_CODE][varchar](25) NULL,
	[MODIFIER_ORDER] [int] NULL,
	[MEDI_CTL_NUMBER] [varchar](50) Null,
PRIMARY KEY CLUSTERED 
(
	[JOBID] ASC,
	[DA_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

end


/****** Object:  Table [dbo].[EDI_MEDICAL_DIAG_CODE]    Script Date: 4/14/2017 6:31:13 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_DIAG_CODE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_DIAG_CODE]
BEGIN

CREATE TABLE [dbo].[EDI_MEDICAL_DIAG_CODE](
	[INVOICE_DETAIL_ID] [int] NULL,
	[DIAGNOSIS_CODE] [varchar](25) NULL,
	[JOBID] [int] NOT NULL,
	[DA_ROW_ID] [int] NOT NULL,
	[DIAGNOSIS_CODE_ICD10] [varchar](25) NULL,
	[MEDI_CTL_NUMBER] [varchar](50) Null,
	[FL_ICD_TYPE_INDICATOR] [varchar](25) NULL,
PRIMARY KEY CLUSTERED 
([DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

end


/****** Object:  Table [dbo].[EDI_MEDICAL_PROC]    Script Date: 4/14/2017 6:41:33 PM ******/

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_PROC]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_PROC]
BEGIN

CREATE TABLE [dbo].[EDI_MEDICAL_PROC](
	[JOBID] [int] NOT NULL,
	[DA_ROW_ID] [int] NOT NULL,
	[TRANS_ID] [int] NULL,
	[PI_ROW_ID] [int] NULL,
	[PROCEDURE_CODE] [int] NULL,
	[DATE_OF_PROCEDURE] [varchar](8) NULL,
	[MEDI_CTL_NUMBER] [varchar](50) NULL,
	[PROC_SHORT_CODE] [varchar](25) NULL,
	[PROC_CODE_DESC] [varchar](100) NULL,--dn0551
PRIMARY KEY CLUSTERED 
(
	[JOBID] ASC,
	[DA_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

end



/****** Object:  Table [dbo].[EDI_MEDICAL_EOB]    Script Date: 4/21/2017 3:47:00 PM ******/


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_EOB]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_EOB]
BEGIN
CREATE TABLE [dbo].[EDI_MEDICAL_EOB](
	[INVOICE_DETAIL_ID] [int] NULL,
	[EOB_CODE] [varchar](25) NULL,
	[TRANS_ID] [int] NULL,
	[MEDI_CTL_NUMBER] [varchar](25) NULL,
	[JOBID] [int] NOT NULL,
	[DA_ROW_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[JOBID] ASC,
	[DA_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
end



/****** Object:  Table [dbo].[EDI_MEDICAL_FEDI_FTS]    Script Date: 7/31/2017 2:34:26 PM ******/

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_FEDI_FTS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_FEDI_FTS]
BEGIN

CREATE TABLE [dbo].[EDI_MEDICAL_FEDI_FTS](
	[TRANS_ID] [int] NULL,
	[FUNDS_SPLIT_ROW_ID] [int] NULL,
	[BILLING_CODE_TEXT] [varchar](64) NULL,
	[UNITS_BILLED_NUM] [decimal](10, 2) NULL,
	[MEDI_TOT_CHARGE_BILL] [decimal](10, 2) NULL,
	[REV_CODE] [varchar](4) NULL,
	[MEDI_BILL_TYPE_CODE] [varchar](25) NULL,
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
	[MODIFIER_CODE] [varchar](25) NULL,
	[MODIFIER_CODE_1] [varchar](25) NULL,
	[MODIFIER_CODE_2] [varchar](25) NULL,
	[MODIFIER_CODE_3] [varchar](25) NULL,
	[MODIFIER_CODE_4] [varchar](25) NULL,
	[INVOICE_DETAIL_ID] [int] NULL,
	[EOB_CODE_1] [varchar](2) NULL,
	[EOB_CODE_2] [varchar](2) NULL,
	[EOB_CODE_3] [varchar](2) NULL,
	[MEDS_QUANTITY] [int] NULL,
	[DAYS_SUPPLIED] [int] NULL,
	[PRESCRIP_NO] [varchar](30) NULL,
	[PHY_EID_INV_DET] [int] NULL,
	[PRESCRIP_DATE] [varchar](8) NULL,
	[RX_USUAL_CHARGE] [decimal](10, 2) NULL,
	[RX_IND] [int] NULL,
	[CERTIFICATION] [int] NULL,
	[PHY_PHARM_NDC_SEC] [varchar](20) NULL,
	[MED_SUPPLY_FLAG] [int] NULL,
	[PURCHASED_IND] [int] NULL,
	[DISPENSED] [varchar](25) NULL,
	[FL_LICENSE] [varchar](25) NULL,
	[PHY_LIC_NUM_PHY_T] [varchar](13) NULL,
	[HCPCS_CODE] [varchar](5) NULL,
	--[TRANS_ID_1] [int] NULL,
	[MEDI_NDC_BLD_CODE] [varchar](20) NULL,
	[MEDI_PLCE_OF_SRVC_BILL_CODE] [varchar](25) NULL,
	[DIAG_REF_NO] [varchar](4) NULL,
	[AMOUNT_TO_PAY] [decimal](10, 2) NULL,
	[FROM_DATE] [varchar](8) NULL,
	[TO_DATE] [varchar](8) NULL,
	[MEDI_BILL_FORMAT_CODE] [varchar](25) NULL,
	[MEDI_BILL_FREQ_TYPE_CODE] [varchar](25) NULL,
	[TYPE_OF_SER_CODE] [varchar](25) NULL,
	[DRUG_NAME] [varchar](80) NULL,
	[ZIP_CODE_INV_DET] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
end





/****** Object:  Table [dbo].[EDI_MEDICAL_UPD_CTLNO]    Script Date: 8/3/2017 4:35:01 PM ******/
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[EDI_MEDICAL_UPD_CTLNO]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[EDI_MEDICAL_UPD_CTLNO]
BEGIN
CREATE TABLE [dbo].[EDI_MEDICAL_UPD_CTLNO](
	[MEDI_CTL_NUMBER] [varchar](50) NULL,
	[TRANS_ID] [int] NULL,
	[DA_ROW_ID] [int] NOT NULL,
	[JOBID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DA_ROW_ID] ASC,
	[JOBID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

END






insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0615_TO_XX','WA','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0615_FROM_XX','WA','Must be a valid DATE in CCYYMMDD format and prior to DN0615_TO_XX','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0532_XX','','Must be A-Z/0-9/spaces','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0101_XX','','Must be a valid Time','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0100_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0006_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0050_XX','NC','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0052_XX','WA/NC','Must be a valid DOB in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0053_XX','WA/NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0098_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0099_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG VALUES ('DN0005_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0007_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0043_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0044_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0153_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0154_XX','OR/NC','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0156_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0152_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0042_XX','OR/NC','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0048_XX','NC','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0049_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0050_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values ('DN0031_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0018_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0015_XX','','Must be A-Z/0-9/spaces','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0523_XX','','Must be A-Z/0-9/spaces','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0188_XX','','Data must be present because Claim Administrator is a different entity than the insurer','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0187_XX','','Data must be present because Claim Administrator is a different entity than the insurer','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0014_XX','','Data must be present because Claim Administrator is a different entity than the insurer','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0501_XX','','Either amount is not provided or it does not balance to the sum of all charge amounts reported at the line level or to the drugs/billed amount','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0502_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0504_XX','','Either code is not populated or invalid code is populated','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0555_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0503_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0505_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0507_XX','WA','Either code is not populated or invalid code is populated','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0508_XX','','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0511_XX','','Must be a valid DATE in CCYYMMDD format and should be greater than Date_of_injury','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0509_TO_XX','','Must be a valid DATE in CCYYMMDD format','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0509_FROM_XX','','Must be a valid DATE in CCYYMMDD format and prior to DN0509_TO_XX','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0527_TO_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0527_FROM_XX','','Must be a valid DATE in CCYYMMDD format and prior to DN0527_TO_XX','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0510_XX','','Must be a valid DATE in CCYYMMDD format and should be greater than Date_of_injury','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0516_XX','','Either field is blank or its sum is not equal to sum of Total amount paid per line/split','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0500_XX','','Must be A-Z/0-9/spaces','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0266_XX','','Must be A-Z/0-9/spaces','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0521_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0535_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0513_XX','WA/OR','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0514_XX','WA/OR','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0515_XX','OR','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0520_XX','OR','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0520_1_XX','OR','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0577_XX','WA/OR/NC','Mandatory Fields as per the type of medical bill extracted are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0521_01_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0550_XX','','Must be a valid DATE in CCYYMMDD format','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_01_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_02_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_03_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_04_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_05_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_06_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_07_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_08_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_09_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_10_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_11_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0524_12_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0528_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0529_XX','OR','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0634_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_01_XX','WA/NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_02_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_03_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_04_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_05_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_06_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_07_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_08_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_09_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_10_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_11_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_12_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0533_13_XX','NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0538_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0540_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0629_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0647_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0684_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0686_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0543_XX','','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0541_XX','WA/NC','Either code is not populated or invalid code is populated','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0542_XX','WA/NC','Either code is not populated or invalid code is populated','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0543_XX','WA','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0569_XX','OR/NC','Either code is not populated or invalid code is populated','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0630_XX','OR','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0678_XX','OR','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0639_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0643_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0647_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0651_XX','OR','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0682_XX','WA/OR','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0687_XX','WA/NC','Either code is not populated or invalid code is populated','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0688_XX','WA/NC','Either code is not populated or invalid code is populated','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0689_XX','WA/OR/NC','Either code is not populated or invalid code is populated','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0690_XX','OR/NC','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0691_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0695_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0699_XX','WA/OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0209_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0208_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0714_XX','WA/OR/NC','Either code is not populated or invalid code is populated','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0715_XX','WA/OR/NC','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0721_XX','WA/OR/NC','Either code is not populated or invalid code is populated','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0714_1_XX','WA/OR','Either code is not populated or invalid code is populated','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0715_1_XX','WA/OR','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0719_XX','WA/OR','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0714_2_XX','WA/OR','Either code is not populated or invalid code is populated','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0714_3_XX','WA','Either code is not populated or invalid code is populated','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0715_2_XX','WA','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0721_01_XX','WA','Either code is not populated or invalid code is populated','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0722_XX','WA/OR','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0726_XX','WA/OR','Either code is not populated or invalid code is populated','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0728_XX','WA/OR','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0729_XX','WA/OR','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0762_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0579_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0544_01_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0544_02_XX','OR','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0544_03_XX','OR','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0545_01_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0545_02_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0545_03_XX','','Mandatory fields are not present','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0546_01_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0546_02_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0546_03_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0547_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0547_02_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0553_XX','','Either value is not present or invalid code is present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0554_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0600_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0557_01_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0552_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0552_02_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0552_03_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0553_01_XX','','Either value is not present or invalid code is present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0553_02_XX','','Either value is not present or invalid code is present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0554_01_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0554_02_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0557_05_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0561_01_XX','','Must be A-Z/0-9/spaces','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0721_01_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0562_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0563_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0605_TO_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0605_FROM_XX','','Must be a valid DATE in CCYYMMDD format and prior to DN0605_TO_XX','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0604_XX','','Must be a valid DATE in CCYYMMDD format','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0570_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0616_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0571_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0572_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0721_03_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0561_XX','','Mandatory fields are not present','EDI_MEDICAL_FTS_INVDET')
insert into EDI_MEDICAL_ERROR_LOG values('DN0574_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0731_XX','','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0293_XX','','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0732_01_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0733_01_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0734_01_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0732_02_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0733_02_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0734_02_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0732_03_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0733_03_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0734_03_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0732_04_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0733_04_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0734_04_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0732_05_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0733_05_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0734_05_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0044_XX','','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0587_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0592_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0595_XX','OR','Either code is not populated or invalid code is populated','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0599_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0628_XX','OR','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0622_XX','NC','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0623_XX','NC','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0658_XX','NC','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0155_XX','NC','Mandatory fields are not present','')
insert into EDI_MEDICAL_ERROR_LOG values('DN0512_XX','','Must be a valid DATE in CCYYMMDD format','EDI_MEDICAL_FUNDS_INV')
insert into EDI_MEDICAL_ERROR_LOG values('DN0559_XX','','Either code is not populated or invalid code is populated','EDI_MEDICAL_FTS_INVDET')

---------------------ERROR MEssages for Florida EDI------------------------

insert into EDI_MEDICAL_ERROR_LOG values('FL_D_REVCODE_H','','Revenue Billed Code missing for Payment','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_BILLCDTXT_H','','Procedure, Service, Supply Billed Code is wrong length','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_UNITBL_HPHY','','Day(s)/Unit(s) Billed for Payment.','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_TOTCRGLINE_H','','Total Charge Per Line is missing for Payment.','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_SERLINEDT_H','','Service Line Date From is out of position','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_TOTAMTPAY_H','','Total Amount Paid Per Line is required when field 10A is Ambulatory Surgical Center)','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_MEDQ_PR','','Drugs/Supplies Quantity Dispensed missing for Payment.','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_DAYSUP_PR','','Drugs Number Of Days is missing for claim','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_BILLCDTXT_PRD','','NDC Number - Primary is missing for Payment','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_RXIND_PR','','Prescription Type Code missing for Payment','')
insert into EDI_MEDICAL_ERROR_LOG values('D_FL_PURCHIND_PR','','Purchased/Rental Indicator missing for Payment','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_PRESDT_PR','','Purchase/Rental Date missing for Payment','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_DSPNSED_PR','','Dispense As Written Code missing for Payment.','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_PHRMLICNO_PR','','Prescriber''s State License Number is missing for Payment.','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_RXUSCHRG_PR','','Total Amount Charged Per Line missing for Payment.','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_HPCS_PR','','Procedure, Service, Supply Billed Code missing for Payment. ','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_TOAMTPAY_PRPH','','Total Amount Paid Per Line missing for Payment.','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_PLCSER_P','','Physican Detail, Diagnosis Pointer missing for claim','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_BILLCDTXT_P','','Procedure, Service, Supply Billed Code missing for Payment.','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_TOTCHRBL_PD','','Total Charge Per Line missing for the claim','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_FRMDT_P','','Service Line Date From missing for the claim','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_TODT_PHY','','Service Line Date To missing for the claim.','')
insert into EDI_MEDICAL_ERROR_LOG values('FL_D_NDCNUM_P','','NDC Number - Primary is missing for Payment. ','')


insert into EDI_MEDICAL_ERROR_LOG values('FL_SENDERID_XX','','Florida Submitter ID was not found.  This is a required (mandatory) value.', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_CLMNT_XX','', 'No valid claimant for Claim', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_INSCODENUM_XX'	,'','Insurer Code Number is missing for claim', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_TPALICCODE_XX',''	,'TPA, Claim Administrator Code Number is missing', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_CLMADMFIEN_XX',''	,'Claim Administrator FEIN is missing', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_CLMADMZIP_XX','','Claim Administrator Physical Postal Code is missing', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_RPTTYPECODE_HP',''	,'Type of Report is missing for Payment.', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_EMPSSN_XX'	,'','Employee Jurisdiction Assigned Indentification Number is missing for claim', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_EMPLNAME_XX','',	'Employee Last Name is missing in claim', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_EMPFNAME_XX','',	'Employee First Name is missing in claim', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_EMPDOB_XX'	,'','Employee Date Of Birth is missing', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_EMPGNDR_XX','','Employee Gender Code is missing', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_OPPHYLIC_H','',	'Rendering Bill Provider State License Number is missing for claim', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_ADHR_H',	'','Admission Hour is missing for Payment', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_ADMDT_H','',	'Admission Date is missing for Payment', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_FROMDT_H','',	'Service Bill Date From is missing for Payment', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_TODT_FL'	,'','Service Bill Date Through is missing for Payment.', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_INSRCVBL_HPD','',	'Date Insurer Paid Bill is missing for Payment', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_DTINSPAID_HPD','','Total Amount Paid Per Bill missing for Payment', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_PRIDIAGCODE_H','','Principal ICD Diagnostic Code is missing for Payment.', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_RPTRESN_HPD','','Bill Submission Reason Code missing for Payment', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_ADMTYPECODE_H','','Admission Type Code is missing for Payment.', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_CLMCTL_HPPY',	'','Claim Administrator Claim Number missing for claim', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_FACLICNPI_H','','Facility data (Facility License and NPINumber ) is missing', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_ICDIND_PH',	'','ICD Type Indicator is missing for Payment', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_PAYPLAN_PR','','Payment Code is missing for Payment.', '')
insert into EDI_MEDICAL_ERROR_LOG values('FL_PLCSERCOD_D','','Place of Treatment for Payment is missing.', '')
End;