--============================================================
--   DI Module Name: DA EDI Medical
--   DESCRIPTION: Structure Definition Script for Staging database of DA EDI Medical.
--	 Template_MEDEDI(rmA16.4 onwards)
--   Script Date: 03/17/2017 
--	 Author		: mkaur24
--==============================================================


declare
isRmdb NUMBER;
iExists NUMBER;
begin
select count(*) into isRmdb from user_tables where table_name='SYS_PARMS';
if isRmdb > 0 then
dbms_output.put_line('Error: Script Execution Aborted - Script trying to execute on RISKMASTER database not on DA Staging database. Please open the correct Staging database 
and execute this script.');
else

--==========================================================
---CREATE EDI_MEDICAL_OPTIONS table 
--============================================================
BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_OPTIONS';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_OPTIONS';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

 EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_OPTIONS 
   (             
    JOBID NUMBER NOT NULL , 
    MEDICAL_BILL_TYPE Number,
    OPTIONSET_ID Number NOT NULL, 
    DATEOPTION Number, 
    DATEFROM VARCHAR2(8), 
    DATETO VARCHAR2(8), 
    REPORT_PERIOD_DATETO VARCHAR2(8),
    REPORT_PERIOD_DATEFROM VARCHAR2(8),
    EXTRACTFILENAME VARCHAR2(1024), 
    IAIABC_TRASN_ID_NUM VARCHAR2(50), 
    IAIABC_SENDER_ID VARCHAR2 (50), 
    IAIABC_RECEIVER_ID VARCHAR2(50),
    STR_PARM_NAME VARCHAR2 (100),
    CreateNewCtl Number null,
    FLMedBillType Number null,
    ExtractPreviousData Number null,
    RISKMASTR_ProducInd varchar(1) null,
    BillTypeFlag Number null)';

EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_OPTIONS ADD CONSTRAINT PK_EDI_MEDICAL_OPTIONS PRIMARY KEY (JOBID, OPTIONSET_ID)';  

END IF;
END;
--==========================================================
---CREATE EDIMEDICALEXSOURCE table 
--============================================================
BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDIMEDICALEXSOURCE';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDIMEDICALEXSOURCE';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EDIMEDICALEXSOURCE
	(
	OPTIONSETID Number NOT NULL, 
	CONTROLNO VARCHAR2(50) NULL, 
	BSRCODE VARCHAR2(50) NULL,
	CLAIM_ID Number  NULL,
	STATEABBRE VARCHAR2(50) NULL,
	STATE_ROW_ID  NUMBER NULL,
	TRANS_ID  NUMBER NULL)';
END IF;
END;

--==========================================================
---CREATE EDI_MEDICAL_EXTRACT table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_EXTRACT';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_EXTRACT';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

 EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_EXTRACT
    (
	JOBID Number ,
	DA_ROW_ID Number NOT NULL ,
	INVALID_ROW_ID Number NOT NULL,
	REPORT_PERIOD_DATETO VARCHAR2(8),
	REPORT_PERIOD_DATEFROM VARCHAR2(8),
	MEDI_CLAIM_ID Number NOT NULL,
	MEDI_ORIGINATOR_TRANS_ID_NUM varchar2(50),
	MEDI_DATE_TRNSMSSN_SENT varchar2(8 ),
	MEDI_TIME_TRNSMSSN_SENT varchar2(6 ),
	MEDI_SENDER_ID varchar2(9),
	MEDI_RECEIVER_ID varchar2(9),
	MEDI_REPORTING_PERIOD Number ,
	MEDI_INSURER_EID Number ,
	MEDI_INSURER_NAME varchar2(255),		--mpandey24 Added
	MEDI_INSURER_ZIP varchar2(10),			--mpandey24 Added
	MEDI_INSURER_TID varchar2(20),			--mpandey24 Added
	MEDI_CLAIM_ADMIN_NAME varchar2(50),
	MEDI_CLAIM_ADMINI_FEIN varchar2(9),
	MEDI_CLAIM_ADMIN_POST_CODE varchar2(10),
	MEDI_EMPLOYER_EID Number,
	MEDI_DATE_OF_INJURY varchar2(8),
	EMP_LAST_NAME varchar2(255),
	EMP_FIRST_NAME varchar2(255),
	EMP_MIDDLE_NAME varchar2(255),
	EMP_SUFFIX_COMMON Number,
	EMP_TAX_ID varchar2(20),
	EMP_ADDR1 varchar2(100),
	EMP_ADDR2 varchar2(100),
	EMP_CITY varchar2(50),
	EMP_STATE_ID varchar2(25),
	EMP_COUNTRY_CODE varchar2(25),
	EMP_SEX_CODE varchar2(25),
	EMP_BIRTH_DATE varchar2(8),
	EMP_PHONE1 varchar2(30),
	EMP_ZIP_CODE varchar2(10),
	MEDI_EMPL_NAME_SUFFIX varchar2(4),
	MEDI_EMPL_GREEN_CARD varchar2(15),
	MEDI_EMPL_JUR_ID varchar2(15),
	MEDI_EMPL_PASSPORT varchar2(15),
	MEDI_EMPL_EMP_VISA varchar2(15),
	MEDI_CLAIM_ADMIN_CLM_NUM varchar2(25),
	MEDI_JURIS_CLM_NUM varchar2(25),
	MEDI_BILL_PRO_UNI_BILL_ID_NUM NUMBER,
	MEDI_TOT_CHARGE_BILL NUMBER(10,2),
	MEDI_BILL_TYPE_CODE NUMBER,
	MEDI_FACLITY_TYPE_CODE NUMBER,
	MEDI_PLCE_OF_SRVC_BILL_CODE NUMBER,
	MEDI_BILL_FORMAT_CODE NUMBER,
	MEDI_BILL_FREQ_TYPE_CODE NUMBER,
	MEDI_PROV_AGRMNT_CODE NUMBER,
	MEDI_BILL_SUB_RSN_CODE NUMBER,
	MEDI_DATE_INSRER_RCVD_BILL varchar2(8),
	MEDI_ADMISN_DATE varchar2(12),
	MEDI_ADMISN_HOUR varchar2(12),
	MEDI_DSCHRGE_DATE varchar2(12),
	MEDI_DSCHRGE_HOUR varchar2(12),
	MEDI_SRVC_BILL_DATETO varchar2(8),
	MEDI_SRVC_BILL_DATEFROM varchar2(8),
	MEDI_PRSCRPTN_DATETO varchar2(8),
	MEDI_PRSCRPTN_DATEFROM varchar2(8),
	MEDI_DATE_OF_BILL varchar2(8),
	MEDI_DATE_INSRD_PAID_BILL varchar2(8),
	MEDI_ADMSSN_TYPE_CODE NUMBER,
	MEDI_ADMSSN_TYPE_SHORT_CODE varchar2(25),
	MEDI_CONTRCT_TYPE_CODE NUMBER,
	MEDI_CONTRCT_TYPE_SHORT_CODE varchar(25),
	MEDI_TOT_AMT_PAID_PER_BILL NUMBER(10,2),
	MEDI_UNIQ_BILL_ID_NUM varchar2(50),
	MEDI_TRANS_TRACK_NUM varchar2(50),
	MEDI_TRTMNT_AUTHOR_NUM varchar2(50),
	MEDI_LMPSM_PYMNT_CODE NUMBER,
	MEDI_LMPSM_PYMNT_SHRT_CODE varchar2(25),
	MEDI_PRNCPL_DIG_CODE NUMBER,
	MEDI_ADMTNG_DIAG_CODE NUMBER,
	MEDI_BILD_DRG_CODE NUMBER,
	MEDI_BIL_PRV_EID NUMBER,
	MEDI_BIL_PRV_NAME_SUFFIX varchar(4),
	MEDI_BIL_PRV_PRM_SPL_CODE NUMBER,
	MEDI_BIL_PRV_STE_LIC_NUM varchar2(50),
	MEDI_RENDRNGBILL_EID NUMBER,
	MEDI_RENDRNGBILL_NAME_SUFFIX varchar2(4),
	MEDI_RENDRNGBILL_PRM_SPL_CODE NUMBER,
	MEDI_RENDRNGBILL_STE_LIC_NUM varchar2(50),
	MEDI_SUPERVISE_EID NUMBER,
	MEDI_SUPERVISE_SUFFIX varchar(4),
	MEDI_SUPERVISE_PRM_SPL_CODE NUMBER,
	MEDI_SUPERVISE_STE_LIC_NUM varchar2(50),
	MEDI_FACILITY_EID NUMBER,
	MEDI_FACILITY_STE_LIC_NUM varchar2(50),
	MEDI_FACILITY_SRVC_LOC_ID NUMBER,
	MEDI_REFERRNG_EID NUMBER,
	MEDI_REFERRNG_SUFFIX varchar2(4),
	MEDI_REFERRNG_STE_LIC_NUM varchar2(50),
	MEDI_REFER_FIRST_NAME varchar2(255),
	MEDI_REFER_LAST_NAME varchar2 (255),
	MEDI_REFER_MIDDLE_NAME varchar2 (255),
	MEDI_REFER_NPI varchar2(10),
	MEDI_MCO_NAME varchar2(255),
	MEDI_MCO_SSN varchar2(9),
	MEDI_MCO_IDNUM NUMBER,
	MEDI_BILL_ADJUST_GRP_CODE NUMBER,
	MEDI_PRIOR_ACT_AMT_PAID NUMBER(20,2),
	MEDI_LINE_NUM NUMBER,
	MEDI_PROC_DESC varchar2 (80),
	MEDI_TOT_CHARGE_PER_LINE NUMBER (10,2),
	MEDI_DAY_PER_UNT_CODE NUMBER NULL,
	MEDI_DAY_PER_UNT_BLD varchar2(2),
	MEDI_PLC_OF_SRVC_LNE_CODE NUMBER,
	MEDI_DIAGNOSIS_PTR varchar2(1),
	MEDI_REV_BLD_CODE NUMBER,
	MEDI_PRSCRPTN_LINE_NUM varchar2(50),
	MEDI_NDC_BLD_CODE NUMBER ,
	MEDI_DSPNS_AS_WRTN_CODE NUMBER,
	MEDI_DRUG_NAME varchar2(80),
	MEDI_CMP_DRG_INDI varchar2(2),
	MEDI_SRVC_LINE_DATETO varchar2(17) ,
	MEDI_SRVC_LINE_DATEFROM varchar2(17),
	MEDI_PRCRPTN_LINE_DATE varchar2(8),
	MEDI_DRG_SUPP_DISP varchar2(15),
	MEDI_DRG_SUPP_NO_DAYS varchar2(15),
	MEDI_CNTRCT_TYPE_CODE NUMBER,
	MEDI_TRMNT_LINE_AUTHOR_NUM varchar2(50),
	MEDI_DRG_SUPP_DIS_FEE varchar2(15),
	MEDI_DRG_SUPP_BLD_AMT NUMBER(10,2) ,
	MEDI_LINE_ITM_TAX_CHRG_AMT NUMBER (10,2),
	MEDI_RENDRNGLINE_EID NUMBER,
	MEDI_RENDRNGLINE_NAME_SUFFIX varchar2(4),
	MEDI_RENDRNGLINE_PRM_SPL_CODE NUMBER,
	MEDI_RENDRNGLINE_STE_LIC_NUM varchar (50),
	MEDI_TOT_AMT_PAID_PRLINE NUMBER (10,2),
	MEDI_RVN_PAID_CODE NUMBER,
	MEDI_DAY_PER_UNT_PAID varchar2(2),
	MEDI_LINE_ITM_PRIOR_ACT_AMT NUMBER(10,2),
	MEDI_LINE_ITM_TAX_PAID_AMT NUMBER(10,2),
	MEDI_FILING_STATE_ID NUMBER,
	MEDI_EMPLOYEE_EID NUMBER,
	MEDI_ADMIN_EID NUMBER,
	MEDI_CLAIM_TYPE_CODE NUMBER,
	MEDI_PRIMARY_POLICY_ID NUMBER,
	MEDI_IS_CARRIER_CLAIM NUMBER,	
	MEDI_PI_DEPT_ASSIGNED_EID NUMBER,
	MEDI_DATE_OF_EVENT varchar2(8),
	MEDI_EVENT_ID NUMBER,
	MEDI_DEF_CARRIER_EID NUMBER,
	MEDI_CLMADMIN_ORG_LEVEL NUMBER,
	MEDI_PRINT_CLAIM_ADMIN NUMBER,
	MEDI_CLAIMADMIN_TPA_EID  NUMBER,
	MEDI_DEF_CLAIM_ADMIN_EID NUMBER,
	MEDI_EMPLOYER_LEVEL  NUMBER,
	MEDI_VIRGIN_PARENT_LEVEL  NUMBER,
	MEDI_DEPT_USE_DEF_CARRIER  NUMBER,
	MEDI_CTL_NUMBER varchar2(50),
	MEDI_CARRIER_ORG_LEVEL NUMBER,
	MEDI_JURIS_ROW_ID NUMBER null,
	MEDI_CARRIER_EID NUMBER null,
	MEDI_PRIN_PROC_CODE varchar2(25),
	MEDI_PRNCPL_PROC_DATE varchar2(8),
	BSRCODE varchar2 (50),
	MEDI_BILLING_FORMAT_CODE Varchar2(25),
	MEDI_CONTRACT_TYPE_CODE Varchar2(25),
	MEDI_NDC_PAID_CODE Varchar2(25),
	MEDI_JURIS_PROC_BLD_CODE Varchar2(25),
	MEDI_JURIS_PROC_PD_CDE Varchar2 (25),
	MEDI_BILL_ADJ_GRP_CODE Varchar2(25),
	MEDI_DAYS_UNITS_CODE Varchar2 (25),
	MEDI_DISPENSE_WRITTEN_CODE Varchar2(25),
	MEDI_ADMISSION_TYPE_CODE Varchar2(5),
	MEDI_OUTPATIENT_VISIT_CODE Varchar2(5),
  MEDI_CERT_NUMBER Varchar2(64) null,         --Added for florida MED 
  MEDI_CODELICENSE_NUMBER Varchar2(64) null  --Added for florida MED 
  )';
EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_EXTRACT ADD CONSTRAINT PK_EDI_MEDICAL_EXTRACT PRIMARY KEY (JOBID, DA_ROW_ID)';
	
END IF;
END;

--==========================================================
---CREATE EDI_MEDICAL_ENTITY table 
--============================================================
BEGIN
	SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_ENTITY';
	
IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_ENTITY';
iExists := 0 ;
END IF;

IF iExists = 0 THEN
 EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_ENTITY
    (
	JOBID NUMBER NOT NULL,
	DA_ROW_ID NUMBER NOT NULL,
	ENTITY_ID NUMBER NOT NULL,
	ABBREVIATION varchar2(25),
	ADDR1 varchar2(100),
	ADDR2 varchar2(100),
	ALSO_KNOWN_AS varchar2(50),
	BUSINESS_TYPE_CODE NUMBER,
	CITY varchar2(50),
	COMMENTS varchar2(4000),
	CONTACT varchar2(50),
	COUNTRY_SCODE varchar2(25),
	COUNTY varchar2(30),
	NATURE_OF_BUSINESS varchar2(50),
	ORGANIZATION_TYPE NUMBER,
	SIC_CODE NUMBER,
	SIC_CODE_DESC varchar2(150),
	NAICS_CODE NUMBER,
	ENTITY_TABLE_ID NUMBER,
	LAST_NAME varchar2(255),
	FIRST_NAME varchar2(255),
	STATE_ID NUMBER,
	ZIP_CODE varchar2(10),
	PARENT_EID NUMBER,
	TAX_ID varchar2(20),
	EMAIL_TYPE_CODE NUMBER,
	EMAIL_ADDRESS varchar2(100),
	SEX_CODE NUMBER,
	BIRTH_DATE varchar2(8),
	PHONE1 varchar2(30),
	PHONE2 varchar2(30),
	FAX_NUMBER varchar2(30),
	DTTM_RCD_ADDED varchar2(14),
	DTTM_RCD_LAST_UPD varchar2(14),
	UPDATED_BY_USER varchar2(50),
	ADDED_BY_USER varchar2(50),
	DELETED_FLAG NUMBER,
	EFF_START_DATE varchar2(8),
	EFF_END_DATE varchar2(8),
	TRIGGER_DATE_FIELD varchar2(50),
	RM_USER_ID NUMBER,
	MIDDLE_NAME varchar2(255),
	TITLE varchar2(50),
	NPI_NUMBER varchar2(10))';
EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_ENTITY ADD CONSTRAINT PK_EDI_MEDICAL_ENTITY PRIMARY KEY (JOBID, DA_ROW_ID)';	

END IF;
END;

--==========================================================
---CREATE EDI_MEDICAL_CODES table 
--============================================================
BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_CODES';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_CODES';
iExists := 0 ;
END IF;

IF iExists = 0 THEN
EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_CODES
   (
	JOBID NUMBER NOT NULL,
	DA_ROW_ID NUMBER NOT NULL,
	MEDI_DIAG_CODE_ELMNT_NAME varchar2(6),
	MEDI_DIAG_SHORT_CODE varchar2(25),
	MEDI_COLUMN_NAME varchar2(25),
	MEDI_PROCEDRE_DATE varchar2(8),
	MEDI_ADJSTMNT_AMT NUMBER(20,2),
	MEDI_ADJSTMNT_UNIT NUMBER )';
EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_CODES ADD CONSTRAINT PK_EDI_MEDICAL_CODES PRIMARY KEY (JOBID, DA_ROW_ID)';
	
END IF;
END;
--==========================================================
---CREATE EDI_MEDICAL_ADJUSTMENT table 
--============================================================
BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_ADJUSTMENT';
IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_ADJUSTMENT';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_ADJUSTMENT
    (
	JOBID NUMBER NOT NULL,
	DA_ROW_ID NUMBER  NOT NULL,
	MEDI_ADJST_GRP_CODE varchar2(25),
	MEDI_ADJST_RSN_CODE varchar2(25),
	MEDI_ADJST_AMT NUMBER(10,2),
	MEDI_ADJST_UNIT NUMBER(10,2),
	MEDI_SERVICE_OR_BILL varchar2(10))';
EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_ADJUSTMENT ADD CONSTRAINT PK_EDI_MEDICAL_ADJUSTMENT PRIMARY KEY (JOBID, DA_ROW_ID)';	
	 
END IF;
END;
--==========================================================
---CREATE ERROR_LOG table 
--============================================================
BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='ERROR_LOG';
IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE ERROR_LOG';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

	EXECUTE IMMEDIATE 'CREATE TABLE ERROR_LOG
	   (
		ERR_LOG_ROW_ID NUMBER NOT NULL,
		JOBID NUMBER NOT NULL,
		INPUT_ROW_ID NUMBER,
		MODULE_NAME varchar2(50),
		WORK_FLOW_NAME varchar2(50),
		DATA_FLOW_NAME varchar2(50),
		ERROR_TIME varchar2(14),
		ERROR_TITLE varchar2(100),
		ERROR_DESC varchar2(4000),
		IS_VALIDATION NUMBER,
		ERROR_TABLE varchar2(50),
		TABLE_ROW_ID NUMBER,
		ERROR_COLUMNS varchar2(4000))';
		
EXECUTE IMMEDIATE 'ALTER TABLE ERROR_LOG ADD CONSTRAINT PK_ERROR_LOG PRIMARY KEY (JOBID,ERR_LOG_ROW_ID)';	
	 
END IF;
END;	


--==========================================================
---CREATE PROCESS_LOG table 
--============================================================
BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='PROCESS_LOG';
IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE PROCESS_LOG';
iExists := 0 ;
END IF;

IF iExists = 0 THEN


EXECUTE IMMEDIATE  'CREATE TABLE PROCESS_LOG
(DA_ROW_ID NUMBER ,
JOBID NUMBER NOT NULL,
		PROCESS_DESC varchar2(500),
        DISPLAY_ORDER NUMBER,
        TRANS_ID NUMBER,
        IDENTIFIER NUMBER,
		CLAIM_NUMBER VARCHAR2(25), 
        ERROR_RECORDS VARCHAR2(500),
        RULE_FAILED VARCHAR2(255))';

END IF;
END;

--==========================================================
---CREATE EDI_MEDICAL_PAYMENT table 
--============================================================
BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_PAYMENT';
IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_PAYMENT';
iExists := 0 ;
END IF;

IF iExists = 0 THEN
EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_PAYMENT
	(
DA_ROW_ID NUMBER  NOT NULL , 
	JOBID NUMBER NOT NULL , 
	CLAIM_ID NUMBER, 
	DN0501_TOT_CHARGE_BILL float,
	DN0509_SRVC_BILL_DATE_RNGE varchar2(17),
	DN0510_DATE_OF_BILL varchar2(8),
	DN0512_DATE_INSRD_PAID_BILL varchar2(8),
	DN0516_TOT_AMT_PAID_PR_BILL varchar2(18),
	DN0266_TRANS_TRACK_NUM varchar2(50),
	DN0552_01_TOT_CHARGE_PER_LINE varchar2(18),
	DN0553_01_DAY_PER_UNT_CODE varchar2(25),
	DN0554_01_DAY_PER_UNT_BLD varchar2(2),
	DN0600_01_PLC_OF_SRVC_LNE_CODE varchar2(25),
	CONCATENATED_STRING CLOB)';

END IF;
END;
--==========================================================
---CREATE EDI_MEDICAL_EOB table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_EOB';
IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_EOB';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_EOB 
   (           INVOICE_DETAIL_ID NUMBER,
               EOB_CODE varchar2(25),
               TRANS_ID NUMBER,
               MEDI_CTL_NUMBER varchar2(25),
               JOBID NUMBER NOT NULL,
               DA_ROW_ID NUMBER NOT NULL
                )';

EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_EOB ADD CONSTRAINT PK_EDI_MEDICAL_EOB PRIMARY KEY (JOBID, DA_ROW_ID)';   

END IF;
END;

--==========================================================
---CREATE EDI_MEDICAL_PROC table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_PROC';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_PROC';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_PROC 
   (           JOBID Number NOT NULL,
                DA_ROW_ID Number NOT NULL,
                TRANS_ID Number,
                PI_ROW_ID Number,
               PROCEDURE_CODE Number,
                DATE_OF_PROCEDURE varchar2(8),
                MEDI_CTL_NUMBER varchar2 (50),
				PROC_SHORT_CODE varchar2 (25),
				PROC_CODE_DESC varchar2 (100)
                )';

EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_PROC ADD CONSTRAINT PK_EDI__MEDICAL_PROC PRIMARY KEY (JOBID, DA_ROW_ID)';   

END IF;
END;


--==========================================================
---CREATE EDI_MEDICAL_DIAG_CODE table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_DIAG_CODE';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_DIAG_CODE';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_DIAG_CODE  
   (           INVOICE_DETAIL_ID Number,
               DIAGNOSIS_CODE varchar2 (25),
               JOBID Number NOT NULL,
               DA_ROW_ID Number NOT NULL,
               DIAGNOSIS_CODE_ICD10 varchar2 (25),
               MEDI_CTL_NUMBER varchar2 (50),
               	FL_ICD_TYPE_INDICATOR varchar2 (25) NULL
                )';

EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_DIAG_CODE ADD CONSTRAINT PK_EDI_MEDICAL_DIAG_CODE PRIMARY KEY (JOBID, DA_ROW_ID)';

END IF;
END;

--==========================================================
---CREATE EDI_MEDICAL_INVDET_MOD table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_INVDET_MOD';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_INVDET_MOD';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_INVDET_MOD  
            (JOBID NUMBER NOT NULL,
	          DA_ROW_ID NUMBER NOT NULL,
	          TRANS_ID NUMBER,
	          INVOICE_DETAIL_ID NUMBER,
	          MODIFIER_CODE varchar2(25),
	          MODIFIER_ORDER NUMBER ,
	          MEDI_CTL_NUMBER varchar2(50))';

EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_INVDET_MOD ADD CONSTRAINT PK_EDI_MEDICAL_INVDET_MOD PRIMARY KEY (JOBID, DA_ROW_ID)';   
END IF;
END;

--==========================================================
---CREATE EDI_MEDICAL_FUNDS_INV table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_FUNDS_INV';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_FUNDS_INV';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_FUNDS_INV  
   (DA_ROW_ID NUMBER NOT NULL,
	JOBID NUMBER NOT NULL,
	TRANS_ID NUMBER,
	MEDI_CTL_NUMBER varchar2(50) ,
	MEDI_TOT_AMT_PAID_PER_BILL number(10,2),
	MEDI_DATE_INSRER_RCVD_BIL varchar2(8),
	BILL_ADJUST_AMT number(10,2),
	ADJUST_START varchar2(8),
	ADJUST_END varchar2(8),
	TOT_AMT_TO_PAY number(10,2),
	TOT_AMT_BILLED number(10,2),
	MEDI_BILL_ADJ_CODE varchar(25),
	INVOICE_ID NUMBER,
	PAYEE_EID NUMBER,
	DN529_FIRST_NAME varchar2(255),
	DN528_LAST_NAME varchar2(255),
	DN531_SUFFIX_COMMON NUMBER,
	DN530_MIDDLE_NAME varchar2(255),
	DN634_NPI_NUMBER varchar2(10),
	DN538_ADDR1 varchar2(100),
	DN539_ADDR2 varchar2(100),
	DN540_CITY varchar2(50),
	DN569_COUNTRY_CODE NUMBER,
	DN541_STATE_ID NUMBER,
	DN542_ZIP_CODE varchar2(10),
	DN629_TAX_ID varchar2(20),
	DN630_WC_FILING_NUMBER varchar2(30),
	DN537_BILL_PROV_PRI_SP_CODE NUMBER,
	FACILITY_PAYEE_EID NUMBER,
	FACILITY_LAST_NAME_TEXT varchar2(255),
	FACILITY_ADDR1_TEXT varchar2(100),
	FACILITY_ADDR2_TEXT varchar2(100),
	FACILITY_CITY_TEXT varchar2(50),
	FACLITY_STATE_ID NUMBER,
	FACLITY_COUNTRY_CODE NUMBER,
	FACLITY_POSTAL_CODE_TEXT varchar2(15),
	FACILITY_NPI_NUM varchar2(30),
	PROV_AGRMNT_CODE NUMBER,
	BILL_SUB_RSN_CODE NUMBER,
	MEDI_DATE_OF_BILL varchar2(8),
	MEDI_DATE_INSRD_PAID_BILL varchar2(8),
	MEDI_SRVC_BILL_DATETO varchar2(8),
	MEDI_SRVC_BILL_DATEFROM varchar2(8),
	MEDI_PRSCRPTN_DATETO varchar2(8),
	MEDI_PRSCRPTN_DATEFROM varchar2(8),
	MEDI_UNIQ_BILL_ID_NUM varchar2(50),
	MEDI_TRANS_TRACK_NUM varchar2(25),
	MEDI_PRNCPL_DIG_CODE NUMBER,
	MEDI_PRIN_PROC_CODE varchar2(25),
	MEDI_PRNCPL_PROC_DATE varchar2(8),
	ADMTNG_DIAG_CODE NUMBER,
	MEDI_BILLING_FORMAT_CODE Varchar2(25),
	MEDI_CONTRACT_TYPE_CODE NUMBER,
	MEDI_SUPERVISE_EID NUMBER,
	MEDI_NDC_PAID_CODE NUMBER,
	MEDI_JURIS_PROC_BLD_CDE NUMBER,
	MEDI_JURIS_PROC_PD_CODE NUMBER,
	MEDI_BILL_ADJ_GRP_CODE NUMBER,
	MEDI_DAYS_UNITS_CODE NUMBER,
	MEDI_DISPENSE_WRITTEN_CODE NUMBER,
	MEDI_ADMISSION_TYPE_CODE Varchar2(5),
	MEDI_OUTPATIENT_VISIT_CODE Varchar2(5)
                )';

EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_FUNDS_INV ADD CONSTRAINT PK_EDI_MEDICAL_FUNDS_INV PRIMARY KEY (JOBID, DA_ROW_ID)';   
END IF;
END;

--==========================================================
---CREATE EDI_MEDICAL_ERROR_LOG table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_ERROR_LOG';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_ERROR_LOG';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_ERROR_LOG 
   (   RULE_NAME VARCHAR2(20), 
       JURISDICTION VARCHAR2(10), 
       ERROR_MESSAGE VARCHAR2(500),
       ERROR_TABLE VARCHAR2(30)
                )'; 

END IF;
END;


--==========================================================
---CREATE EDI_MEDICAL_JURIS_STATES table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_JURIS_STATES';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_JURIS_STATES';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_JURIS_STATES 
   (JOBID NUMBER NOT NULL,
	DN0004_JURISDICTION_CODE varchar2(25) NOT NULL,
	ROW_NUM NUMBER,
	DA_ROW_ID NUMBER NOT NULL)'; 

END IF;
END;

--==========================================================
---CREATE EDI_MEDICAL_EXPORT table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_EXPORT';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_EXPORT';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_EXPORT 
   (   	DA_ROW_ID NUMBER NOT NULL,
	JOBID NUMBER NOT NULL ,
	INVALID_ROW NUMBER,
  TRANS_ID NUMBER NULL,
	MEDI_CTL_NUMBER varchar2(50),
	MEDI_CLAIM_ADMIN_EID NUMBER,
	MEDI_INSURER_EID NUMBER ,
	JURIS_STATE_ID varchar2(25) ,
	DN0615_TO_REPORT_PERIOD varchar2(8)  ,
	DN0615_FROM_REPORT_PERIOD varchar2(8)  ,
	DN0532_ORIGIN_TRANS_ID_NUM varchar2(50) ,
	DN0100_DATE_TRNSMSSN_SENT varchar2(8) ,
	DN0101_TIME_TRNSMSSN_SENT varchar2(6) ,
	DN0098_SENDER_ID varchar2(25) ,
	DN0099_RECEIVER_ID varchar2(25) ,
	DN0007_INSURER_NAME varchar2(255) ,
	DN0006_INSURER_FEIN varchar2(9) ,
	DN0616_INSURER_POST_CODE varchar2(10) ,
	DN0188_CLAIM_ADMIN_NAME varchar2(255) ,
	DN0187_CLAIM_ADMIN_FEIN varchar2(9) ,
	DN0014_CLAIM_ADMIN_POST_CODE varchar2(10) ,
	DN0018_EMPLOYER_NAME varchar2(255) ,
	DN0016_EMPLOYER_FEIN varchar2(9) ,
	DN0031_DATE_OF_INJURY varchar2(8) ,
	DN0043_EMPLOYEE_LAST_NAME varchar2(255) ,
	DN0044_EMPLOYEE_FIRST_NAME varchar2(255) ,
	DN0045_EMPLOYEE_MIDDLE_Name varchar2(255) ,
	DN0255_EMPLAST_NAME_SUFFIX varchar2(4) ,
	DN0042_EMPLOYEE_SSN varchar2(9) ,
	DN0153_EMPLOYEE_GREEN_CARD varchar2(15) ,
	DN0154_EMPID_ASSIGNEDBY_JURIS varchar2(15) ,
	DN0156_EMPLOYEE_PASSPORT_NUM varchar2(15) ,
	DN0152_EMPLOYEEE_VISA varchar2(15) ,
	DN0046_EMPLOYEE_MAIL_PRIMADD varchar2(255) ,
	DN0047_EMPLOYEE_MAIL_SECADD varchar2(255) ,
	DN0048_EMPLOYEE_MAIL_CITY varchar2(100) ,
	DN0049_EMPLOYEE_MAIL_STATECODE varchar2(25) ,
	DN0050_EMPLOYEE_MAIL_POSTCODE varchar2(10) ,
	DN0155_EMPLOYEE_MAIL_COUNTRY varchar2(25) ,
	DN0052_EMPLOYEE_DOB varchar2(8) ,
	DN0053_EMPLOYEE_GENDER varchar2(3) ,
	DN0015_CLAIM_ADMIN_CLAM_NUM varchar2(50) ,
	DN0005_JURIS_CLAM_NUM varchar2(50) ,
	DN0051_EMPLOYEE_PHONE_NUM varchar2(30) ,
	DN0523_BILL_PRO_UNI_ID_NUM varchar2(38) ,
	DN0501_TOT_CHARGE_BILL number(10,2) ,
	DN0502_BILL_TYPE_CODE varchar2(25) ,
	DN0504_FACLITY_CODE varchar2(25) ,
	DN0555_PLCE_OF_SRVC_BILL_CODE varchar2(25) ,
	DN0503_BILL_FORMAT_CODE varchar2(25),
	DN0505_BILL_FREQ_TPE_SHRT_CODE varchar2(25),
	DN0507_PROV_AGRMNT_SHRT_CODE varchar2(25),
	DN0508_BILL_SUB_RSN_SHRT_CODE varchar2(25),
	DN0511_DATE_INSRER_RCVD_BILL varchar2(8) ,
	DN0513_ADMISN_DATE varchar2(12) ,
	DN0622_ADMISN_HOUR varchar2(12) ,
	DN0514_DSCHRGE_DATE varchar2(8) ,
	DN0623_DSCHRGE_HOUR varchar2(12) ,
	DN0509_SRVC_BILL_DATETO varchar2(17) ,
	DN0509_SRVC_BILL_DATEFROM varchar2(17) ,
	DN0527_PRSCRPTN_DATETO varchar2(17) ,
	DN0527_PRSCRPTN_DATEFROM varchar2(17) ,
	DN0510_DATE_OF_BILL varchar2(8) ,
	DN0512_DATE_INSRD_PAID_BILL varchar2(8) ,
	DN0577_ADMSSN_TYPE_CODE varchar2(25) ,
	DN0515_CONTRCT_TYPE_CODE varchar2(25) ,
	DN0516_TOT_AMT_PAID_PR_BILL number(10,2) ,
	DN0500_UNIQ_BILL_ID_NUM varchar2(50) ,
	DN0266_TRANS_TRACK_NUM varchar2(50),
	DN0581_TRTMNT_AUTHOR_NUM varchar2(50) ,
	DN0293_LMPSM_PYMNT_CODE varchar2(25),
	DN0521_PRNCPL_DIG_CODE varchar2(25),
	DN0533_01_PRSNT_ADMSN_INDC varchar2(2),
	DN0535_ADMTNG_DIAG_CODE varchar2(25),
	DN0522_01_DIAG_CODE varchar2(25),
	DN0522_02_DIAG_CODE varchar2(25),
	DN0533_02_PRSNT_ADMSN_INDC varchar2(2),
	DN0522_03_DIAG_CODE varchar2(25),
	DN0533_03_PRSNT_ADMSN_INDC varchar2(2),
	DN0522_04_DIAG_CODE varchar2(25),
	DN0533_04_PRSNT_ADMSN_INDC varchar2(2),
	DN0522_05_DIAG_CODE varchar2(25),
	DN0533_05_PRSNT_ADMSN_INDC varchar2(2),
	DN0522_06_DIAG_CODE varchar2(25),
	DN0533_06_PRSNT_ADMSN_INDC varchar2(2),
	DN0522_07_DIAG_CODE varchar2(25),
	DN0533_07_PRSNT_ADMSN_INDC varchar2(2),
	DN0522_08_DIAG_CODE varchar2(25),
	DN0533_08_PRSNT_ADMSN_INDC varchar2(2),
	DN0522_09_DIAG_CODE varchar2(25),
	DN0533_09_PRSNT_ADMSN_INDC varchar2(2),
	DN0522_10_DIAG_CODE varchar2(25),
	DN0533_10_PRSNT_ADMSN_INDC varchar2(2),
	DN0522_11_DIAG_CODE varchar2(25),
	DN0533_11_PRSNT_ADMSN_INDC varchar2(2),
	DN0522_12_DIAG_CODE varchar2(25),
	DN0533_12_PRSNT_ADMSN_INDC varchar2(2),
	DN0533_13_PRSNT_ADMSN_INDC varchar2(2),
	DN0520_OUT_RSN_CODE varchar2(25) ,
	DN0520_1_OUT_RSN_CODE varchar2(25) ,
	DN0520_2_OUT_RSN_CODE varchar2(25) ,
	DN0521_PRNCPL_DIG_CODE1 varchar2(25),
	DN0522_02_DIAG_CODE2 varchar2(30),
	DN0522_03_DIAG_CODE3 varchar2(30),
	DN0522_04_DIAG_CODE4 varchar2(30),
	DN0522_05_DIAG_CODE5 varchar2(30),
	DN0522_06_DIAG_CODE6 varchar2(30),
	DN0522_07_DIAG_CODE7 varchar2(30),
	DN0522_08_DIAG_CODE8 varchar2(30),
	DN0522_09_DIAG_CODE9 varchar2(30),
	DN0522_10_DIAG_CODE10 varchar2(30),
	DN0522_11_DIAG_CODE11 varchar2(30),
	DN0522_12_DIAG_CODE12 varchar2(30),
	DN0525_PRNCPL_PROC_CODE varchar2(25) ,
	DN0550_PRNCPL_PROC_DATE varchar2(8) ,
	DN0736_01_OT_PROC_CODE varchar2(25) ,
	DN0524_01_OT_PROC_DATE varchar2(8) ,
	DN0736_02_OT_PROC_CODE varchar2(25) ,
	DN0524_02_OT_PROC_DATE varchar2(8) ,
	DN0736_03_OT_PROC_CODE varchar2(25) ,
	DN0524_03_OT_PROC_DATE varchar2(8) ,
	DN0736_04_OT_PROC_CODE varchar2(25) ,
	DN0524_04_OT_PROC_DATE varchar2(8) ,
	DN0736_05_OT_PROC_CODE varchar2(25) ,
	DN0524_05_OT_PROC_DATE varchar2(8) ,
	DN0736_06_OT_PROC_CODE varchar2(25) ,
	DN0524_06_OT_PROC_DATE varchar2(8) ,
	DN0736_07_OT_PROC_CODE varchar2(25) ,
	DN0524_07_OT_PROC_DATE varchar2(8) ,
	DN0736_08_OT_PROC_CODE varchar2(25) ,
	DN0524_08_OT_PROC_DATE varchar2(8) ,
	DN0736_09_OT_PROC_CODE varchar2(25) ,
	DN0524_09_OT_PROC_DATE varchar2(8) ,
	DN0736_10_OT_PROC_CODE varchar2(25) ,
	DN0524_10_OT_PROC_DATE varchar2(8) ,
	DN0736_11_OT_PROC_CODE varchar2(25) ,
	DN0524_11_OT_PROC_DATE varchar2(8) ,
	DN0736_12_OT_PROC_CODE varchar2(25) ,
	DN0524_12_OT_PROC_DATE varchar2(8) ,
	DN0556_1_CONDITION_CODE varchar2(25) ,
	DN0556_2_CONDITION_CODE varchar2(25) ,
	DN0556_3_CONDITION_CODE varchar2(25) ,
	DN0556_4_CONDITION_CODE varchar2(25) ,
	DN0556_5_CONDITION_CODE varchar2(25) ,
	DN0556_6_CONDITION_CODE varchar2(25) ,
	DN0556_7_CONDITION_CODE varchar2(25) ,
	DN0556_8_CONDITION_CODE varchar2(25) ,
	DN0556_9_CONDITION_CODE varchar2(25) ,
	DN0556_10_CONDITION_CODE varchar2(25) ,
	DN0556_11_CONDITION_CODE varchar2(25) ,
	DN0556_12_CONDITION_CODE varchar2(25) ,
	DN0549_PAID_DRG_CODE varchar2(25) ,
	DN0548_BILD_DRG_CODE varchar2(25) ,
	DN0528_BILLING_LAST_NAME varchar2(255) ,
	DN0529_BILLING_FIRST_NAME varchar2(255) ,
	DN0530_BILLING_MIDDLE_Name varchar2(255) ,
	DN0531_BILLING_NAME_SUFFIX varchar2(4) ,
	DN0634_BILLING_NPI varchar2(10) ,
	DN0537_BIL_PRV_PRM_SPL_CODE varchar2(25) ,
	DN0538_BILLING_MAIL_PRIMADD varchar2(100) ,
	DN0539_BILLING_MAIL_SECADD varchar2(100) ,
	DN0540_BILLING_MAIL_CITY varchar2(100) ,
	DN0541_BILLING_MAIL_STATECODE varchar2(25) ,
	DN0542_BILLING_MAIL_POSTCODE varchar2(25) ,
	DN0569_BILLING_MAIL_COUNTRY varchar2(25) ,
	DN0629_BILLING_SSN varchar2(20) ,
	DN0630_BIL_PRV_STE_LIC_NUM varchar2(50) ,
	DN0638_RENDER_LAST_NAME varchar2(255) ,
	DN0639_RENDER_FIRST_NAME varchar2(255) ,
	DN0640_RENDER_MIDDLE_Name varchar2(255) ,
	DN0641_RENDER_NAME_SUFFIX varchar2(4) ,
	DN0647_RENDER_NPI varchar2(10) ,
	DN0651_RENDER_PRV_PRM_SPL_CODE varchar2(25) ,
	DN0642_RENDER_SSN varchar2(9) ,
	DN0643_RENDER_PRV_STE_LIC_NUM varchar2(50) ,
	DN0658_SUPERV_LAST_NAME varchar2(255) ,
	DN0659_SUPERV_FIRST_NAME varchar2(255) ,
	DN0660_SUPERV_MIDDLE_Name varchar2(255) ,
	DN0661_SUPERV_NAME_SUFFIX varchar2(4) ,
	DN0667_SUPERV_NPI varchar2(10) ,
	DN0671_SUPERV_PRV_PRM_SPL_CODE varchar2(25) ,
	DN0663_SUPERV_PRV_STE_LIC_NUM varchar2(50) ,
	DN0678_FACILITY_LAST_NAME varchar2(255) ,
	DN0682_FACILITY_NPI varchar2(30) ,
	DN0684_FACILITY_MAIL_PRIMADD varchar2(255) ,
	DN0685_FACILITY_MAIL_SECADD varchar2(255) ,
	DN0686_FACILITY_MAIL_CITY varchar2(50) ,
	DN0687_FACILITY_MAIL_STATECODE varchar2(25) ,
	DN0688_FACILITY_MAIL_POSTCODE varchar2(10) ,
	DN0689_FACILITY_MAIL_COUNTRY varchar2(25) ,
	DN0680_FAC_PRV_STE_LIC_NUM varchar2(50) ,
	DN0683_FACILITY_SRVC_LOC_ID varchar2(50),
	DN0690_REFER_LAST_NAME varchar2(255) ,
	DN0691_REFER_FIRST_NAME varchar2(255) ,
	DN0692_REFER_MIDDLE_Name varchar2(255) ,
	DN0693_REFER_NAME_SUFFIX varchar2(4) ,
	DN0699_REFER_NPI varchar2(10) ,
	DN0695_REFER_PRV_STE_LIC_NUM varchar2(50) ,
	DN0209_MCO_NAME varchar2(255) ,
	DN0704_MCO_SSN varchar2(9) ,
	DN0208_MCO_IDNUM NUMBER ,
	DN0543_01_BL_ADJ_GRP_CODE varchar2(25) ,
	DN0544_01_BL_ADJ_RSN_CODE varchar2(25) ,
	DN0545_01_BL_ADJ_AMT number(10,2) ,
	DN0546_01_BL_ADJ_UNITS varchar2(15) ,
	DN0544_02_BL_ADJ_RSN_CODE varchar2(25) ,
	DN0545_02_BL_ADJ_AMT number(10,2) ,
	DN0546_02_BL_ADJ_UNITS varchar2(15) ,
	DN0544_03_BL_ADJ_RSN_CODE varchar2(25) ,
	DN0545_03_BL_ADJ_AMT number(10,2) ,
	DN0546_03_BL_ADJ_UNITS varchar2(15) ,
	DN0760_PRIOR_ACT_AMT_PAID number(10,2) ,
	DN0547_01_LINE_NUM varchar2(50) ,
	DN0714_HCPCS_LN_PROCBLD_CDE varchar2(25) ,
	DN0715_JURIS_PROC_BLD_CODE varchar2(25) ,
	DN0721_NDC_BLD_CODE varchar2(25) ,
	DN0551_01_PROC_DESC varchar2(80) ,
	DN0552_01_TOT_CHARGE_PER_LINE number(10,2) ,
	DN0553_01_DAY_PER_UNT_CODE varchar2(25) ,
	DN0554_01_DAY_PER_UNT_BLD varchar2(2) ,
	DN0600_01_PLC_OF_SRVC_LNE_CODE varchar2(25) ,
	DN0557_01_DIAGNOSIS_PTR varchar2(1) ,
	DN0557_02_DIAGNOSIS_PTR varchar2(1) ,
	DN0557_03_DIAGNOSIS_PTR varchar2(1) ,
	DN0557_04_DIAGNOSIS_PTR varchar2(1) ,
	DN0742_PRV_AGRMNT_LINE_CODE varchar2(25) ,
	DN0559_REV_BLD_CODE varchar2(25) ,
	DN0714_1_HCPCS_LN_PROCBLD_CDE varchar2(25) ,
	DN0715_1_JURIS_PROC_BLD_CODE varchar2(25) ,
	DN0625_HIPPS_CODE varchar2(25) ,
	DN0551_02_PROC_DESC varchar2(80) ,
	DN0552_02_TOT_CHARGE_PER_LINE number(10,2) ,
	DN0553_02_DAY_PER_UNT_CODE varchar2(25) ,
	DN0554_02_DAY_PER_UNT_BLD varchar2(2) ,
	DN0719_ADA_PROC_BLD_CDE varchar2(25) ,
	DN0714_2_HCPCS_LN_PROCBLD_CDE varchar2(25) ,
	DN0551_03_PROC_DESC varchar2(80) ,
	DN0552_03_TOT_CHARGE_PER_LINE number(10,2) ,
	DN0600_02_PLC_OF_SRVC_LNE_CODE varchar2(25) ,
	DN0557_05_DIAGNOSIS_PTR varchar2(1) ,
	DN0557_06_DIAGNOSIS_PTR varchar2(1) ,
	DN0557_07_DIAGNOSIS_PTR varchar2(1) ,
	DN0557_08_DIAGNOSIS_PTR varchar2(1) ,
	DN0561_01_PRSCRPTN_LINE_NUM varchar2(50) ,
	DN0714_3_HCPCS_LN_PROCBLD_CDE varchar2(25) ,
	DN0715_2_JURIS_PROC_BLD_CODE varchar2(25) ,
	DN0721_01_NDC_BLD_CODE varchar2(25) ,
	DN0562_DSPNS_AS_WRTN_CODE varchar2(25) ,
	DN0563_DRUG_NAME varchar2(80) ,
	DN0762_CMP_DRG_INDI varchar2(2) ,
	DN0605_SRVC_LINE_DATETO varchar2(17) ,
	DN0605_SRVC_LINE_DATEFROM varchar2(17) ,
	DN0604_PRCRPTN_LINE_DATE varchar2(8) ,
	DN0570_DRG_SUPP_DISP varchar2(15) ,
	DN0571_DRG_SUPP_NO_DAYS varchar2(15) ,
	DN0741_CNTRCT_TYPE_CODE varchar2(25) ,
	DN0738_TRMNT_LINE_AUTHOR_NUM varchar2(50) ,
	DN0579_DRG_SUPP_DIS_FEE varchar2(15) ,
	DN0572_DRG_SUPP_BLD_AMT number(10,2) ,
	DN0627_LINE_ITM_TAX_CHRG_AMT number(10,2) ,
	DN0721_02_NDC_BLD_CODE varchar2(25) ,
	DN0721_03_NDC_BLD_CODE varchar2(25) ,
	DN0553_03_DAY_PER_UNT_CODE varchar2(25) ,
	DN0561_02_PRSCRPTN_LINE_NUM varchar2(50) ,
	DN0589_RENDERL_LAST_NAME varchar2(255) ,
	DN0587_RENDERL_FIRST_NAME varchar2(255) ,
	DN0591_RENDERL_MIDDLE_Name varchar2(255) ,
	DN0588_RENDERL_NAME_SUFFIX varchar2(4) ,
	DN0592_RENDERL_NPI varchar2(10) ,
	DN0595_RENDERLPRV_PRM_SPL_CODE varchar2(25) ,
	DN0586_RENDERL_SSN varchar2(9) ,
	DN0599_RENDERL_PRV_STE_LIC_NUM varchar2(50) ,
	DN0574_TOT_AMT_PAID_PRLINE number(10,2) ,
	DN0722_ADA_PROC_PD_CDE varchar2(25) ,
	DN0726_HCPCS_LN_PROCPD_CDE varchar2(25) ,
	DN0727_HCPCS_MOD_CODE varchar2(25) ,
	DN0728_NDC_PAID_CODE varchar2(25) ,
	DN0729_JURIS_PROC_PD_CDE varchar2(25) ,
	DN0727_01_HCPCS_MOD_CODE varchar2(25) ,
	DN0730_01_JURIS_MOD_CODE varchar2(25),
	DN0727_02_HCPCS_MOD_CODE varchar2(25),
	DN0730_02_JURIS_MOD_CODE varchar2(25),
	DN0727_03_HCPCS_MOD_CODE varchar2(25), 
	DN0730_03_JURIS_MOD_CODE varchar2(25) , 
	DN0727_04_HCPCS_MOD_CODE varchar2(25),
	DN0730_04_JURIS_MOD_CODE varchar2(25),
	DN0576_RVN_PAID_CODE varchar2(25),
	DN0580_DAY_PER_UNT_PAID varchar2(2),
	DN0547_02_LINE_NUM varchar2(50),
	DN0731_01_SVC_ADJ_GRP_CODE varchar2(25),
	DN0732_01_SVC_ADJ_RSN_CODE varchar2(25),
	DN0733_01_SVC_ADJ_AMT number(10,2),
	DN0734_01_SVC_ADJ_UNITS varchar2(15),
	DN0732_02_SVC_ADJ_RSN_CODE varchar2(25),
	DN0733_02_SVC_ADJ_AMT number(10,2),
	DN0734_02_SVC_ADJ_UNITS varchar2(15),
	DN0732_03_SVC_ADJ_RSN_CODE varchar2(25),
	DN0733_03_SVC_ADJ_AMT number(10,2),
	DN0734_03_SVC_ADJ_UNITS varchar2(15),
	DN0732_04_SVC_ADJ_RSN_CODE varchar2(25),
	DN0733_04_SVC_ADJ_AMT number(10,2),
	DN0734_04_SVC_ADJ_UNITS varchar2(15),
	DN0732_05_SVC_ADJ_RSN_CODE varchar2(25),
	DN0733_05_SVC_ADJ_AMT number(10,2),
	DN0734_05_SVC_ADJ_UNITS varchar2(15),
	DN0761_LINE_ITM_PRIOR_ACT_AMT number(10,2),
	DN0628_LINE_ITM_TAX_PAID_AMT number(10,2),
	DN0717_HCPCS_MOD_BLD_CODE varchar2(15),
	DN0717_01_HCPCS_MOD_BLD_CODE varchar2(15),
	DN0717_02_HCPCS_MOD_BLD_CODE varchar2(15),
	DN0717_03_HCPCS_MOD_BLD_CODE varchar2(15),
	DN0717_04_HCPCS_MOD_BLD_CODE varchar2(15),
	DN0717_05_HCPCS_MOD_BLD_CODE varchar2(15),
	DN0717_06_HCPCS_MOD_BLD_CODE varchar2(15),
	DN0717_07_HCPCS_MOD_BLD_CODE varchar2(15),
	DN0718_JURIS_MOD_BLD_CODE varchar2(15),
	DN0718_01_JURIS_MOD_BLD_CODE varchar2(15),
	DN0718_02_JURIS_MOD_BLD_CODE varchar2(15),
	DN0718_03_JURIS_MOD_BLD_CODE varchar2(15),
	DN0718_04_JURIS_MOD_BLD_CODE varchar2(15),
	DN0718_05_JURIS_MOD_BLD_CODE varchar2(15),
	DN0718_06_JURIS_MOD_BLD_CODE varchar2(15),
	DN0718_07_JURIS_MOD_BLD_CODE varchar2(15),
    MEDI_EMPLOYEE_EID NUMBER,
    MEDI_EMPLOYER_EID NUMBER,	
    ENTITY_TYP_QULFR_INS NUMBER,
    ENTITY_TYP_QULFR_EMP NUMBER,
    DN0019_Empr_Phys_PrimAddr varchar2(255), --MKAUR24 START
    DN0020_Empr_Phys_SecAddr varchar2(255), 
    DN0021_Empr_Phys_City varchar2(100), 
    DN0022_Empr_Phys_State_Code varchar2(100), 
    DN0023_Empr_Phys_Pstl_Code varchar2(100), 
    DN0164_Empr_Phys_Cntry_Code varchar2(100),
     ENTITY_TYP_QULFR_BILLP NUMBER,
  MEDI_CERT_NUMBER  Varchar (64) null,        --Added for florida MED 
 MEDI_CODELICENSE_NUMBER  Varchar (64) null, --Added for florida MED 
 MEDI_CLAIMADMIN_TPA_EID   NUMBER NULL,	--Added for florida MED 
 FEDI_REISSUE_REASON_CODE  VARCHAR (25)NULL, --Added for florida MED
 FEDI_TPA_LICNENSE_CODE   VARCHAR (9)NULL, --Added for florida MED
 FEDI_REPORT_TYPE_CODE  VARCHAR (25)NULL, --Added for florida MED
 FL_FORCE_MB_RE   NUMBER NULL,	--Added for florida MED 
 PHY_EID_INV_DET   NUMBER  NULL, --Added for florida MED 
 FL_LICENSE  varchar (25) NULL, --Added for florida MED 
 ZIP_CODE_INV_DET  varchar (10) NULL, --Added for florida MED 
 FEDI_PHY_TAX_ID  varchar (9) NULL, --Added for florida MED 
 FEDI_PHY_NAME  varchar (512) NULL, --Added for florida MED 
 JURIS_LIC_CODE_PHY  varchar (64) NULL, --Added for florida MED
 FL_OPER_PHYS_EID  NUMBER  NULL, --Added for florida MED
 MEDI_EVENT_ID   NUMBER  NULL, --Added for florida MED
 FEDI_DATE_OF_EVENT  varchar (8) NULL, --Added for florida MED
 -- FL_OPR_LIC_NUM  varchar (20) NULL, --Added for florida MED
  FL_OP_PHY_LIC_TEXT  varchar (64) NULL, --Added for florida MED
  FL_ADMISSN_DATE  varchar (8) NULL, --Added for florida MED
  StatmentCoversFrom  varchar (8) NULL, --Added for florida MED
 StatementCoversThough  varchar (8) NULL, --Added for florida MED
 FL_AD_HOUR  NUMBER  NULL, --Added for florida MED
 FL_DC_HOUR  NUMBER  NULL, --Added for florida MED
 FACILITY_TAX_ID   varchar (20) NULL, --Added for florida MED
 DATE_OF_CHECK  varchar (8) NULL, --Added for florida MED
 FL_RCVD_BILL  varchar (8) NULL, --Added for florida MED
 FUNDS_AMOUNT  decimal (10,2) NULL, --Added for florida MED
 FL_CAUSE_1  varchar (25) NULL, --Added for florida MED
 FL_CAUSE_2  varchar (25) NULL, --Added for florida MED
 FL_CAUSE_3  varchar (25) NULL, --Added for florida MED
 FL_RPT_REAS  varchar (25) NULL, --Added for florida MED
 FL_PRE_PMT  varchar (25) NULL, --Added for florida MED
 FL_ADMIT_TYPE  varchar (25) NULL, --Added for florida MED
 FL_PAYTCODE_CODE  varchar (25) NULL, --Added for florida MED
 MEDI_CLAIM_ID  varchar (25) NULL, --Added for florida MED
 FL_SUB_LOC  varchar (25) NULL, --Added for florida MED
 FL_ICD_TYPE_INDICATOR  varchar (25) NULL, --Added for florida MED
 PT_SERVICE_DATE  varchar (8) NULL, --Added for florida MED
 MEDICAL_CHARGE decimal (10,2) NULL, --Added for florida MED
 PHARMACY_CHARGE decimal (10,2) NULL, --Added for florida MED
 FL_PAY_PLAN   varchar (25) NULL, --Added for florida MED
 FL_DUP_IND  varchar (25) NULL, --Added for florida MED
 FL_SCHEDULED_IND  varchar (25) NULL, --Added for florida MED
 FL_IMPLANT_TOTAL  varchar (25) NULL, --Added for florida MED
 FL_FAC_LIC_TEXT  varchar (13) NULL, --Added for florida MED
 FL_FAC_NPI_TEXT  varchar (10) NULL, --Added for florida MED
 FAC_LAST_NAME_TEXT  varchar (255) NULL, --Added for florida MED
 RESUBMISSION_CODE  varchar (11) NULL, --Added for florida MED
 PLACE_OF_SER_CODE  varchar (25) NULL, --Added for florida MED
 FL_PRIMARY_DIAG  varchar (25) NULL, --Added for florida MED
 CODE_NUMBER  varchar (10) NULL  --Added for florida MED
           )'; 
				
EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_EXPORT ADD CONSTRAINT PK_EDI_MEDICAL_EXPORT PRIMARY KEY (JOBID, DA_ROW_ID)';   


END IF;
END;
--==========================================================
---CREATE EDI_MEDICAL_FTS_INVDET table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_FTS_INVDET';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_FTS_INVDET ';
iExists := 0 ;
END IF;

IF iExists = 0 THEN

  EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_FTS_INVDET 
   (TRANS_ID NUMBER,
	AMOUNT number,
	BILL_RCVD_DATE varchar2(8),
	MEDI_BILL_ADJ_CODE varchar2(25),
	INVOICE_ID NUMBER,
	FUNDS_SPLIT_ROW_ID NUMBER,
	MEDI_FACLITY_TYPE_CODE varchar2(25),
	MEDI_PLCE_OF_SRVC_BILL_CODE varchar2(25),
	MEDI_BILL_FORMAT_CODE varchar2(25),
	MEDI_BILL_FREQ_TYPE_CODE varchar2(25),
	TYPE_OF_SER_CODE varchar2(25),
	BILLING_CODE_TEXT varchar2(64) ,
	UNITS_BILLED_NUM number(10,2),
	MEDI_TOT_CHARGE_BILL number(10,2),
	AMOUNT_TO_PAY number(10,2),
	DRUG_NAME varchar2(80),
	PRESCRIP_DATE varchar2(8),
	HCPCS_CODE Varchar2(5),
	MEDI_BILL_TYPE_CODE varchar2(25),
	FROM_DATE varchar2(8),
	TO_DATE varchar2(8),
	MEDI_BILL_PRO_UNI_BILL_ID_NUM varchar2(30),
	INVOICE_DETAIL_ID NUMBER,
	DA_ROW_ID NUMBER NOT NULL,
	JOBID NUMBER NOT NULL,
	PRESCRIP_NO varchar2(30),
	MEDI_NDC_BLD_CODE varchar2(20),
	DISPENSED varchar2(25),
	MEDS_QUANTITY NUMBER,
	DAYS_SUPPLIED NUMBER,
	UNITS_BILLED_TYPE Varchar2(4),
	REV_CODE varchar2(4),
	MEDI_DIAGNOSIS_PTR varchar2(4) ,
	MEDI_CTL_NUMBER varchar2(25),
	MEDI_DRG_SUPP_BLD_AMT number(10, 2),
	MEDI_ADJUSTMENT_AMT number(10, 2),
	RX_USUAL_CHARGE number(10, 2),
   PHY_EID_INV_DET   NUMBER  NULL,
	 FL_LICENSE  varchar (25) NULL,
	 ZIP_CODE_INV_DET  varchar (10) NULL,
	 TABLE_CODE  NUMBER  NULL,
	 MODIFIER_CODE  varchar (25) NULL,
	 RX_IND  NUMBER  NULL,
	 CERTIFICATION  NUMBER  NULL,
	 PHY_PHARM_NDC_SEC  varchar (20) NULL,
	 MED_SUPPLY_FLAG  NUMBER  NULL,
	 PURCHASED_IND  NUMBER  NULL
  )';

EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_FTS_INVDET ADD CONSTRAINT PK_EDI_MEDICAL_FTS_INVDET PRIMARY KEY (JOBID, DA_ROW_ID)';   

END IF;
END;



--==========================================================
---CREATE EDI_MEDICAL_FEDI_FTS table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_FEDI_FTS';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_FEDI_FTS ';
iExists := 0 ;
END IF;
IF iExists = 0 THEN
EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_FEDI_FTS(
	TRANS_ID NUMBER NULL,
	FUNDS_SPLIT_ROW_ID NUMBER NULL,
	BILLING_CODE_TEXT varchar(64) NULL,
	UNITS_BILLED_NUM NUMBER(10, 2) NULL,
	MEDI_TOT_CHARGE_BILL NUMBER(10, 2) NULL,
	REV_CODE varchar(4) NULL,
	MEDI_BILL_TYPE_CODE varchar(25) NULL,
	DA_ROW_ID NUMBER NOT NULL,
	JOBID NUMBER NOT NULL,
	MODIFIER_CODE varchar(25) NULL,
	MODIFIER_CODE_1 varchar(25) NULL,
	MODIFIER_CODE_2 varchar(25) NULL,
	MODIFIER_CODE_3 varchar(25) NULL,
	MODIFIER_CODE_4 varchar(25) NULL,
	INVOICE_DETAIL_ID NUMBER NULL,
	EOB_CODE_1 varchar(2) NULL,
	EOB_CODE_2 varchar(2) NULL,
	EOB_CODE_3 varchar(2) NULL,
	MEDS_QUANTITY NUMBER NULL,
	DAYS_SUPPLIED NUMBER NULL,
	PRESCRIP_NO varchar(30) NULL,
	PHY_EID_INV_DET NUMBER NULL,
	PRESCRIP_DATE varchar(8) NULL,
	RX_USUAL_CHARGE NUMBER(10, 2) NULL,
	RX_IND NUMBER NULL,
	CERTIFICATION NUMBER NULL,
	PHY_PHARM_NDC_SEC varchar(20) NULL,
	MED_SUPPLY_FLAG NUMBER NULL,
	PURCHASED_IND NUMBER NULL,
	DISPENSED varchar(25) NULL,
	FL_LICENSE varchar(25) NULL,
	PHY_LIC_NUM_PHY_T varchar(13) NULL,
	HCPCS_CODE varchar(5) NULL,
	--TRANS_ID_1 NUMBER NULL,
	MEDI_NDC_BLD_CODE varchar(20) NULL,
	MEDI_PLCE_OF_SRVC_BILL_CODE varchar(25) NULL,
	DIAG_REF_NO varchar(4) NULL,
	AMOUNT_TO_PAY NUMBER(10, 2) NULL,
	FROM_DATE varchar(8) NULL,
	TO_DATE varchar(8) NULL,
	MEDI_BILL_FORMAT_CODE varchar(25) NULL,
	MEDI_BILL_FREQ_TYPE_CODE varchar(25) NULL,
	TYPE_OF_SER_CODE varchar(25) NULL,
	DRUG_NAME varchar(80) NULL,
	ZIP_CODE_INV_DET varchar(10) NULL )';
EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_FEDI_FTS ADD CONSTRAINT PK_EDI_MEDICAL_FEDI_FTS PRIMARY KEY (JOBID, DA_ROW_ID)';   

END IF;
END;



--==========================================================
---CREATE EDI_MEDICAL_UPD_CTLNO table 
--============================================================

BEGIN
SELECT COUNT(*) INTO iExists FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME='EDI_MEDICAL_UPD_CTLNO';

IF iExists != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EDI_MEDICAL_UPD_CTLNO ';
iExists := 0 ;
END IF;
IF iExists = 0 THEN
EXECUTE IMMEDIATE 'CREATE TABLE EDI_MEDICAL_UPD_CTLNO(
	MEDI_CTL_NUMBER varchar(50) NULL,
	TRANS_ID Number NULL,
	DA_ROW_ID Number NOT NULL,
	JOBID Number NOT NULL )';
  EXECUTE IMMEDIATE 'ALTER TABLE EDI_MEDICAL_UPD_CTLNO ADD CONSTRAINT PK_EDI_MEDICAL_UPD_CTLNO PRIMARY KEY (JOBID, DA_ROW_ID)';   

END IF;
END;
  
  

--==========================================================
---INSERT  ERROR MESSAGES IN EDI_MEDICAL_ERROR_LOG  table
--============================================================
begin
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0615_TO_XX'''||','||'''WA'''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0615_FROM_XX'''||','||'''WA'''||','||'''Must be a valid DATE in CCYYMMDD format and prior to 
DN0615_TO_XX'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0532_XX'''||','||''''''||','||'''Must be A-Z/0-9/spaces'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0101_XX'''||','||''''''||','||'''Must be a valid Time'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0100_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0006_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0050_XX'''||','||'''NC'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0052_XX'''||','||'''WA/NC'''||','||'''Must be a valid DOB in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0053_XX'''||','||'''WA/NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0098_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0099_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0005_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0007_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0043_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0044_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0153_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0154_XX'''||','||'''OR/NC'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0156_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0152_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0042_XX'''||','||'''OR/NC'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0048_XX'''||','||'''NC'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0049_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0050_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0031_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0018_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0015_XX'''||','||''''''||','||'''Must be A-Z/0-9/spaces'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0523_XX'''||','||''''''||','||'''Must be A-Z/0-9/spaces'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0188_XX'''||','||''''''||','||'''Data must be present because Claim Administrator is a different entity than 
the insurer'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0187_XX'''||','||''''''||','||'''Data must be present because Claim Administrator is a different entity than 
the insurer'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0014_XX'''||','||''''''||','||'''Data must be present because Claim Administrator is a different entity than 
the insurer'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0501_XX'''||','||''''''||','||'''Either amount is not provided or it does not balance to the sum of all charge 
amounts reported at the line level or to the drugs/billed amount'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0502_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0504_XX'''||','||''''''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0555_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0503_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0505_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0507_XX'''||','||'''WA'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0508_XX'''||','||''''''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0511_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format and should be greater than 
Date_of_injury'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0509_TO_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD 
format'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0509_FROM_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format and prior to 
DN0509_TO_XX'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0527_TO_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0527_FROM_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format and prior to 
DN0527_TO_XX'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0510_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format and should be greater than 
Date_of_injury'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0516_XX'''||','||''''''||','||'''Either field is blank or its sum is not equal to sum of Total amount paid per 
line/split'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0500_XX'''||','||''''''||','||'''Must be A-Z/0-9/spaces'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0266_XX'''||','||''''''||','||'''Must be A-Z/0-9/spaces'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0521_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0535_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0513_XX'''||','||'''WA/OR'''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0514_XX'''||','||'''WA/OR'''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0515_XX'''||','||'''OR'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0520_XX'''||','||'''OR'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0520_1_XX'''||','||'''OR'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0577_XX'''||','||'''WA/OR/NC'''||','||'''Mandatory Fields as per the type of medical bill extracted are not 
present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0521_01_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0550_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD 
format'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_01_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_02_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_03_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_04_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_05_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_06_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_07_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_08_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_09_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_10_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_11_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0524_12_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0528_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0529_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0634_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_01_XX'''||','||'''WA/NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_02_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_03_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_04_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_05_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_06_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_07_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_08_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_09_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_10_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_11_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_12_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0533_13_XX'''||','||'''NC'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0538_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0540_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0629_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0647_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0684_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0686_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0543_XX'''||','||''''''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0541_XX'''||','||'''WA/NC'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0542_XX'''||','||'''WA/NC'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0543_XX'''||','||'''WA'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0569_XX'''||','||'''OR/NC'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0630_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0678_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0639_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0643_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0647_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0651_XX'''||','||'''OR'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0682_XX'''||','||'''WA/OR'''||','||'''Mandatory fields are not 
present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0687_XX'''||','||'''WA/NC'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0688_XX'''||','||'''WA/NC'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0689_XX'''||','||'''WA/OR/NC'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0690_XX'''||','||'''OR/NC'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0691_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0695_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0699_XX'''||','||'''WA/OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0209_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0208_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0714_XX'''||','||'''WA/OR/NC'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0715_XX'''||','||'''WA/OR/NC'''||','||'''Either code is not populated or invalid code is 
populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0721_XX'''||','||'''WA/OR/NC'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0714_1_XX'''||','||'''WA/OR'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0715_1_XX'''||','||'''WA/OR'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0719_XX'''||','||'''WA/OR'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0714_2_XX'''||','||'''WA/OR'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0714_3_XX'''||','||'''WA'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0715_2_XX'''||','||'''WA'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0721_01_XX'''||','||'''WA'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0722_XX'''||','||'''WA/OR'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0726_XX'''||','||'''WA/OR'''||','||'''Either code is not populated or invalid code is 
populated'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0728_XX'''||','||'''WA/OR'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0729_XX'''||','||'''WA/OR'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0762_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0579_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0544_01_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0544_02_XX'''||','||'''OR'''||','||'''Mandatory fields are not 
present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0544_03_XX'''||','||'''OR'''||','||'''Mandatory fields are not 
present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0545_01_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0545_02_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0545_03_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0546_01_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0546_02_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0546_03_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0547_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0547_02_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0553_XX'''||','||''''''||','||'''Either value is not present or invalid code is present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0554_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0600_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0557_01_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0552_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0552_02_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0552_03_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0553_01_XX'''||','||''''''||','||'''Either value is not present or invalid code is present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0553_02_XX'''||','||''''''||','||'''Either value is not present or invalid code is present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0554_01_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0554_02_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0557_05_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0561_01_XX'''||','||''''''||','||'''Must be A-Z/0-9/spaces'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0721_01_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0562_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0563_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0605_TO_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0605_FROM_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format and prior to 
DN0605_TO_XX'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0604_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDD format'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0570_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0616_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0571_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0572_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0721_03_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0561_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0574_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0731_XX'''||','||''''''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0293_XX'''||','||''''''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0732_01_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0733_01_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0734_01_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0732_02_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0733_02_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0734_02_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0732_03_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0733_03_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0734_03_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0732_04_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0733_04_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0734_04_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0732_05_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0733_05_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0734_05_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0044_XX'''||','||''''''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0587_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0592_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0595_XX'''||','||'''OR'''||','||'''Either code is not populated or invalid code is populated'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0599_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0628_XX'''||','||'''OR'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0622_XX'''||','||'''NC'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0623_XX'''||','||'''NC'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0658_XX'''||','||'''NC'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0155_XX'''||','||'''NC'''||','||'''Mandatory fields are not present'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0512_XX'''||','||''''''||','||'''Must be a valid DATE in CCYYMMDDformat'''||','||'''EDI_MEDICAL_FUNDS_INV'''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG VALUES ('||'''DN0559_XX'''||','||''''''||','||'''Either code is not populated or invalid code is populated'''||','||'''EDI_MEDICAL_FTS_INVDET'''||')';

---------------------ERROR MEssages for Florida EDI------------------------
---------------------ERROR MEssages for Florida EDI------------------------
---------------------ERROR MEssages for Florida EDI------------------------

EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_REVCODE_H'''||','||''''''||','||'''Revenue Billed Code missing for Payment'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_BILLCDTXT_H'''||','||''''''||','||'''Procedure, Service, Supply Billed Code is wrong length'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_UNITBL_HPHY'''||','||''''''||','||'''Day(s)/Unit(s)Billed for Payment.'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_TOTCRGLINE_H'''||','||''''''||','||'''Total Charge Per Line is missing for Payment.'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_SERLINEDT_H'''||','||''''''||','||'''Service Line Date From is out of position'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_TOTAMTPAY_H'''||','||''''''||','||'''Total Amount Paid Per Line is required when field 10A is Ambulatory Surgical Center'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_MEDQ_PR'''||','||''''''||','||'''Drugs/Supplies Quantity Dispensed missing for Payment.'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_DAYSUP_PR'''||','||''''''||','||'''Drugs Number Of Days is missing for claim'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_BILLCDTXT_PRD'''||','||''''''||','||'''NDC Number - Primary is missing for Payment'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_RXIND_PR'''||','||''''''||','||'''Prescription Type Code missing for Payment'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''D_FL_PURCHIND_PR'''||','||''''''||','||'''Purchased/Rental Indicator missing for Payment'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_PRESDT_PR'''||','||''''''||','||'''Purchase/Rental Date missing for Payment'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_DSPNSED_PR'''||','||''''''||','||'''Dispense As Written Code missing for Payment.'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_PHRMLICNO_PR'''||','||''''''||','||'''Prescriber'||''''''||'s State License Number is missing for Payment.'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_RXUSCHRG_PR'''||','||''''''||','||'''Total Amount Charged Per Line missing for Payment.'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_HPCS_PR'''||','||''''''||','||'''Procedure, Service, Supply Billed Code missing for Payment. '''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_TOAMTPAY_PRPH'''||','||''''''||','||'''Total Amount Paid Per Line missing for Payment.'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_PLCSER_P'''||','||''''''||','||'''Physican Detail, Diagnosis Pointer missing for claim'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_BILLCDTXT_P'''||','||''''''||','||'''Procedure, Service, Supply Billed Code missing for Payment.'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_TOTCHRBL_PD'''||','||''''''||','||'''Total Charge Per Line missing for the claim'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_FRMDT_P'''||','||''''''||','||'''Service Line Date From missing for the claim'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_TODT_PHY'''||','||''''''||','||'''Service Line Date To missing for the claim.'''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_D_NDCNUM_P'''||','||''''''||','||'''NDC Number - Primary is missing for Payment. '''||','||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_SENDERID_XX'''||','||''''''||','||'''Florida Submitter ID was not found.  This is a required (mandatory) value.'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_CLMNT_XX'''||','||''''''||', '||'''No valid claimant for Claim'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_INSCODENUM_XX'''||','||''''''||','||'''Insurer Code Number is missing for claim'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_TPALICCODE_XX'''||','||''''''||'	,'||'''TPA, Claim Administrator Code Number is missing'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_CLMADMFIEN_XX'''||','||''''''||'	,'||'''Claim Administrator FEIN is missing'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_CLMADMZIP_XX'''||','||''''''||','||'''Claim Administrator Physical Postal Code is missing'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_RPTTYPECODE_HP'''||','||''''''||'	,'||'''Type of Report is missing for Payment.'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_EMPSSN_XX'''||'	,'||''''''||','||'''Employee Jurisdiction Assigned Indentification Number is missing for claim'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_EMPLNAME_XX'''||','||''''''||',	'||'''Employee Last Name is missing in claim'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_EMPFNAME_XX'''||','||''''''||',	'||'''Employee First Name is missing in claim'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_EMPDOB_XX'''||','||''''''||','||'''Employee Date Of Birth is missing'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_EMPGNDR_XX'''||','||''''''||','||'''Employee Gender Code is missing'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_OPPHYLIC_H'''||','||''''''||',	'||'''Rendering Bill Provider State License Number is missing for claim'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_ADHR_H'''||',	'||''''''||','||'''Admission Hour is missing for Payment'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_ADMDT_H'''||','||''''''||',	'||'''Admission Date is missing for Payment'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_FROMDT_H'''||','||''''''||',	'||'''Service Bill Date From is missing for Payment'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_TODT_FL'''||'	,'||''''''||','||'''Service Bill Date Through is missing for Payment'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_INSRCVBL_HPD'''||','||''''''||','||'''Date Insurer Paid Bill is missing for Payment'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_DTINSPAID_HPD'''||','||''''''||','||'''Total Amount Paid Per Bill missing for Payment'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_PRIDIAGCODE_H'''||','||''''''||','||'''Principal ICD Diagnostic Code is missing for Payment.'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_RPTRESN_HPD'''||','||''''''||','||'''Bill Submission Reason Code missing for Payment'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_ADMTYPECODE_H'''||','||''''''||','||'''Admission Type Code is missing for Payment.'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_CLMCTL_HPPY'''||',	'||''''''||','||'''Claim Administrator Claim Number missing for claim'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_FACLICNPI_H'''||','||''''''||','||'''Facility data (Facility License and NPINumber is missing'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_ICDIND_PH'''||','||''''''||','||'''ICD Type Indicator is missing for Payment'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_PAYPLAN_PR'''||','||''''''||','||'''Payment Code is missing for Payment.'''||', '||''''''||')';
EXECUTE IMMEDIATE 'INSERT INTO EDI_MEDICAL_ERROR_LOG values('||'''FL_PLCSERCOD_D'''||','||''''''||','||'''Place of Treatment for Payment is missing.'''||', '||''''''||')';

end;
Commit;
END IF;
end;





